from typing import Any, Protocol


class ProjectInputModelProtocol(Protocol):
    ontology_model: Any
    project_input_model_dict: dict[str, Any]
    filter_results: dict[str, list[Any]]

    def set_project_id(self, proj_id: str) -> None: ...

    def update(self, attribute_name: str, result: Any) -> None: ...

    def set(self, attribute_name: str, result: Any) -> None: ...

    def add_properties(self, dict_properties: dict[str, Any]) -> None: ...

    def get(self, attribute_name: str) -> Any: ...

    def get_nested_value_with_references(
        self, structure: dict[str, Any], nested_address: str
    ) -> Any: ...

    def run_filter(self, results_name: str, equation: str) -> None: ...

    def run_equation(self, equation: str, params: list[Any] | None = None) -> Any: ...

    def complete_access_control_mapping(self) -> None: ...
