schema_dict = {
    "app_tnc": "1.0.0",
    "kb_assessment_config": "1.0.11",
    "kb_attack_flow": "1.0.0",
    "kb_attack_graph_rule": "1.0.2",
    "kb_generation_rule": "2.3.2",
    "kb_generation_rules_library": "1.3.0",
    "kb_gt_llm_register": "1.1.0",
    "kb_llm_prompt": "1.0.21",
    "kb_owasp_register": "1.0.0",
    "kb_priority_rules": "1.2.8",
    "kb_question_to_model": "2.9.13",
    "kb_register_mapping": "1.2.0",
    "kb_tosca": "1.4.3",
    "master_ad_template": "1.0.0",
    "master_cq_template": "2.45.7",
    "master_cq": "2.45.15",
    "master_mitigation_mapping": "1.2.1",
    "master_mitigation": "1.3.18",
    "master_register": "1.12.0",
    "user_plan_config": "1.0.0",
}
