"""Configuration-driven model extraction primitives.

This module implements :class:`ModelExtractorBase`, the extraction layer used to
transform questionnaire and diagram answer payloads into normalized project model
objects. It focuses on:

- resolving answers from nested data structures,
- executing configured creation/extraction functions,
- building object attributes and references, and
- handling dynamic-key payload patterns generated by form builders.
"""

import copy
import logging
import re
from typing import Any

from engine_libs.utils.data_extractor_util import DataExtractorUtil

from shared_libs.decorators import raise_exception
from shared_libs.protocols import ProjectInputModelProtocol

from .model_solver_base import ModelSolverBase

logger = logging.getLogger(__name__)


class ModelExtractorBase(ModelSolverBase):
    """
    Handles extraction logic for converting questionnaire and diagram data into structured models.

    Provides functionality for data processing, object creation, reference resolution,
    and complex extraction operations with dynamic key handling.
    """

    # ============================================================================
    # INITIALIZATION
    # ============================================================================

    @raise_exception(
        "Failed to initialize ModelExtractorBase.",
        exception_logger=logger,
    )
    def __init__(
        self,
        project_input_model: ProjectInputModelProtocol,
    ) -> None:
        """
        Initialize the model extraction instance.

        Args:
            project_input_model: The project input model to work with
        """
        self.project_input_model: ProjectInputModelProtocol = project_input_model
        super().__init__(project_input_model=self.project_input_model)
        logger.info("[ RR-PROJECT-MODEL ] ModelExtractorBase initialized successfully.")

    # ============================================================================
    # PUBLIC API METHODS
    # ============================================================================

    @raise_exception(
        "Failed to run creation equation.",
        exception_logger=logger,
    )
    def run_creation_equation(
        self,
        function: str,
        answer: Any,
        parameters: Any | None = None,
    ) -> Any:
        """
        Run a creation equation with the given function and answer.

        Args:
            function: The function name to execute
            answer: The answer data to process
            parameters: Optional parameters for the function

        Returns:
            Result of the function execution
        """
        if not parameters:
            return eval("self." + function + "(answer)")
        else:
            return eval("self." + function + "(answer,parameters)")

    @raise_exception(
        "Failed to run extraction logic.",
        exception_logger=logger,
    )
    def run_extraction_logic(
        self,
        extraction_logic: dict[str, Any],
        answer: Any,
    ) -> tuple[Any, dict[str, Any]]:
        """
        Run extraction logic based on the provided configuration.

        Args:
            extraction_logic: The extraction logic configuration
            answer: The answer data to process

        Returns:
            Tuple of (result, checks) where result is the extracted data and checks contains validation info
        """
        parameters = self._get_extraction_parameters(extraction_logic)

        match extraction_logic["function"]:
            case "pre_requisite":
                return self._handle_prerequisite_extraction(
                    extraction_logic, answer, parameters
                )
            case _:
                result = self.run_creation_equation(
                    extraction_logic["function"], answer, parameters
                )
                return result, {}

    @raise_exception(
        "Failed to get answer from structure.",
        exception_logger=logger,
    )
    def get_answer_from_structure(
        self,
        answers: Any,
    ) -> Any | None:
        """
        Get answer from structure, handling empty or None values.

        Args:
            answers: The answer structure to process

        Returns:
            The answer if valid, None otherwise
        """
        if answers != "" and answers is not None:
            return answers
        return None

    @raise_exception(
        "Failed to get answer from data.",
        exception_logger=logger,
    )
    def get_answer(
        self,
        data: Any,
        answer_id: str,
    ) -> Any | None:
        """
        Get answer from data using the answer ID.

        Args:
            data: The data structure to search in
            answer_id: The ID of the answer to retrieve

        Returns:
            The answer if found, None otherwise
        """
        answers = DataExtractorUtil.get_value_from_structure_recursive(data, answer_id)
        return self.get_answer_from_structure(answers)

    @raise_exception(
        "Failed to get raw answer from data.",
        exception_logger=logger,
    )
    def get_raw_answer(
        self,
        data: Any,
        answer_id: str,
    ) -> Any:
        """
        Get raw answer from data without processing.

        Args:
            data: The data structure to search in
            answer_id: The ID of the answer to retrieve

        Returns:
            The raw answer data
        """
        return DataExtractorUtil.get_value_from_structure_recursive(data, answer_id)

    @raise_exception(
        "Failed to extract cell info.",
        exception_logger=logger,
    )
    def extract_cell_info(
        self,
        answer: Any,
        parameters: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Extract cell information based on parameters.

        Args:
            answer: The answer data to process
            parameters: Parameters defining how to extract the information

        Returns:
            Dictionary containing extracted information
        """
        new_object = {}

        if not answer:
            return new_object

        param_key = parameters["keyName"]

        extraction_methods = {
            "attribute": lambda: self._extract_attribute_info(
                answer, param_key, parameters
            ),
            "objectRef": lambda: self._extract_object_ref_info(
                answer, param_key, parameters
            ),
            "keyValueMapping": lambda: self._extract_key_value_mapping(
                answer, param_key, parameters
            ),
            "objectId": lambda: self._extract_object_id(answer, param_key),
        }

        key_meaning = parameters["keyMeaning"]
        return extraction_methods.get(key_meaning, lambda: new_object)()

    # ============================================================================
    # CONFIGURATION-DRIVEN METHODS (Called via kb_question_to_model.json)
    # ============================================================================

    @raise_exception(
        "Failed to create new value.",
        exception_logger=logger,
    )
    def create_new_value(
        self,
        answer: Any,
    ) -> Any:
        """
        Create a new value from the answer.

        Called externally through configuration-driven system (kb_question_to_model.json).

        Args:
            answer: The answer data to process

        Returns:
            The processed answer
        """
        return answer

    @raise_exception(
        "Failed to create new object per cell.",
        exception_logger=logger,
    )
    def create_new_object_per_cell(
        self,
        answers: list[Any],
        parameters: list[dict[str, Any]] | None = None,
    ) -> list[dict[str, Any]]:
        """
        Create new objects per cell from answers and parameters.

        Called externally through configuration-driven system (kb_question_to_model.json).

        Args:
            answers: List of answer data to process
            parameters: Optional parameters for processing

        Returns:
            List of created objects
        """
        return_object = []
        if not answers:
            return return_object

        current_list_id = []
        obj_id = 0

        for answer in answers:
            new_object = {"id": obj_id}
            obj_id = obj_id + 1

            for param in parameters:
                mini_object = self.extract_cell_info(answer, param)
                new_object.update(mini_object)

            if new_object["id"] not in current_list_id:
                return_object.append(new_object)
                current_list_id.append(new_object["id"])

        return return_object

    @raise_exception(
        "Failed to create new object nested per cell.",
        exception_logger=logger,
    )
    def create_new_object_nested_per_cell(
        self,
        answers: list[Any],
        parameters: list[dict[str, Any]] | None = None,
    ) -> list[dict[str, Any]]:
        """
        Create new objects per cell from answers and parameters.

        Called externally through configuration-driven system (kb_question_to_model.json).

        Args:
            answers: List of answer data to process
            parameters: Optional parameters for processing

        Returns:
            List of created objects
        """
        return_object = []
        if not answers:
            return return_object

        current_list_id = []
        obj_id = 0

        for answer in answers:
            new_object = {"id": obj_id}
            obj_id = obj_id + 1

            for param in parameters:
                if "nest_type" not in param:
                    mini_object = self.extract_cell_info(answer, param)
                    new_object.update(mini_object)
                else:
                    answer_key = DataExtractorUtil.get_value_from_structure_recursive(
                        answer, param["keyName"]
                    )
                    new_key_name = (
                        param["newKeyName"]
                        if "newKeyName" in param
                        else param["keyName"]
                    )
                    func_name = param.get("subfunction")
                    if param["nest_type"] == "object":
                        if func_name == "create_new_object_nested":
                            new_object[new_key_name] = self.create_new_object_nested(
                                answer_key, param["parameters"]
                            )
                        else:
                            new_object[new_key_name] = {}
                    elif param["nest_type"] == "list":
                        if func_name == "create_new_object_per_cell":
                            new_object[new_key_name] = self.create_new_object_per_cell(
                                answer_key, param["parameters"]
                            )
                        else:
                            new_object[new_key_name] = []

            if new_object["id"] not in current_list_id:
                return_object.append(new_object)
                current_list_id.append(new_object["id"])

        return return_object

    @raise_exception(
        "Failed to create new object nested per cell.",
        exception_logger=logger,
    )
    def create_new_object_nested(
        self,
        answers: Any,
        parameters: list[dict[str, Any]] | None = None,
    ) -> dict[str, Any]:
        """
        Create new objects per cell from answers and parameters.

        Called externally through configuration-driven system (kb_question_to_model.json).

        Args:
            answers: List of answer data to process
            parameters: Optional parameters for processing

        Returns:
            List of created objects
        """
        new_object = {}

        if not answers:
            return new_object

        for param in parameters:
            if "nest_type" not in param:
                mini_object = self.extract_cell_info(answers, param)
                new_object.update(mini_object)
            else:
                if param["nest_type"] == "object":
                    answer_key = DataExtractorUtil.get_value_from_structure_recursive(
                        answers, param["keyName"]
                    )
                    new_key_name = (
                        param["newKeyName"]
                        if "newKeyName" in param
                        else param["keyName"]
                    )
                    func_name = param.get("function")

                    if func_name == "create_new_object_nested":
                        new_object[new_key_name] = self.create_new_object_nested(
                            answer_key, param["parameters"]
                        )
                elif param["nest_type"] == "list":
                    if func_name == "create_new_object_per_cell":
                        new_object[new_key_name] = self.create_new_object_per_cell(
                            answer_key, param["parameters"]
                        )
                    else:
                        new_object[new_key_name] = []

        return new_object

    @raise_exception(
        "Failed to create multiple new object per cell.",
        exception_logger=logger,
    )
    def create_multiple_new_object_per_cell(
        self,
        answers: list[Any],
        parameters: list[list[dict[str, Any]]] | None = None,
    ) -> list[dict[str, Any]]:
        """
        Create multiple new objects per cell with dynamic key handling.

        Called externally through configuration-driven system (kb_question_to_model.json).

        Args:
            answers: List of answer data to process
            parameters: Optional parameters for processing

        Returns:
            List of created objects
        """
        if not answers:
            return []

        KEY_PATTERN = re.compile(r"^[a-z]+_[a-zA-Z0-9]{22}$")
        return_object = []
        obj_id = 0

        for answer in answers:
            dynamic_keynames = self._find_dynamic_keynames(answer, KEY_PATTERN)
            obj_id = self._process_answer_with_dynamic_keys(
                answer, parameters, dynamic_keynames, return_object, obj_id
            )

        return return_object

    @raise_exception(
        "Failed to create new object attribute.",
        exception_logger=logger,
    )
    def create_new_object_attribute(
        self,
        answer: Any,
    ) -> dict[str, Any]:
        """
        Create a new object attribute from the answer.

        Called externally through configuration-driven system (kb_question_to_model.json).

        Args:
            answer: The answer data to process

        Returns:
            Dictionary with value property
        """
        return {"value": answer}

    @raise_exception(
        "Failed to create new object ref.",
        exception_logger=logger,
    )
    def create_new_object_ref(
        self,
        answer: Any,
        parameters: dict[str, Any] | None = None,
    ) -> Any:
        """
        Create a new object reference.

        Called externally through configuration-driven system (kb_question_to_model.json).

        Args:
            answer: The answer data to process
            parameters: Optional parameters for reference creation

        Returns:
            The referenced object
        """
        ref_attribute_name = parameters["ref_attribute"]

        obj = self.project_input_model.get_object(
            ref_attribute_name,
            answer,
        )
        return obj

    @raise_exception(
        "Failed to append new object ref.",
        exception_logger=logger,
    )
    def append_new_object_ref(
        self,
        answer: Any,
        parameters: dict[str, Any] | None = None,
    ) -> Any:
        """
        Append a new object reference.

        Called externally through configuration-driven system (kb_question_to_model.json).

        Args:
            answer: The answer data to process
            parameters: Optional parameters for reference creation

        Returns:
            The referenced object
        """
        return self.create_new_object_ref(
            answer,
            parameters=parameters,
        )

    @raise_exception(
        "Failed to create new object.",
        exception_logger=logger,
    )
    def create_new_object(
        self,
        answer: list[Any],
    ) -> list[dict[str, Any]]:
        """
        Create new objects from a list of answers.

        Available for configuration-driven system (kb_question_to_model.json).

        Args:
            answer: List of answer data to process

        Returns:
            List of objects with value properties
        """
        return_object = []
        if not answer:
            return return_object

        obj_id = 0
        for cell in answer:
            new_object = {}
            new_object["value"] = cell
            obj_id = obj_id + 1
            return_object.append(new_object)

        return return_object

    # ============================================================================
    # EXTRACTION LOGIC ORCHESTRATION
    # ============================================================================

    @raise_exception(
        "Failed to get extraction parameters.",
        exception_logger=logger,
    )
    def _get_extraction_parameters(
        self,
        extraction_logic: dict[str, Any],
    ) -> Any | None:
        """
        Get parameters from extraction logic if present.

        Args:
            extraction_logic: The extraction logic configuration

        Returns:
            Parameters if present, None otherwise
        """
        return extraction_logic.get("parameters")

    @raise_exception(
        "Failed to handle prerequisite extraction.",
        exception_logger=logger,
    )
    def _handle_prerequisite_extraction(
        self,
        extraction_logic: dict[str, Any],
        answer: Any,
        parameters: Any | None,
    ) -> tuple[dict[str, Any] | None, dict[str, Any]]:
        """
        Handle prerequisite-based extraction logic.

        Args:
            extraction_logic: The extraction logic configuration
            answer: The answer data to process
            parameters: Optional parameters

        Returns:
            Tuple of (result, checks) for prerequisite extraction
        """
        checks = self._create_prerequisite_checks()
        pre_req_check = self._evaluate_prerequisite_condition(extraction_logic)

        result = self.run_creation_equation(
            extraction_logic["subfunction"], answer, parameters
        )

        return self._process_prerequisite_result(
            extraction_logic, result, pre_req_check, checks
        )

    @raise_exception(
        "Failed to create prerequisite checks.",
        exception_logger=logger,
    )
    def _create_prerequisite_checks(self) -> dict[str, bool]:
        """Create initial prerequisite checks dictionary."""
        return {
            "is_pre_req": True,
            "is_pre_req_check": True,
        }

    @raise_exception(
        "Failed to evaluate prerequisite condition.",
        exception_logger=logger,
    )
    def _evaluate_prerequisite_condition(
        self,
        extraction_logic: dict[str, Any],
    ) -> bool:
        """Evaluate if prerequisite condition is met."""
        pre_req_attribute = extraction_logic["condition"]["attribute"]
        pre_req_value = extraction_logic["condition"]["match"]
        value = self.project_input_model.get(pre_req_attribute)
        return value == pre_req_value

    @raise_exception(
        "Failed to process prerequisite result.",
        exception_logger=logger,
    )
    def _process_prerequisite_result(
        self,
        extraction_logic: dict[str, Any],
        result: Any,
        pre_req_check: bool,
        checks: dict[str, bool],
    ) -> tuple[dict[str, Any] | None, dict[str, bool]]:
        """Process the result of prerequisite extraction."""
        if pre_req_check and result is not None and len(result) != 0:
            new_subattribute_name = extraction_logic["attributeName"]
            return {new_subattribute_name: result}, checks
        else:
            checks["is_pre_req_check"] = False
            return None, checks

    # ============================================================================
    # CELL INFORMATION EXTRACTION METHODS
    # ============================================================================

    @raise_exception(
        "Failed to extract attribute info.",
        exception_logger=logger,
    )
    def _extract_attribute_info(
        self, answer: Any, param_key: str, parameters: dict[str, Any]
    ) -> dict[str, Any]:
        """
        Extract attribute information from answer.

        Args:
            answer: The answer data
            param_key: The parameter key
            parameters: The parameters configuration

        Returns:
            Dictionary with extracted attribute
        """
        new_object = {}
        new_attribute_name = parameters["parameters"][0]
        new_object[new_attribute_name] = self.get_answer_from_structure(
            DataExtractorUtil.get_value_from_structure_recursive(answer, param_key)
        )
        return new_object

    @raise_exception(
        "Failed to extract object ref info.",
        exception_logger=logger,
    )
    def _extract_object_ref_info(
        self, answer: Any, param_key: str, parameters: dict[str, Any]
    ) -> dict[str, Any]:
        """
        Extract object reference information from answer.

        Args:
            answer: The answer data
            param_key: The parameter key
            parameters: The parameters configuration

        Returns:
            Dictionary with extracted object reference
        """
        new_object = {}
        answer_key = DataExtractorUtil.get_value_from_structure_recursive(
            answer, param_key
        )

        if answer_key is not None:
            if isinstance(answer_key, list):
                new_object_ref = []
                for ref_obj in answer_key:
                    new_o = self.create_new_object_ref(
                        self.get_answer_from_structure(ref_obj),
                        parameters["parameters"],
                    )
                    new_object_ref.append(new_o)
            else:
                new_object_ref = self.create_new_object_ref(
                    self.get_answer_from_structure(answer_key),
                    parameters["parameters"],
                )

            new_obj_attribute_name = parameters["parameters"]["new_attribute_name"]
            new_object[new_obj_attribute_name] = new_object_ref

        return new_object

    @raise_exception(
        "Failed to extract key value mapping.",
        exception_logger=logger,
    )
    def _extract_key_value_mapping(
        self,
        answer: Any,
        param_key: str,
        parameters: dict[str, Any],
    ) -> dict[str, Any]:
        """
        Extract key-value mapping from answer.

        Args:
            answer: The answer data
            param_key: The parameter key
            parameters: The parameters configuration

        Returns:
            Dictionary with extracted key-value mapping
        """
        new_object = {}
        answer_key = DataExtractorUtil.get_value_from_structure_recursive(
            answer, param_key
        )
        _key = parameters["parameters"]["new_attribute_name"]
        attribute_key_to_fetch = parameters["parameters"]["attribute_key_to_fetch"]

        if not answer_key or not attribute_key_to_fetch:
            new_object[_key] = ""
        else:
            _value = answer_key[attribute_key_to_fetch]
            new_object[_key] = _value

        return new_object

    @raise_exception(
        "Failed to extract object id.",
        exception_logger=logger,
    )
    def _extract_object_id(
        self,
        answer: Any,
        param_key: str,
    ) -> dict[str, Any]:
        """
        Extract object ID from answer.

        Args:
            answer: The answer data
            param_key: The parameter key

        Returns:
            Dictionary with extracted object ID
        """
        new_object = {}
        new_object["id"] = answer[param_key]
        return new_object

    # ============================================================================
    # DYNAMIC KEY HANDLING METHODS
    # ============================================================================

    @raise_exception(
        "Failed to process answer with dynamic keys.",
        exception_logger=logger,
    )
    def _process_answer_with_dynamic_keys(
        self,
        answer: Any,
        parameters: list[list[dict[str, Any]]],
        dynamic_keynames: list[str],
        return_object: list[dict[str, Any]],
        obj_id: int,
    ) -> int:
        """Process a single answer with dynamic key handling."""
        for grouping_for_new_object in parameters:
            new_list_groupings = self._process_parameter_grouping(
                grouping_for_new_object, dynamic_keynames
            )

            for grouping in new_list_groupings:
                new_object = self._create_object_from_grouping(answer, grouping, obj_id)
                return_object.append(new_object)
                obj_id += 1

        return obj_id

    # ============================================================================
    # OBJECT CREATION METHODS
    # ============================================================================

    @raise_exception(
        "Failed to create object from grouping.",
        exception_logger=logger,
    )
    def _create_object_from_grouping(
        self,
        answer: Any,
        grouping: list[dict[str, Any]],
        obj_id: int,
    ) -> dict[str, Any]:
        """Create a single object from a parameter grouping."""
        new_object = {"id": obj_id}

        for param in grouping:
            mini_object = self.extract_cell_info(answer, param)
            new_object.update(mini_object)

        return new_object

    @raise_exception(
        "Failed to find dynamic keynames.",
        exception_logger=logger,
    )
    def _find_dynamic_keynames(
        self,
        answer: Any,
        key_pattern: re.Pattern,
    ) -> list[str]:
        """
        Find dynamic key names in the answer.

        Args:
            answer: The answer data to search
            key_pattern: The regex pattern for dynamic keys

        Returns:
            List of dynamic key names
        """
        dynamic_keynames = []
        keynames = set(answer.keys())
        for keyname in keynames:
            if bool(key_pattern.fullmatch(keyname)):
                dynamic_keynames.append(keyname)
        return dynamic_keynames

    @raise_exception(
        "Failed to process parameter grouping.",
        exception_logger=logger,
    )
    def _process_parameter_grouping(
        self,
        grouping_for_new_object: list[dict[str, Any]],
        dynamic_keynames: list[str],
    ) -> list[list[dict[str, Any]]]:
        """
        Process parameter grouping with dynamic key handling.

        Args:
            grouping_for_new_object: The parameter grouping to process
            dynamic_keynames: List of dynamic key names

        Returns:
            List of processed parameter groupings
        """
        dict_new_params = {}
        dict_static_params = {}

        for param in grouping_for_new_object:
            if "DYNAMIC" in param["keyName"]:
                self._process_dynamic_params(param, dynamic_keynames, dict_new_params)
            else:
                dict_static_params[param["keyName"]] = param

        if len(dict_new_params) > 0:
            return self._combine_dynamic_and_static_params(
                dict_new_params, dict_static_params
            )
        else:
            return grouping_for_new_object

    @raise_exception(
        "Failed to process dynamic params.",
        exception_logger=logger,
    )
    def _process_dynamic_params(
        self,
        param: dict[str, Any],
        dynamic_keynames: list[str],
        dict_new_params: dict[str, list[dict[str, Any]]],
    ) -> None:
        """
        Process dynamic parameters by creating copies for each dynamic key.

        Args:
            param: The parameter to process
            dynamic_keynames: List of dynamic key names
            dict_new_params: Dictionary to store new parameters
        """
        for keyname in dynamic_keynames:
            if keyname not in dict_new_params:
                dict_new_params[keyname] = []
            new_param = copy.deepcopy(param)
            new_param["keyName"] = param["keyName"].replace("DYNAMIC", keyname)
            dict_new_params[keyname].append(new_param)

    @raise_exception(
        "Failed to combine dynamic and static params.",
        exception_logger=logger,
    )
    def _combine_dynamic_and_static_params(
        self,
        dict_new_params: dict[str, list[dict[str, Any]]],
        dict_static_params: dict[str, dict[str, Any]],
    ) -> list[list[dict[str, Any]]]:
        """
        Combine dynamic and static parameters.

        Args:
            dict_new_params: Dictionary of new parameters
            dict_static_params: Dictionary of static parameters

        Returns:
            List of combined parameter groupings
        """
        # Remove static key names from dynamic params
        for static_keyname in dict_static_params.keys():
            dict_new_params.pop(static_keyname, None)

        # Add static parameters to each dynamic grouping
        new_list_groupings = dict_new_params.values()
        for group in new_list_groupings:
            group.extend(list(dict_static_params.values()))

        return new_list_groupings
