export enum DialogStateEnum {
    addRegisterScenario = "addRegisterScenario",
    addMasterRegisterScenario = "addMasterRegisterScenario",
    addProjectRegisterScenario = "addProjectRegisterScenario",
    addRegister = "addRegister",
    appVersionInfo = "appVersionInfo",
    assessmentCheckpointHistory = "assessmentCheckpointHistory",
    attackFlowDatabase = "attackFlowDatabase",
    diagramExport = "diagramExport",
    diagramGeneratedJsonImport = "diagramGeneratedJsonImport",
    diagramImport = "diagramImport",
    editMasterRegisterScenario = "editMasterRegisterScenario",
    editProjectRegisterScenario = "editProjectRegisterScenario",
    editRegister = "editRegister",
    exportActualMitigationMeasure = "exportActualMitigationMeasure",
    exportRegister = "exportRegister",
    mitigationLogAct = "mitigationLogAct",
    mitigationLogActGrouped = "mitigationLogActGrouped",
    mitigationLogMaster = "mitigationLogMaster",
    mitigationLogRec = "mitigationLogRec",
    mitigationLogRecGrouped = "mitigationLogRecGrouped",
    mitigationMappingAct = "mitigationMappingAct",
    mitigationMappingActGrouped = "mitigationMappingActGrouped",
    mitigationMappingMaster = "mitigationMappingMaster",
    mitigationMappingRec = "mitigationMappingRec",
    mitigationMappingRecGrouped = "mitigationMappingRecGrouped",
    mitigationMeasure = "mitigationMeasure",
    runAssessment = "runAssessment",
    uploadCactiFile = "uploadCactiFile",
    uploadDiagramFile = "uploadDiagramFile",
    uploadDirectory = "uploadDirectory",
    uploadFiles = "uploadFiles",
    uploadModuleDirectory = "uploadModuleDirectory",
    uploadTerraformFile = "uploadTerraformFile",
    uploadXMLFile = "uploadXMLFile",
    viewAssociatedRisk = "viewAssociatedRisk",
    viewConflictScenarioDetails = "viewConflictScenarioDetails",
    viewConflictResolve = "viewConflictResolve",
    viewFeedback = "viewFeedback",
    viewLLMScenarioReview = "viewLLMScenarioReview",
    viewLLMRiskScenario = "viewLLMRiskScenario",
    viewLog = "viewLog",
    viewDiagramWarnings = "viewDiagramWarnings",
    viewMasterRegisterScenario = "viewMasterRegisterScenario",
}

export enum DialogFieldStateEnum {
    addCanvas = "addCanvas",
    addEdgeDataAttribute = "addEdgeDataAttribute",
    addEdgeDataCactiAttribute = "addEdgeDataCactiAttribute",
    addEdgeMarkerEndAttribute = "addEdgeMarkerEndAttribute",
    addEdgeMarkerStartAttribute = "addEdgeMarkerStartAttribute",
    addEdgeStyleAttribute = "addEdgeStyleAttribute",
    addGroup = "addGroup",
    addMasterMitigation = "addMasterMitigation",
    addMitigationAct = "addMitigationAct",
    addMitigationMaster = "addMitigationMaster",
    addNodeDataAttribute = "addNodeDataAttribute",
    addNodeDataCactiAttribute = "addNodeDataCactiAttribute",
    addNodeStyleAttribute = "addNodeStyleAttribute",
    addProject = "addProject",
    addResourceTag = "addResourceTag",
    addUser = "addUser",
    attackFlow = "attackFlow",
    changeEmail = "changeEmail",
    changeGroupName = "changeGroupName",
    changeProjectGroup = "changeProjectGroup",
    changeProjectName = "changeProjectName",
    disableProject = "disableProject",
    duplicateProject = "duplicateProject",
    editCanvas = "editCanvas",
    editDisplayFrameworksSettings = "editDisplayFrameworksSettings",
    editGenerationSettings = "editGenerationSettings",
    enableProject = "enableProject",
    exportActualMitigationMeasure = "exportActualMitigationMeasure",
    exportMasterScenario = "exportMasterScenario",
    exportProject = "exportProject",
    exportProjectScenario = "exportProjectScenario",
    importCQForm = "importCQForm",
    importProject = "importProject",
    modifyCardField = "modifyCardField",
    modifyJiraSettings = "modifyJiraSettings",
    modifyMasterMitigation = "modifyMasterMitigation",
    modifyMitigation = "modifyMitigation",
    modifyMitigationAct = "modifyMitigationAct",
    modifyMitigationActGrouped = "modifyMitigationActGrouped",
    modifyMitigationMaster = "modifyMitigationMaster",
    modifyMitigationRec = "modifyMitigationRec",
    modifyMitigationRecGrouped = "modifyMitigationRecGrouped",
    modifyProject = "modifyProject",
    modifyProjectAccess = "modifyProjectAccess",
    modifyResourceTag = "modifyResourceTag",
    modifyResourceTagTierLevel = "modifyResourceTagTierLevel",
    modifySuperuser = "modifySuperuser",
    modifyUser = "modifyUser",
    resetPasswordAdmin = "resetPasswordAdmin",
    resetPasswordByToken = "resetPasswordByToken",
    resetPasswordTemp = "resetPasswordTemp",
    resetPasswordUser = "resetPasswordUser",
    selectScenarioTemplate = "selectScenarioTemplate",
    uploadLLMImage = "uploadLLMImage",
    viewLoginHistory = "viewLoginHistory",
    viewMitigationRec = "viewMitigationRec",
    viewMitigationRecGrouped = "viewMitigationRecGrouped",
    viewUserCredits = "viewUserCredits",
}

export enum DialogFieldTypeEnum {
    accordion = "accordion",
    checkboxGroup = "checkboxGroup",
    entitlementTableFields = "entitlementTableFields",
    password = "password",
    reactSelect = "reactSelect",
    reactSelectMulti = "reactSelectMulti",
    select = "select",
    selectObject = "selectObject",
    selectObjectMulti = "selectObjectMulti",
    selectGroup = "selectGroup",
    selectGroupMulti = "selectGroupMulti",
    text = "text",
    textarea = "textarea",
    upload = "uploadFile",
    url = "url",
    //
    displayText = "displayText",
    displayGroupRisks = "displayGroupRisks",
    displayLoginHistory = "displayLoginHistory",
    //
    jiraFields = "jiraFields",
    datePicker = "datePicker",
    toggle = "toggle",
}

export enum DialogConfirmStateEnum {
    // architecture diagram
    confirmClearCanvas = "confirmClearCanvas",
    confirmCloseAttributeDrawerEdge = "confirmCloseAttributeDrawerEdge",
    confirmCloseAttributeDrawerNode = "confirmCloseAttributeDrawerNode",
    confirmDeleteDrawerEdge = "confirmDeleteDrawerEdge",
    confirmDeleteDrawerNode = "confirmDeleteDrawerNode",
    confirmDeleteNodesAndEdges = "confirmDeleteNodesAndEdges",
    confirmDeleteRegister = "confirmDeleteRegister",
    confirmDeleteResourceTags = "confirmDeleteResourceTags",
    confirmRunAssessment = "confirmRunAssessment",
    confirmSetDiagramComplete = "confirmSetDiagramComplete",
    confirmUnsetDiagramComplete = "confirmUnsetDiagramComplete",
    confirmUpdateUserStoryCard = "confirmUpdateUserStoryCard",
    requestToFillRequiredFields = "requestToFillRequiredFields",
    submitArchitectureDiagram = "submitArchitectureDiagram",
    // diagram cacti
    confirmDeleteCactiFile = "confirmDeleteCactiFile",
    confirmDeleteCactiFiles = "confirmDeleteCactiFiles",
    // diagram file
    confirmDeleteDiagramFile = "confirmDeleteDiagramFile",
    confirmDeleteDiagramFiles = "confirmDeleteDiagramFiles",
    // diagram terraform
    confirmDeleteTerraformFile = "confirmDeleteTerraformFile",
    confirmDeleteTerraformFiles = "confirmDeleteTerraformFiles",
    // diagram module
    confirmDeleteModuleFile = "confirmDeleteModuleFile",
    confirmDeleteModuleFiles = "confirmDeleteModuleFiles",
    // diagram XML
    confirmDeleteXMLFile = "confirmDeleteXMLFile",
    confirmDeleteXMLFiles = "confirmDeleteXMLFiles",
    // generate diagram
    confirmGenerateDiagramBlank = "confirmGenerateDiagramBlank",
    confirmGenerateDiagramFromCacti = "confirmGenerateDiagramFromCacti",
    confirmGenerateDiagramFromIAC = "confirmGenerateDiagramFromIAC",
    confirmGenerateDiagramFromJson = "confirmGenerateDiagramFromJson",
    confirmGenerateDiagramFromLLM = "confirmGenerateDiagramFromLLM",
    confirmGenerateDiagramFromLLMWithDescription = "confirmGenerateDiagramFromLLMWithDescription",
    confirmGenerateDiagramFromTemplate = "confirmGenerateDiagramFromTemplate",
    confirmGenerateDiagramFromTopologyGenerator = "confirmGenerateDiagramFromTopologyGenerator",
    confirmGenerateDiagramFromXML = "confirmGenerateDiagramFromXML",
    // llm
    confirmGenerateLLMDiagram = "confirmGenerateLLMDiagram",
    // admin
    confirmDeleteGroup = "confirmDeleteGroup",
    confirmDeleteProject = "confirmDeleteProject",
    confirmDeleteProjects = "confirmDeleteProjects",
    confirmDisableProject = "confirmDisableProject",
    confirmEnableProject = "confirmEnableProject",
    confirmDeleteUser = "confirmDeleteUser",
    confirmDeleteUsers = "confirmDeleteUsers",
    confirmRevokeToken = "confirmRevokeToken",
    confirmRefreshRolePermissions = "confirmRefreshRolePermissions",
    // register
    confirmAddRegisterScenario = "confirmAddRegisterScenario",
    confirmAbortAssessment = "confirmAbortAssessment",
    confirmAcceptAllMitigation = "confirmAcceptAllMitigation",
    confirmCloseAddScenarioDialog = "confirmCloseAddScenarioDialog",
    confirmCloseAddMasterScenario = "confirmCloseAddMasterScenario",
    confirmCloseAddProjectScenario = "confirmCloseAddProjectScenario",
    confirmCloseEditMasterScenario = "confirmCloseEditMasterScenario",
    confirmCloseEditProjectScenario = "confirmCloseEditProjectScenario",
    confirmCloseRegisterDialog = "confirmCloseRegisterDialog",
    confirmDeleteLLMImage = "confirmDeleteLLMImage",
    confirmDeleteMasterScenario = "confirmDeleteMasterScenario",
    confirmDeleteMasterScenarios = "confirmDeleteMasterScenarios",
    confirmDeleteProjectAssessment = "confirmDeleteProjectAssessment",
    confirmFlushIncompleteProjectAssessment = "confirmFlushIncompleteProjectAssessment",
    confirmRemoveFailedProjectAssessment = "confirmRemoveFailedProjectAssessment",
    confirmRestoreProjectAssessment = "confirmRestoreProjectAssessment",
    confirmDeleteProjectScenario = "confirmDeleteProjectScenario",
    confirmDeleteProjectScenarios = "confirmDeleteProjectScenarios",
    confirmDeleteScenario = "confirmDeleteScenario",
    confirmDeleteScenarios = "confirmDeleteScenarios",
    confirmRemoveMitigationAct = "confirmRemoveMitigationAct",
    confirmRemoveMitigationMaster = "confirmRemoveMitigationMaster",
    confirmReset = "confirmReset",
    confirmSubmit = "confirmSubmit",
    // register conflicts
    confirmAcceptAllConflicts = "confirmAcceptAllConflicts",
    confirmIgnoreAllConflicts = "confirmIgnoreAllConflicts",
    // register llm
    confirmAddLLMScenarioToProjectRegister = "confirmAddLLMScenarioToProjectRegister",
    // feedback
    confirmDeleteFeedback = "confirmDeleteFeedback",
    // rec mitigations
    confirmAcceptRecMitigations = "confirmAcceptRecMitigations",
    confirmHideRecMitigations = "confirmHideRecMitigations",
    confirmUnhideRecMitigations = "confirmUnhideRecMitigations",
    // rec mitigations (grouped)
    confirmAcceptGroupedRecMitigations = "confirmAcceptGroupedRecMitigations",
    confirmHideGroupedRecMitigations = "confirmHideGroupedRecMitigations",
    confirmUnhideGroupedRecMitigations = "confirmUnhideGroupedRecMitigations",
    // act mitigations
    confirmDeleteActMitigation = "confirmDeleteActMitigation",
    confirmDeleteActMitigations = "confirmDeleteActMitigations",
    confirmMarkCompleteActMitigations = "confirmMarkCompleteActMitigations",
    confirmMarkIncompleteActMitigations = "confirmMarkIncompleteActMitigations",
}

export enum LogDialogStateEnum {
    mitigationAct = "mitigationAct",
    mitigationActGrouped = "mitigationActGrouped",
    mitigationMeasureAct = "mitigationMeasureAct",
    mitigationMeasureActGrouped = "mitigationMeasureActGrouped",
    //
    mitigationMaster = "mitigationMaster",
    mitigationMasterMeasure = "mitigationMasterMeasure",
    //
    mitigationMeasureRec = "mitigationMeasureRec",
    mitigationMeasureRecGrouped = "mitigationMeasureRecGrouped",
    mitigationRec = "mitigationRec",
    mitigationRecGrouped = "mitigationRecGrouped",
    //
    masterRegister = "masterRegister",
    masterRegisterScenario = "masterRegisterScenario",
    projectRegister = "projectRegister",
    projectRegisterScenario = "projectRegisterScenario",
    //
    projectCQ = "projectCQ",
    projectDiagram = "projectDiagram",
    projectDiagramEdge = "projectDiagramEdge",
    projectDiagramNode = "projectDiagramNode",
}
