import os

ASSESSMENT_JOB_HEARTBEAT_TTL_SECONDS = int(
    os.getenv("ASSESSMENT_JOB_HEARTBEAT_TTL_SECONDS", "300")
)
ASSESSMENT_JOB_HEARTBEAT_REFRESH_SECONDS = int(
    os.getenv("ASSESSMENT_JOB_HEARTBEAT_REFRESH_SECONDS", "10")
)
ASSESSMENT_JOB_RESERVATION_TTL_SECONDS = int(
    os.getenv("ASSESSMENT_JOB_RESERVATION_TTL_SECONDS", "300")
)
ASSESSMENT_JOB_RESERVATION_STALE_SECONDS = int(
    os.getenv("ASSESSMENT_JOB_RESERVATION_STALE_SECONDS", "60")
)
