import os

LLM_GENERATION_JOB_HEARTBEAT_TTL_SECONDS = int(
    os.getenv("LLM_GENERATION_JOB_HEARTBEAT_TTL_SECONDS", "300")
)
LLM_GENERATION_JOB_HEARTBEAT_REFRESH_SECONDS = int(
    os.getenv("LLM_GENERATION_JOB_HEARTBEAT_REFRESH_SECONDS", "10")
)
LLM_GENERATION_JOB_RESERVATION_TTL_SECONDS = int(
    os.getenv("LLM_GENERATION_JOB_RESERVATION_TTL_SECONDS", "300")
)
LLM_GENERATION_JOB_RESERVATION_STALE_SECONDS = int(
    os.getenv("LLM_GENERATION_JOB_RESERVATION_STALE_SECONDS", "60")
)
