# Any resource names with certain prefixes are consolidated into one node

# each element is a dictionary where key is the terraform resource type, and
# resource_name is what to display
AWS_CONSOLIDATED_NODES = [
    {
        "class_label_list": [
            "aws_iam_access_key",
            "aws_iam_account_alias",
            "aws_iam_account_password_policy",
            "aws_iam_instance_profile",
            "aws_iam_openid_connect_provider",
            "aws_iam_policy_attachment",
            "aws_iam_policy",
            "aws_iam_saml_provider",
            "aws_iam_security_token_service_preferences",
            "aws_iam_server_certificate",
            "aws_iam_service_linked_role",
            "aws_iam_service_specific_credential",
            "aws_iam_signing_certificate",
            "aws_iam_virtual_mfa_device",
            "aws_iam_group",
            "aws_iam_group_membership",
            "aws_iam_group_policy",
            "aws_iam_group_policy_attachment",
            "aws_iam_role",
            "aws_iam_role_policy",
            "aws_iam_role_policy_attachment",
            "aws_iam_user",
            "aws_iam_user_group_membership",
            "aws_iam_user_login_profile",
            "aws_iam_user_policy",
            "aws_iam_user_policy_attachment",
            "aws_iam_user_ssh_key",
        ],
        "consolidated_label": "AWS IAM",
        "consolidated_class_label": "aws_iam",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_vpc_endpoint",
            "aws_vpc_endpoint_connection_accepter",
            "aws_vpc_endpoint_connection_notification",
            "aws_vpc_endpoint_policy",
            "aws_vpc_endpoint_route_table_association",
            "aws_vpc_endpoint_security_group_association",
            "aws_vpc_endpoint_service",
            "aws_vpc_endpoint_service_allowed_principal",
            "aws_vpc_endpoint_subnet_association",
        ],
        "consolidated_label": "AWS VPC Endpoint",
        "consolidated_class_label": "aws_vpc_endpoint",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_sns_platform_application",
            "aws_sns_sms_preferences",
            "aws_sns_topic",
            "aws_sns_topic_data_protection_policy",
            "aws_sns_topic_policy",
            "aws_sns_topic_subscription",
        ],
        "consolidated_label": "AWS SNS",
        "consolidated_class_label": "aws_sns",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_default_security_group",
            "aws_security_group_rule",
            "aws_security_group",
            "aws_vpc_security_group_egress_rule",
            "aws_vpc_security_group_ingress_rule",
        ],
        "consolidated_label": "AWS VPC Security Group",
        "consolidated_class_label": "aws_vpc_security_group",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_secretsmanager_secret",
            "aws_secretsmanager_secret_policy",
            "aws_secretsmanager_secret_rotation",
            "aws_secretsmanager_secret_version",
        ],
        "consolidated_label": "AWS Secrets Manager",
        "consolidated_class_label": "aws_secretsmanager",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_cloudwatch_log_data_protection_policy",
            "aws_cloudwatch_log_destination",
            "aws_cloudwatch_log_destination_policy",
            "aws_cloudwatch_log_group",
            "aws_cloudwatch_log_metric_filter",
            "aws_cloudwatch_log_resource_policy",
            "aws_cloudwatch_log_stream",
            "aws_cloudwatch_log_subscription_filter",
            "aws_cloudwatch_query_definition",
        ],
        "consolidated_label": "AWS Cloudwatch Logs",
        "consolidated_class_label": "aws_cloudwatch_log",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_cloudwatch_event_api_destination",
            "aws_cloudwatch_event_archive",
            "aws_cloudwatch_event_bus",
            "aws_cloudwatch_event_bus_policy",
            "aws_cloudwatch_event_connection",
            "aws_cloudwatch_event_endpoint",
            "aws_cloudwatch_event_permission",
            "aws_cloudwatch_event_rule",
            "aws_cloudwatch_event_target",
        ],
        "consolidated_label": "AWS Cloudwatch EventBridge",
        "consolidated_class_label": "aws_cloudwatch_eventbridge",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_scheduler_schedule",
            "aws_scheduler_schedule_group",
        ],
        "consolidated_label": "AWS Cloudwatch EventBridge Scheduler",
        "consolidated_class_label": "aws_cloudwatch_eventbridge_scheduler",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_schemas_discoverer",
            "aws_schemas_registry",
            "aws_schemas_registry_policy",
            "aws_schemas_schema",
        ],
        "consolidated_label": "AWS Cloudwatch EventBridge Schemas",
        "consolidated_class_label": "aws_cloudwatch_eventbridge_schemas",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_cloudwatch_composite_alarm",
            "aws_cloudwatch_dashboard",
            "aws_cloudwatch_metric_alarm",
            "aws_cloudwatch_metric_stream",
        ],
        "consolidated_label": "AWS Cloudwatch",
        "consolidated_class_label": "aws_cloudwatch",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_synthetics_canary",
            "aws_synthetics_group",
            "aws_synthetics_group_association",
        ],
        "consolidated_label": "AWS Cloudwatch Synthetics",
        "consolidated_class_label": "aws_cloudwatch_synthetics",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_rum_app_monitor",
            "aws_rum_metrics_destination",
        ],
        "consolidated_label": "AWS Cloudwatch RUM",
        "consolidated_class_label": "aws_cloudwatch_rum",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_oam_link",
            "aws_oam_sink",
            "aws_oam_sink_policy",
        ],
        "consolidated_label": "AWS Cloudwatch OAM",
        "consolidated_class_label": "aws_cloudwatch_oam",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_evidently_feature",
            "aws_evidently_launch",
            "aws_evidently_project",
            "aws_evidently_segment",
        ],
        "consolidated_label": "AWS Cloudwatch Evidently",
        "consolidated_class_label": "aws_cloudwatch_evidently",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_cloudtrail",
            "aws_cloudtrail_event_data_store",
        ],
        "consolidated_label": "AWS CloudTrail",
        "consolidated_class_label": "aws_cloudtrail",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_networkfirewall_firewall",
            "aws_networkfirewall_firewall_policy",
            "aws_networkfirewall_logging_configuration",
            "aws_networkfirewall_resource_policy",
            "aws_networkfirewall_rule_group",
        ],
        "consolidated_label": "AWS Network Firewall",
        "consolidated_class_label": "aws_networkfirewall",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_s3_bucket",
            "aws_s3_bucket_accelerate_configuration",
            "aws_s3_bucket_acl",
            "aws_s3_bucket_analytics_configuration",
            "aws_s3_bucket_cors_configuration",
            "aws_s3_bucket_intelligent_tiering_configuration",
            "aws_s3_bucket_inventory",
            "aws_s3_bucket_lifecycle_configuration",
            "aws_s3_bucket_logging",
            "aws_s3_bucket_metric",
            "aws_s3_bucket_notification",
            "aws_s3_bucket_object",
            "aws_s3_bucket_object_lock_configuration",
            "aws_s3_bucket_ownership_controls",
            "aws_s3_bucket_policy",
            "aws_s3_bucket_public_access_block",
            "aws_s3_bucket_replication_configuration",
            "aws_s3_bucket_request_payment_configuration",
            "aws_s3_bucket_server_side_encryption_configuration",
            "aws_s3_bucket_versioning",
            "aws_s3_bucket_website_configuration",
            "aws_s3_object",
            "aws_s3_object_copy",
        ],
        "consolidated_label": "AWS S3 Simple Storage",
        "consolidated_class_label": "aws_s3_bucket",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_wafv2_ip_set",
            "aws_wafv2_regex_pattern_set",
            "aws_wafv2_rule_group",
            "aws_wafv2_web_acl",
            "aws_wafv2_web_acl_association",
            "aws_wafv2_web_acl_logging_configuration",
        ],
        "consolidated_label": "AWS WAF",
        "consolidated_class_label": "aws_wafv2",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_default_route_table",
            "aws_route_table_association",
            "aws_route_table",
            "aws_route",
        ],
        "consolidated_label": "AWS VPC Route",
        "consolidated_class_label": "aws_vpc_route",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_default_subnet",
            "aws_subnet",
        ],
        "consolidated_label": "AWS VPC Subnet",
        "consolidated_class_label": "aws_vpc_subnet",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_default_vpc_dhcp_options",
            "aws_default_vpc",
            "aws_flow_log",
            "aws_main_route_table_association",
            "aws_vpc_dhcp_options_association",
            "aws_vpc_dhcp_options",
            "aws_vpc_ipv4_cidr_block_association",
            "aws_vpc_ipv6_cidr_block_association",
            "aws_vpc_network_performance_metric_subscription",
            "aws_vpc_peering_connection_accepter",
            "aws_vpc_peering_connection_options",
            "aws_vpc_peering_connection",
            "aws_vpc",
        ],
        "consolidated_label": "AWS VPC",
        "consolidated_class_label": "aws_vpc",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_nat_gateway",
        ],
        "consolidated_label": "AWS VPC NAT Gateway",
        "consolidated_class_label": "aws_vpc_nat_gateway",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_internet_gateway",
            "aws_internet_gateway_attachment",
            "aws_egress_only_internet_gateway",
        ],
        "consolidated_label": "AWS VPC Internet Gateway",
        "consolidated_class_label": "aws_vpc_internet_gateway",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_default_network_acl",
            "aws_network_acl_association",
            "aws_network_acl_rule",
            "aws_network_acl",
        ],
        "consolidated_label": "AWS VPC Network ACL",
        "consolidated_class_label": "aws_vpc_network_acl",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_network_interface",
            "aws_network_interface_attachment",
            "aws_network_interface_sg_attachment",
        ],
        "consolidated_label": "AWS VPC Network Interface",
        "consolidated_class_label": "aws_vpc_network_interface",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_ec2_managed_prefix_list",
            "aws_ec2_managed_prefix_list_entry",
            "aws_ec2_network_insights_analysis",
            "aws_ec2_network_insights_path",
            "aws_ec2_subnet_cidr_reservation",
            "aws_ec2_traffic_mirror_filter",
            "aws_ec2_traffic_mirror_filter_rule",
            "aws_ec2_traffic_mirror_session",
            "aws_ec2_traffic_mirror_target",
        ],
        "consolidated_label": "AWS VPC EC2",
        "consolidated_class_label": "aws_vpc_ec2",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_ami_copy",
            "aws_ami_from_instance",
            "aws_ami_launch_permission",
            "aws_ami",
            "aws_ec2_availability_zone_group",
            "aws_ec2_capacity_reservation",
            "aws_ec2_fleet",
            "aws_ec2_host",
            "aws_ec2_instance_connect_endpoint",
            "aws_ec2_instance_state",
            "aws_ec2_serial_console_access",
            "aws_ec2_tag",
            "aws_eip_association",
            "aws_eip",
            "aws_instance",
            "aws_key_pair",
            "aws_launch_template",
            "aws_placement_group",
            "aws_spot_datafeed_subscription",
            "aws_spot_fleet_request",
            "aws_spot_instance_request",
        ],
        "consolidated_label": "AWS EC2 Resources",
        "consolidated_class_label": "aws_ec2",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_backup_framework",
            "aws_backup_global_settings",
            "aws_backup_plan",
            "aws_backup_region_settings",
            "aws_backup_report_plan",
            "aws_backup_selection",
            "aws_backup_vault_lock_configuration",
            "aws_backup_vault_notifications",
            "aws_backup_vault_policy",
            "aws_backup_vault",
        ],
        "consolidated_label": "AWS Backup",
        "consolidated_class_label": "aws_backup",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_elastic_beanstalk_application",
            "aws_elastic_beanstalk_application_version",
            "aws_elastic_beanstalk_configuration_template",
            "aws_elastic_beanstalk_environment",
        ],
        "consolidated_label": "AWS Elastic Beanstalk",
        "consolidated_class_label": "aws_elastic_beanstalk",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_route53_resolver_config",
            "aws_route53_resolver_dnssec_config",
            "aws_route53_resolver_endpoint",
            "aws_route53_resolver_query_log_config",
            "aws_route53_resolver_query_log_config_association",
            "aws_route53_resolver_rule",
            "aws_route53_resolver_rule_association",
            "aws_route53_resolver_firewall_config",
            "aws_route53_resolver_firewall_domain_list",
            "aws_route53_resolver_firewall_rule",
            "aws_route53_resolver_firewall_rule_group",
            "aws_route53_resolver_firewall_rule_group_association",
        ],
        "consolidated_label": "AWS Route 53 Resolver",
        "consolidated_class_label": "aws_route53_resolver",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_db_cluster_snapshot",
            "aws_db_event_subscription",
            "aws_db_instance",
            "aws_db_instance_automated_backups_replication",
            "aws_db_instance_role_association",
            "aws_db_option_group",
            "aws_db_parameter_group",
            "aws_db_proxy",
            "aws_db_proxy_default_target_group",
            "aws_db_proxy_endpoint",
            "aws_db_proxy_target",
            "aws_db_snapshot",
            "aws_db_snapshot_copy",
            "aws_db_subnet_group",
        ],
        "consolidated_label": "AWS RDS DB",
        "consolidated_class_label": "aws_rds_db",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_kms_alias",
            "aws_kms_ciphertext",
            "aws_kms_custom_key_store",
            "aws_kms_external_key",
            "aws_kms_grant",
            "aws_kms_key",
            "aws_kms_key_policy",
            "aws_kms_replica_external_key",
            "aws_kms_replica_key",
        ],
        "consolidated_label": "AWS KMS",
        "consolidated_class_label": "aws_kms",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_lambda_alias",
            "aws_lambda_code_signing_config",
            "aws_lambda_event_source_mapping",
            "aws_lambda_function",
            "aws_lambda_function_event_invoke_config",
            "aws_lambda_function_url",
            "aws_lambda_invocation",
            "aws_lambda_layer_version",
            "aws_lambda_layer_version_permission",
            "aws_lambda_permission",
            "aws_lambda_provisioned_concurrency_config",
        ],
        "consolidated_label": "AWS Lambda",
        "consolidated_class_label": "aws_lambda",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_ebs_default_kms_key",
            "aws_ebs_encryption_by_default",
            "aws_ebs_snapshot",
            "aws_ebs_snapshot_copy",
            "aws_ebs_snapshot_import",
            "aws_ebs_volume",
            "aws_snapshot_create_volume_permission",
            "aws_volume_attachment",
        ],
        "consolidated_label": "AWS EBS (EC2)",
        "consolidated_class_label": "aws_ebs",
        "source": "custom",
    },
    {
        "class_label_list": [
            "aws_ecr_lifecycle_policy",
            "aws_ecr_pull_through_cache_rule",
            "aws_ecr_registry_policy",
            "aws_ecr_registry_scanning_configuration",
            "aws_ecr_replication_configuration",
            "aws_ecr_repository",
            "aws_ecr_repository_policy",
        ],
        "consolidated_label": "AWS ECR",
        "consolidated_class_label": "aws_ecr",
        "source": "custom",
    },
    # {
    #     "class_label_list": [
    #         "aws_acm_certificate",
    #         "aws_acm_certificate_validation",
    #     ],
    #     "consolidated_label": "AWS ACM Resources",
    #     "consolidated_class_label": "aws_acm_resources",
    #     "source": "custom",
    # },
    # {
    #     "class_label_list": [
    #         "aws_ecs_account_setting_default",
    #         "aws_ecs_capacity_provider",
    #         "aws_ecs_cluster",
    #         "aws_ecs_cluster_capacity_providers",
    #         "aws_ecs_service",
    #         "aws_ecs_tag",
    #         "aws_ecs_task_definition",
    #         "aws_ecs_task_set",
    #     ],
    #     "consolidated_label": "AWS ECS Resources",
    #     "consolidated_class_label": "aws_ecs_resources",
    #     "source": "custom",
    # },
    # {
    #     "class_label_list": [
    #         "aws_ssm_activation",
    #         "aws_ssm_association",
    #         "aws_ssm_default_patch_baseline",
    #         "aws_ssm_document",
    #         "aws_ssm_maintenance_window",
    #         "aws_ssm_maintenance_window_target",
    #         "aws_ssm_maintenance_window_task",
    #         "aws_ssm_parameter",
    #         "aws_ssm_patch_baseline",
    #         "aws_ssm_patch_group",
    #         "aws_ssm_resource_data_sync",
    #         "aws_ssm_service_setting",
    #     ],
    #     "consolidated_label": "AWS SSM Resources",
    #     "consolidated_class_label": "aws_ssm_resources",
    #     "source": "custom",
    # },
    # {
    #     "class_label_list": [
    #         "aws_efs_access_point",
    #         "aws_efs_backup_policy",
    #         "aws_efs_file_system",
    #         "aws_efs_file_system_policy",
    #         "aws_efs_mount_target",
    #         "aws_efs_replication_configuration",
    #     ],
    #     "consolidated_label": "AWS EFS Resources",
    #     "consolidated_class_label": "aws_efs_resources",
    #     "source": "custom",
    # },
    # {
    #     "class_label_list": [
    #         "aws_s3_access_point",
    #         "aws_s3_account_public_access_block",
    #         "aws_s3control_access_point_policy",
    #         "aws_s3control_bucket",
    #         "aws_s3control_bucket_lifecycle_configuration",
    #         "aws_s3control_bucket_policy",
    #         "aws_s3control_multi_region_access_point",
    #         "aws_s3control_multi_region_access_point_policy",
    #         "aws_s3control_object_lambda_access_point",
    #         "aws_s3control_object_lambda_access_point_policy",
    #         "aws_s3control_storage_lens_configuration",
    #     ],
    #     "consolidated_label": "AWS S3 Control Resources",
    #     "consolidated_class_label": "aws_s3_control_resources",
    #     "source": "custom",
    # },
    # {
    #     "class_label_list": [
    #         "aws_s3outposts_endpoint",
    #     ],
    #     "consolidated_label": "AWS S3 Outposts",
    #     "consolidated_class_label": "aws_s3_outposts",
    #     "source": "custom",
    # },
    # {
    #     "class_label_list": [
    #         "aws_glacier_vault",
    #         "aws_glacier_vault_lock",
    #     ],
    #     "consolidated_label": "AWS S3 Glacier Resources",
    #     "consolidated_class_label": "aws_s3_glacier_resources",
    #     "source": "custom",
    # },
    # {
    #     "class_label_list": [
    #         "aws_rds_cluster",
    #         "aws_rds_cluster_activity_stream",
    #         "aws_rds_cluster_endpoint",
    #         "aws_rds_cluster_instance",
    #         "aws_rds_cluster_parameter_group",
    #         "aws_rds_cluster_role_association",
    #         "aws_rds_custom_db_engine_version",
    #         "aws_rds_export_task",
    #         "aws_rds_global_cluster",
    #         "aws_rds_reserved_instance",
    #     ],
    #     "consolidated_label": "AWS RDS RDS Resources",
    #     "consolidated_class_label": "aws_rds_rds_resources",
    #     "source": "custom",
    # },
    # {
    #     "class_label_list": [
    #         "aws_route53_cidr_collection",
    #         "aws_route53_cidr_location",
    #         "aws_route53_delegation_set",
    #         "aws_route53_health_check",
    #         "aws_route53_hosted_zone_dnssec",
    #         "aws_route53_key_signing_key",
    #         "aws_route53_query_log",
    #         "aws_route53_record",
    #         "aws_route53_traffic_policy",
    #         "aws_route53_traffic_policy_instance",
    #         "aws_route53_vpc_association_authorization",
    #         "aws_route53_zone",
    #         "aws_route53_zone_association",
    #     ],
    #     "consolidated_label": "AWS Route53 Resources",
    #     "consolidated_class_label": "aws_route53_resources",
    #     "source": "custom",
    # },
    # {
    #     "class_label_list": [
    #         "aws_route53domains_registered_domain",
    #     ],
    #     "consolidated_label": "AWS Route53 Domains",
    #     "consolidated_class_label": "aws_route53_domains",
    #     "source": "custom",
    # },
    # {
    #     "class_label_list": [
    #         "aws_route53recoverycontrolconfig_cluster",
    #         "aws_route53recoverycontrolconfig_control_panel",
    #         "aws_route53recoverycontrolconfig_routing_control",
    #         "aws_route53recoverycontrolconfig_safety_rule",
    #     ],
    #     "consolidated_label": "AWS Route53 Recovery Control Resources",
    #     "consolidated_class_label": "aws_route53recoverycontrolconfig_resources",
    #     "source": "custom",
    # },
    # {
    #     "class_label_list": [
    #         "aws_route53recoveryreadiness_cell",
    #         "aws_route53recoveryreadiness_readiness_check",
    #         "aws_route53recoveryreadiness_recovery_group",
    #         "aws_route53recoveryreadiness_resource_set",
    #     ],
    #     "consolidated_label": "AWS Route 53 Recovery Readiness Resources",
    #     "consolidated_class_label": "aws_route53recoveryreadiness_resources",
    #     "source": "custom",
    # },
    # {
    #     "class_label_list": [
    #         "aws_guardduty_detector",
    #         "aws_guardduty_detector_feature",
    #         "aws_guardduty_filter",
    #         "aws_guardduty_invite_accepter",
    #         "aws_guardduty_ipset",
    #         "aws_guardduty_member",
    #         "aws_guardduty_organization_admin_account",
    #         "aws_guardduty_organization_configuration",
    #         "aws_guardduty_publishing_destination",
    #         "aws_guardduty_threatintelset",
    #     ],
    #     "consolidated_label": "AWS GuardDuty Resources",
    #     "consolidated_class_label": "aws_guardduty_resources",
    #     "source": "custom",
    # },
    # {
    #     "class_label_list": [
    #         "aws_config_aggregate_authorization",
    #         "aws_config_config_rule",
    #         "aws_config_configuration_aggregator",
    #         "aws_config_configuration_recorder",
    #         "aws_config_configuration_recorder_status",
    #         "aws_config_conformance_pack",
    #         "aws_config_delivery_channel",
    #         "aws_config_organization_conformance_pack",
    #         "aws_config_organization_custom_policy_rule",
    #         "aws_config_organization_custom_rule",
    #         "aws_config_organization_managed_rule",
    #         "aws_config_remediation_configuration",
    #     ],
    #     "consolidated_label": "AWS Config Resources",
    #     "consolidated_class_label": "aws_config_resources",
    #     "source": "custom",
    # },
    # {
    #     "class_label_list": [
    #         "aws_inspector2_delegated_admin_account",
    #         "aws_inspector2_enabler",
    #         "aws_inspector2_member_association",
    #         "aws_inspector2_organization_configuration",
    #     ],
    #     "consolidated_label": "AWS Inspector Resources",
    #     "consolidated_class_label": "aws_inspector_resources",
    #     "source": "custom",
    # },
]


# List of Group type nodes and order to draw them in
AWS_GROUP_NODES = []

# Nodes to be drawn first inside the AWS Cloud but outside any subnets or VPCs
AWS_EDGE_NODES = [
    {"class_label_prefix": "aws_api_gateway"},
    {"class_label_prefix": "aws_apigateway"},
    {"class_label_prefix": "aws_cloudfront_distribution"},
    {"class_label_prefix": "aws_internet_gateway"},
    {"class_label_prefix": "aws_route53"},
]

# Nodes outside Cloud boundary
AWS_OUTER_NODES = [
    {"class_label_prefix": "tv_aws_users"},
    {"class_label_prefix": "tv_aws_internet"},
]

AWS_SHARED_SERVICES = [
    # {"class_label_prefix": "aws_acm_certificate"},
    # {"class_label_prefix": "aws_cloudwatch_log_group"},
    # {"class_label_prefix": "aws_ecr_repository"},
    # {"class_label_prefix": "aws_efs_file_system"},
    # {"class_label_prefix": "aws_eip"},
    # {"class_label_prefix": "aws_kms_key"},
    # {"class_label_prefix": "aws_ssm_parameter"},
]

# Order to draw nodes - leave empty string list till last to denote everything else
AWS_DRAW_ORDER = [
    AWS_OUTER_NODES,
    AWS_EDGE_NODES,
    AWS_GROUP_NODES,
    AWS_CONSOLIDATED_NODES,
    [""],
]

# List of prefixes where additional nodes should be created automatically
AWS_AUTO_ANNOTATIONS = [
    # {
    #     "class_label_prefix": "aws_dx",
    #     "related_nodes": [
    #         {
    #             "label": "tv_aws_onprem.corporate_datacenter",
    #             "class_label": "tv_aws_onprem.corporate_datacenter",
    #         },
    #         {
    #             "label": "tv_aws_cgw.customer_gateway",
    #             "class_label": "tv_aws_cgw.customer_gateway",
    #         },
    #     ],
    #     "direction": "forward",
    # },
    # {
    #     "class_label_prefix": "aws_internet_gateway",
    #     "related_nodes": [
    #         {
    #             "label": "tv_aws_internet.internet",
    #             "class_label": "tv_aws_internet.internet",
    #         },
    #     ],
    #     "direction": "reverse",
    # },
    # {
    #     "class_label_prefix": "aws_nat_gateway",
    #     "related_nodes": [
    #         {
    #             "label": "aws_internet_gateway.*",
    #             "class_label": "aws_internet_gateway.*",
    #         },
    #     ],
    #     "direction": "forward",
    # },
    # {
    #     "class_label_prefix": "aws_ecs_service",
    #     "related_nodes": [
    #         {
    #             "label": "aws_ecr_repository.ecr",
    #             "class_label": "aws_ecr_repository.ecr",
    #         },
    #     ],
    #     "direction": "forward",
    # },
    # {
    #     "class_label_prefix": "aws_ecs_",
    #     "related_nodes": [
    #         {
    #             "label": "aws_ecs_cluster.ecs",
    #             "class_label": "aws_ecs_cluster.ecs",
    #         },
    #     ],
    #     "direction": "forward",
    # },
    # {
    #     "class_label_prefix": "aws_lambda",
    #     "related_nodes": [
    #         {
    #             "label": "aws_cloudwatch_log_group.cloudwatch",
    #             "class_label": "aws_cloudwatch_log_group.cloudwatch",
    #         },
    #     ],
    #     "direction": "forward",
    # },
]

AWS_AUTO_LINKS = [
    {
        "class_label_prefix": "aws_ec2_transit_gateway_vpc_attachment",
        "related_class_label_prefixes": [
            "aws_ec2_transit_gateway.ecs",
        ],
        "direction": "none",
    },
]

# Variant icons for the same service - matches keyword in meta data and changes resource type
AWS_NODE_VARIANTS = {
    "aws_ecs_service": {"FARGATE": "aws_fargate", "EC2": "aws_ec2ecs"},
    "aws_lb": {"application": "aws_alb", "network": "aws_nlb"},
    "aws_rds": {
        "aurora": "aws_rds_aurora",
        "mysql": "aws_rds_mysql",
        "postgres": "aws_rds_postgres",
    },
}

# Automatically reverse arrow direction for these resources
AWS_REVERSE_ARROW_LIST = [
    # "aws_vpc.",
    # "aws_route53",
    # "aws_cloudfront",
    # "aws_subnet",
    # "aws_iam_role",
    # "aws_lb",
]

AWS_IMPLIED_CONNECTIONS = [
    {
        "class_label_prefix": "certificate_arn",
        "implied_label": "aws_acm_certificate",
        "implied_class_label": "aws_acm_certificate",
    },
    {
        "class_label_prefix": "container_definitions",
        "implied_label": "aws_ecr_repository",
        "implied_class_label": "aws_ecr_repository",
    },
]

# List of special resources and handler function name
AWS_SPECIAL_RESOURCES = [
    {
        "class_label_prefix": "aws_cloudfront_distribution",
        "handler": "aws_handle_cloudfront_pregraph",
    },
    {
        "class_label_prefix": "aws_subnet",
        "handler": "aws_handle_subnet_azs",
    },
    {
        "class_label_prefix": "aws_appautoscaling_target",
        "handler": "aws_handle_autoscaling",
    },
    {
        "class_label_prefix": "aws_efs_file_system",
        "handler": "aws_handle_efs",
    },
    {
        "class_label_prefix": "aws_db_subnet",
        "handler": "aws_handle_dbsubnet",
    },
    {
        "class_label_prefix": "aws_security_group",
        "handler": "aws_handle_sg",
    },
    {
        "class_label_prefix": "aws_lb",
        "handler": "aws_handle_lb",
    },
    {
        "class_label_prefix": "aws_",
        "handler": "aws_handle_sharedgroup",
    },
]

_INCLUDE = [
    # "data",
    "aws",
    "aws_vpc",
    "aws_az",
    "aws_group",
    "aws_appautoscaling_target",
    "aws_subnet",
    # "aws_security_group",
    "tv_aws_onprem",
    "aws_api_gateway_rest_api",
    "aws_apigatewayv2_api",
    "aws_cloudfront_distribution",
    "aws_route53_record",
    "aws_internet_gateway",
    # "aws_nat_gateway",
    "aws_ecs_service",
    # "aws_lambda_function",
    "aws_lb",
    "aws_elb",
    "aws_alb",
    # "aws_elastic_beanstalk_application",
    # "aws_s3_bucket",
    # "aws_vpc_endpoint",
    "aws_instance",
    "aws_ec2_transit_gateway",
    "aws_ec2_transit_gateway_vpc_attachment",
    # "aws_cloudwatch_log_group",
    # "aws_cloudtrail",
    "aws_networkfirewall_firewall",
    "aws_route53_resolver_firewall_domain_list",
    # "aws_wafv2_web_acl",
    "aws_secretsmanager_secret",
    # "aws_backup_plan",
    "aws_network_acl",
    # "aws_iam_role",
    "aws_db_instance",
    "aws_route_table",
]


EXCLUDE = [
    "var",
    "root",
    "output",
    "data",
    "local",
    "aws_iam",
    "aws_route_table",
    "aws_network_acl",
    "aws_alb_target_group",
    "aws_key_pair",
    "aws_autoscaling",
    "aws_launch_configuration",
    "aws_db_instance",
    "aws_db_parameter_group",
    "aws_db_subnet_group",
    "aws_security_group",
    "aws_ec2_transit_gateway_route_table",
    "aws_cloudfront_origin_access_identity",
    "aws_route53_resolver_rule_association",
    "aws_route53_zone",
    "aws_eip",
    "aws_api_gateway_deployment",
    "aws_api_gateway_resource",
    "aws_api_gateway_stage",
    "aws_ec2_transit_gateway_vpc_attachment_accepter",
    "aws_acm_certificate_validation",
]
