export const dashboardLayoutTokens = {
    pagePaddingX: 4,
    pagePaddingY: 3,
    sectionHeaderMarginBottom: 1.25,
    pageSectionSpacing: 3,
    sectionSpacing: 1.25,
    sectionGridColumnSpacing: 2,
    sectionGridRowSpacing: 1.5,
    cardPaddingX: 3.5,
    cardPaddingY: 3.5,
    compactCardPaddingY: 3,
    contentStackSpacing: 1.5,
    contentRowGap: 0.75,
    insetTilePaddingX: 1.5,
    insetTilePaddingY: 1.25,
} as const;
