export const terraform_mapping: { [key: string]: string } = {
    //AWSAnalyticsNodeIconDisplayKey
    Athena: "aws_athena_database",
    CleanRooms: "aws_cleanrooms_configured_table",
    CloudSearch: "aws_cloudsearch_domain",
    DataExchange: "aws_dataexchange_data_set",
    DataPipeline: "aws_datapipeline_pipeline",
    EMR: "aws_datapipeline_pipeline",
    FinSpace: "aws_finspace_kx_cluster",
    Glue: "aws_glue_catalog_database",
    GlueDataBrew: "aws_glue_catalog_database",
    GlueElasticViews: "aws_glue_catalog_database",
    Kinesis: "aws_kinesis_stream",
    KinesisDataAnalytics: "aws_kinesis_analytics_application",
    KinesisDataStreams: "aws_kinesis_stream",
    KinesisFirehose: "aws_kinesis_firehose_delivery_stream",
    LakeFormation: "aws_lakeformation_resource",
    ManagedStreamingForApacheKafka: "aws_msk_cluster",
    OpenSearchService: "aws_opensearch_domain",
    QuickSight: "aws_quicksight_group",
    Redshift: "aws_redshift_cluster",
    DataZone: "",
    KinesisVideoStreams: "",
    //AWSApplicationIntegrationNodeIconDisplayKey
    APIGateway: "aws_apigatewayv2_api",
    AppFlow: "aws_appflow_flow",
    AppSync: "aws_appsync_graphql_api",
    EventBridge: "aws_cloudwatch_event_connection",
    ManagedWorkflowsForApacheAirflow: "aws_mwaa_environment",
    MQ: "aws_mq_broker",
    SimpleNotificationService: "aws_sns_topic",
    SimpleQueueService: "aws_sqs_queue",
    StepFunctions: "aws_sfn_activity",
    ConsoleMobileApplication: "",
    ExpressWorkflows: "",
    //AWSBusinessApplicationsNodeIconDisplayKey
    AlexaForBusiness: "",
    Chime: "aws_chime_voice_connector",
    ChimeSDK: "aws_chimesdkvoice_global_settings",
    ChimeVoiceConnector: "aws_chime_voice_connector",
    Connect: "aws_connect_instance",
    Pinpoint: "aws_pinpoint_app",
    PinpointAPIs: "aws_pinpoint_app",
    SimpleEmailService: "aws_ses_email_identity",
    Honeycode: "",
    SupplyChain: "",
    Wickr: "",
    WorkDocs: "",
    WorkDocsSDK: "",
    WorkMail: "",
    //AWSCloudFinancialManagementNodeIconDisplayKey
    ApplicationCostProfiler: "",
    BillingConductor: "awscc_billingconductor_billing_group ",
    Budgets: "awscc_budgets_budgets_action ",
    CostAndUsageReport: "",
    CostExplorer: "",
    ReservedInstanceReporting: "",
    SavingsPlans: "",
    //AWSComputeNodeIconDisplayKey
    AppRunner: "aws_apprunner_service",
    ApplicationAutoScaling: "aws_appautoscaling_target",
    Batch: "aws_batch_compute_environment",
    EC2: "aws_instance",
    EC2AutoScaling: "aws_autoscaling_group",
    EC2ImageBuilder: "aws_imagebuilder_component",
    ElasticBeanstalk: "aws_elastic_beanstalk_application",
    ElasticFabricAdapter: "aws_network_interface",
    Fargate: "aws_ecs_task_definition",
    Lambda: "aws_lambda_function",
    Lightsail: "aws_lightsail_bucket",
    OutpostsFamily: "aws_outposts_outpost",
    OutpostsRack: "aws_outposts_outpost",
    OutpostsServers: "aws_outposts_outpost",
    ServerlessApplicationRepository: "aws_serverlessapplicationrepository_cloudformation_stack",
    Bottlerocket: "",
    ComputeOptimizer: "",
    GenomicsCLI: "",
    NICEDCV: "",
    NICEEnginFrame: "",
    NitroEnclaves: "",
    ParallelCluster: "",
    SimSpaceWeaver: "",
    ThinkboxDeadline: "",
    ThinkboxFrost: "",
    ThinkboxKrakatoa: "",
    ThinkboxSequoia: "",
    ThinkboxStoke: "",
    ThinkboxXMesh: "",
    VMwareCloudOnAWS: "",
    Wavelength: "",
    //AWSContainersNodeIconDisplayKey
    ECSAnywhere: "aws_eks_cluster",
    EKSCloud: "aws_eks_cluster",
    EKSDistro: "aws_eks_cluster",
    ElasticContainerRegistry: "aws_ecrpublic_repository",
    ElasticContainerService: "aws_ecs_service",
    ElasticKubernetesService: "aws_eks_cluster",
    RedHatOpenShiftService: "",
    //AWSCustomerEnablementNodeIconDisplayKey
    Activate: "",
    IQ: "",
    ManagedServices: "",
    ProfessionalServices: "",
    rePost: "",
    Support: "",
    TrainingCertification: "",
    //AWSDatabaseNodeIconDisplayKey
    DatabaseMigrationService: "aws_dms_endpoint",
    DocumentDB: "aws_docdb_cluster",
    DynamoDB: "aws_dynamodb_table",
    ElastiCache: "aws_elasticache_cluster",
    Keyspaces: "",
    MemoryDBForRedis: "",
    Neptune: "",
    RDS: "aws_db_instance",
    RDSOnVMware: "",
    Timestream: "aws_keyspaces_keyspace",
    Aurora: "",
    //AWSDeveloperToolsNodeIconDisplayKey
    CloudControlAPI: "aws_cloudcontrolapi_resource",
    Cloud9: "aws_cloud9_environment_ec2",
    CodeArtifact: "aws_codeartifact_domain",
    CodeBuild: "aws_codebuild_project",
    CodeCatalyst: "aws_codecatalyst_project",
    CodeCommit: "aws_codecommit_repository",
    CodeDeploy: "aws_codedeploy_app",
    CodePipeline: "aws_codepipeline",
    CodeStar: "aws_codestarconnections_connection",
    XRay: "aws_xray_group",
    ApplicationComposer: "",
    CloudDevelopmentKit: "",
    CommandLineInterface: "",
    Corretto: "",
    ToolsAndSDKs: "",
    //AWSEndUserComputingNodeIconDisplayKey
    AppStream: "aws_appstream_directory_config",
    WorkLink: "aws_worklink_fleet",
    WorkSpacesFamily: "aws_workspaces_workspace",
    //AWSFrontEndWebMobileNodeIconDisplayKey
    Amplify: "aws_amplify_app",
    DeviceFarm: "aws_devicefarm_project",
    LocationService: "aws_location_map",
    //AWSGamesNodeIconDisplayKey
    GameLift: "aws_gamelift_fleet",
    GameKit: "",
    GameSparks: "",
    Lumberyard: "",
    Open3DEngine: "",
    //AWSInternetOfThingsNodeIconDisplayKey
    IoTCore: "aws_iot_domain_configuration",
    IoTEvents: "awscc_iotevents_alarm_model",
    IoTFleetWise: "awscc_iotfleetwise_fleet ",
    IoTSiteWise: "awscc_iotsitewise_gateway ",
    FreeRTOS: "",
    IoT1Click: "",
    IoTAnalytics: "",
    IoTButton: "",
    IoTDeviceDefender: "",
    IoTDeviceManagement: "",
    IoTEduKit: "",
    IoTExpressLink: "",
    IoTGreengrass: "",
    IoTRoboRunner: "",
    IoTThingsGraph: "",
    IoTTwinMaker: "",
    //AWSMachineLearningNodeIconDisplayKey
    CodeGuru: "awscc_codeguruprofiler_profiling_group ",
    Comprehend: "awscc_comprehend_document_classifier ",
    DevOpsGuru: "awscc_devopsguru_notification_channel ",
    FraudDetector: "awscc_frauddetector_detector ",
    HealthLake: "awscc_healthlake_fhir_datastore ",
    Kendra: "aws_kendra_data_source",
    Lex: "aws_lex_bot",
    LookoutForEquipment: "awscc_lookoutequipment_inference_scheduler ",
    LookoutForMetrics: "awscc_lookoutmetrics_alert",
    LookoutForVision: "awscc_lookoutvision_project ",
    Omics: "awscc_omics_workflow",
    Personalize: "awscc_personalize_schema",
    Rekognition: "awscc_rekognition_project",
    SageMaker: "aws_sagemaker_model",
    Transcribe: "aws_transcribe_vocabulary",
    ApacheMXNetOnAWS: "",
    AugmentedAIA2I: "",
    CodeWhisperer: "",
    ComprehendMedical: "",
    DeepLearningAMIs: "",
    DeepLearningContainers: "",
    DeepComposer: "",
    DeepLens: "",
    DeepRacer: "",
    ElasticInference: "",
    Forecast: "",
    Monitron: "",
    Neuron: "",
    Panorama: "",
    Polly: "",
    SageMakerGroundTruth: "",
    SageMakerStudioLab: "",
    TensorFlowOnAWS: "",
    Textract: "",
    TorchServe: "",
    Translate: "",
    //AWSManagementGovernanceNodeIconDisplayKey
    AppConfig: "aws_appconfig_application",
    AutoScaling: "aws_autoscaling_group",
    CloudFormation: "aws_cloudformation_stack",
    CloudTrail: "aws_cloudtrail",
    CloudWatch: "aws_cloudwatch_log_group",
    Config: "aws_config_aggregate_authorization",
    ControlTower: "aws_controltower_control",
    FaultInjectionSimulator: "aws_fis_experiment_template",
    LicenseManager: "aws_licensemanager_license_configuration",
    ManagedGrafana: "aws_grafana_workspace",
    ManagedServiceForPrometheus: "aws_prometheus_workspace",
    OpsWorks: "aws_opsworks_application",
    Organizations: "aws_organizations_organization",
    Proton: "awscc_proton_service_template ",
    ServiceCatalog: "aws_servicecatalog_product",
    SystemsManager: "aws_ssm_document",
    BackintAgent: "",
    Chatbot: "",
    DistroForOpenTelemetry: "",
    LaunchWizard: "",
    ManagementConsole: "",
    PersonalHealthDashboard: "",
    ResilienceHub: "",
    ResourceExplorer: "",
    ServiceManagementConnector: "",
    TrustedAdvisor: "",
    WellArchitectedTool: "",
    //AWSMediaServicesNodeIconDisplayKey
    ElasticTranscoder: "aws_elastictranscoder_pipeline",
    ElementalMediaConnect: "aws_media_package_channel",
    ElementalMediaLive: "aws_medialive_channel",
    ElementalMediaPackage: "aws_media_package_channel",
    ElementalMediaStore: "aws_media_store_container",
    InteractiveVideoService: "aws_ivs_channel",
    NimbleStudio: "awscc_nimblestudio_studio_component ",
    ElementalAppliancesAndSoftware: "",
    ElementalConductor: "",
    ElementalDelta: "",
    ElementalLink: "",
    ElementalLive: "",
    ElementalMediaConvert: "",
    ElementalMediaTailor: "",
    ElementalServer: "",
    //AWSMigrationTransferNodeIconDisplayKey
    ApplicationDiscoveryService: "aws_service_discovery_service",
    DataSync: "aws_datasync_agent",
    TransferFamily: "aws_transfer_server",
    ApplicationMigrationService: "",
    MainframeModernization: "",
    MigrationEvaluator: "",
    MigrationHub: "",
    ServerMigrationService: "",
    // AWSNetworkingContentDeliveryNodeIconDisplayKey
    AppMesh: "aws_appmesh_mesh",
    ClientVPN: "aws_ec2_client_vpn_endpoint",
    CloudFront: "aws_cloudfront_distribution",
    DirectConnect: "aws_dx_connection",
    ElasticLoadBalancing: "aws_lb",
    GlobalAccelerator: "aws_globalaccelerator_accelerator",
    Route53: "aws_route53_record",
    SiteToSite: "aws_vpn_connection",
    TransitGateway: "aws_ec2_transit_gateway",
    VerifiedAccess: "aws_verifiedaccess_instance",
    VirtualPrivateCloud: "aws_vpc",
    VPCLattice: "aws_vpclattice_service",
    CloudDirectory: "",
    CloudMap: "",
    CloudWAN: "",
    Private5G: "",
    PrivateLink: "",
    //AWSSecurityIdentityComplianceNodeIconDisplayKey
    AuditManager: "aws_auditmanager_framework",
    CertificateManager: "aws_acm_certificate",
    CloudHSM: "aws_cloudhsm_v2_hsm",
    Cognito: "aws_cognito_identity_pool",
    Detective: "aws_detective_graph",
    DirectoryService: "aws_directory_service_directory",
    FirewallManager: "aws_fms_admin_accountFirewall Manager",
    GuardDuty: "aws_guardduty_detector",
    IdentityAndAccessManagement: "aws_iam_role",
    Inspector: "aws_inspector_assessment_template",
    KeyManagementService: "aws_kms_key",
    Macie: "aws_macie2_account",
    NetworkFirewall: "aws_networkfirewall_firewall",
    PrivateCertificateAuthority: "aws_acmpca_certificate_authority",
    ResourceAccessManager: "aws_ram_principal_association",
    SecretsManager: "aws_secretsmanager_secret",
    SecurityHub: "aws_securityhub_account",
    Shield: "aws_shield_protection",
    Signer: "aws_signer_signing_profile",
    WAF: "aws_wafv2_web_acl",
    Backup: "aws_backup_plan",
    EFS: "aws_efs_file_system",
    ElasticBlockStore: "aws_ebs_volume",
    FSx: "aws_fsx_backup",
    FSxForLustre: "aws_fsx_lustre_file_system",
    FSxForNetAppONTAP: "aws_fsx_ontap_file_system",
    FSxForOpenZFS: "aws_fsx_openzfs_snapshot",
    FSxForWFS: "aws_fsx_windows_file_system",
    S3OnOutposts: "aws_s3outposts_endpoints",
    SimpleStorageService: "aws_s3_bucket",
    SimpleStorageServiceGlacier: "aws_glacier_vault",
    StorageGateway: "aws_storagegateway_gateway",
    GroundStation: "awscc_groundstation_mission_profile ",
    QuantumLedgerDatabase: "aws_qldb_ledger",
    RoboMaker: "awscc_robomaker_robot ",
    SingleSignOn: "aws_ssoadmin_managed_policy_attachment",

    //AWSResourceAnalyticsNodeIconDisplayKey
    EMRCluster: "aws_emr_cluster",
    GlueDataQuality: "aws_glue_data_quality_ruleset",
    LakeFormationDataLake: "aws_lakeformation_resource",
    MSKConnect: "aws_mskconnect_connector",
    RedshiftAuto: "aws_redshift_cluster",
    RedshiftDataSharingGovernance: "aws_redshift_cluster",
    RedshiftDenseComputeNode: "aws_redshift_cluster",
    RedshiftDenseStorageNode: "aws_redshift_cluster",
    RedshiftML: "aws_redshift_cluster",
    RedshiftQueryEditor: "aws_redshift_cluster",
    EMREngine: "",
    EMRHDFSCluster: "",
    //AWSResourceAppIntegrationNodeIconDisplayKey
    ApiGatewayEndpoint: "aws_api_gateway_rest_api",
    EventBridgeCustomEventBus: "aws_cloudwatch_event_bus",
    EventBridgeDefaultEventBus: "aws_cloudwatch_event_bus",
    EventBridgePipes: "aws_pipes_pipe",
    EventBridgeRule: "aws_cloudwatch_event_rule",
    EventBridgeScheduler: "aws_scheduler_schedule",
    EventBridgeSchema: "aws_schemas_schema",
    EventBridgeSchemaRegistry: "aws_schemas_registry",
    EventBridgeEvent: "",
    EventBridgeSaasPartnerEvent: "",
    //AWSResourceDatabaseNodeIconDisplayKey
    AuroraPostgreSQL: "aws_rds_cluster",
    AuroraPostgreSQLAlt: "aws_rds_cluster",
    AuroraSQLServer: "aws_rds_cluster",
    AuroraSQLServerAlt: "aws_rds_cluster",
    //AWSResourceManagementGovernanceNodeIconDisplayKey
    CloudWatchAlarm: "aws_cloudwatch_metric_alarm",
    CloudWatchEvidently: "aws_evidently_project",
    CloudWatchLogs: "aws_cloudwatch_log_group",
    CloudWatchMetricsInsights: "aws_cloudwatch_metric_alarm",
    CloudWatchRule: "aws_cloudwatch_event_rule",
    CloudWatchRUM: "aws_rum_app_monitor",
    CloudWatchSynthetics: "aws_synthetics_canary",
    CloudWatchCrossAccountObservability: "",
    CloudWatchDataProtection: "",
    CloudWatchEventEventBased: "",
    CloudWatchEventTimeBased: "",
    //AWSResourceNetworkingContentDeliveryNodeIconDisplayKey
    ELBApplicationLoadBalancer: "aws_alb",
    ELBClassicLoadBalancer: "aws_elb",
    ELBGatewayLoadBalancer: "aws_lb",
    ELBNetworkLoadBalancer: "aws_lb",
    Route53RouteTable: "aws_route53_record",
    VPCCustomerGateway: "aws_customer_gateway",
    VPCElasticNetworkAdapter: "VPC Elastic Network Adapter",
    VPCElasticNetworkInterface: "aws_network_interface",
    VPCEndpoints: "aws_vpc_endpoint",
    VPCFlowLogs: "aws_flow_log",
    VPCInternetGateway: "aws_internet_gateway",
    VPCNATGateway: "aws_nat_gateway",
    VPCNetworkAccessControlList: "aws_network_acl",
    VPCPeeringConnection: "aws_vpc_peering_connection",
    VPCReachabilityAnalyzer: "aws_ec2_network_insights_analysis",
    VPCRouter: "aws_route_table",
    VPCVirtualPrivateCloud: "aws_vpc",
    VPCVPNConnection: "aws_vpn_connection",
    VPCVPNGateway: "aws_vpn_gateway",
    VPCTrafficMirroring: "",
    VPCCarrierGateway: "",
    VPCNetworkAccessAnalyzer: "",

    //AWSResourceSecurityIdentityComplianceNodeIconDisplayKey {
    IAMAccessAnalyzer: "aws_accessanalyzer_analyzer",
    IAMAddOn: "",
    IAMEncryptedData: "",
    IAMPermissions: "",
    //AWSResourceStorageNodeIconDisplayKey {
    ElasticBlockStoreVolume: "aws_ebs_volume",
    SimpleStorageServiceBucket: "aws_s3_bucket",
    SimpleStorageServiceBucketWithObjects: "aws_s3_bucket",
    ElasticBlockStoreMultipleVolumes: "",
    ElasticFileSystemEFSStandard: "",
    FileCacheOnPremisesNFSLinkedDatasets: "",
    SimpleStorageServiceS3Standard: "",
};
