from enum import Enum


class AWSNodeIconDisplayKey(Enum):
    # AWSAnalyticsNodeIconDisplayKey
    athena = "Athena"
    cleanRooms = "CleanRooms"
    cloudSearch = "CloudSearch"
    dataExchange = "Data Exchange"
    dataPipeline = "Data Pipeline"
    dataZone = "DataZone"
    emr = "EMR"
    finSpace = "FinSpace"
    glue = "Glue"
    glueDataBrew = "Glue DataBrew"
    glueElasticViews = "Glue ElasticViews"
    kinesis = "Kinesis"
    kinesisDataAnalytics = "Kinesis Data Analytics"
    kinesisDataStreams = "Kinesis Data Streams"
    kinesisFirehose = "Kinesis Firehose"
    kinesisVideoStreams = "Kinesis Video Streams"
    lakeFormation = "Lake Formation"
    managedStreamingForApacheKafka = "Managed Streaming for Apache Kafka"
    openSearchService = "OpenSearch Service"
    quickSight = "QuickSight"
    redshift = "Redshift"

    # AWSApplicationIntegrationNodeIconDisplayKey
    apiGateway = "API Gateway"
    appFlow = "AppFlow"
    appSync = "AppSync"
    consoleMobileApplication = "Console Mobile Application"
    eventBridge = "EventBridge"
    expressWorkflows = "Express Workflows"
    managedWorkflowsForApacheAirflow = "Managed Workflows for Apache Airflow"
    mq = "MQ"
    simpleNotificationService = "Simple Notification Service"
    simpleQueueService = "Simple Queue Service"
    stepFunctions = "Step Functions"

    # AWSBusinessApplicationsNodeIconDisplayKey
    alexaForBusiness = "Alexa For Business"
    chime = "Chime"
    chimeSDK = "Chime SDK"
    chimeVoiceConnector = "Chime Voice Connector"
    connect = "Connect"
    honeycode = "Honeycode"
    pinpoint = "Pinpoint"
    pinpointAPIs = "Pinpoint APIs"
    simpleEmailService = "Simple Email Service"
    supplyChain = "Supply Chain"
    wickr = "Wickr"
    workDocs = "WorkDocs"
    workDocsSDK = "WorkDocs SDK"
    workMail = "WorkMail"

    # AWSCloudFinancialManagementNodeIconDisplayKey
    applicationCostProfiler = "Application Cost Profiler"
    billingConductor = "Billing Conductor"
    budgets = "Budgets"
    costAndUsageReport = "Cost and Usage Report"
    costExplorer = "Cost Explorer"
    reservedInstanceReporting = "Reserved Instance Reporting"
    savingsPlans = "Savings Plans"

    # AWSComputeNodeIconDisplayKey
    appRunner = "App Runner"
    applicationAutoScaling = "Application Auto Scaling"
    batch = "Batch"
    bottlerocket = "Bottlerocket"
    computeOptimizer = "Compute Optimizer"
    ec2 = "EC2"
    ec2AutoScaling = "EC2 Auto Scaling"
    ec2ImageBuilder = "EC2 Image Builder"
    elasticBeanstalk = "Elastic Beanstalk"
    elasticFabricAdapter = "Elastic Fabric Adapter"
    fargate = "Fargate"
    Lambda = "lambda"  # Different from others due to python keyword
    lightsail = "Lightsail"
    localZones = "Local Zones"
    niceDCV = "Nice DCV"
    niceEnginFrame = "Nice EnginFrame"
    nitroEnclaves = "Nitro Enclaves"
    outpostsFamily = "Outposts Family"
    outpostsRack = "Outposts Rack"
    outpostsServers = "Outposts Servers"
    parallelCluster = "Parallel Cluster"
    serverlessApplicationRepository = "Serverless Application Repository"
    simSpaceWeaver = "Sim Space Weaver"
    thinkboxDeadline = "Thinkbox Deadline"
    thinkboxFrost = "Thinkbox Frost"
    thinkboxKrakatoa = "Thinkbox Krakatoa"
    thinkboxSequoia = "Thinkbox Sequoia"
    thinkboxStoke = "Thinkbox Stoke"
    thinkboxXMesh = "Thinkbox XMesh"
    vmwareCloudOnAWS = "VMware Cloud on AWS"
    wavelength = "Wavelength"

    # AWSContainersNodeIconDisplayKey
    ecsAnywhere = "ECS Anywhere"
    eksAnywhere = "EKS Anywhere"
    eksDistro = "EKS Distro"
    elasticContainerRegistry = "Elastic Container Registry"
    elasticContainerService = "Elastic Container Service"
    kubernetesPod = "Kubernetes Pod"
    redHatOpenShiftService = "Red Hat OpenShift Service"

    # AWSCustomerEnablementNodeIconDisplayKey
    activate = "Activate"
    iq = "IQ"
    professionalServices = "Professional Services"
    rePost = "RePost"
    rePostPrivate = "RePost Private"
    support = "Support"
    trainingCertification = "Training Certification"

    # AWSDatabaseNodeIconDisplayKey
    aurora = "Aurora"
    databaseMigrationService = "Database Migration Service"
    documentDB = "DocumentDB"
    dynamoDB = "DynamoDB"
    elastiCache = "ElastiCache"
    keyspaces = "Keyspaces"
    memoryDBForRedis = "MemoryDB for Redis"
    neptune = "Neptune"
    rds = "RDS"
    rdsInstance = "RDS Instance"
    rdsOnVMware = "RDS on VMware"
    timestream = "Timestream"

    # AWSDeveloperToolsNodeIconDisplayKey
    applicationComposer = "Application Composer"
    cloud9 = "Cloud9"
    cloudControlAPI = "Cloud Control API"
    cloudDevelopmentKit = "Cloud Development Kit"
    cloudShell = "CloudShell"
    codeArtifact = "CodeArtifact"
    codeBuild = "CodeBuild"
    codeCatalyst = "CodeCatalyst"
    codeCommit = "CodeCommit"
    codeDeploy = "CodeDeploy"
    codePipeline = "CodePipeline"
    commandLineInterface = "Command Line Interface"
    corretto = "Corretto"
    toolsAndSDKs = "Tools and SDKs"
    xRay = "X-Ray"

    # AWSEndUserComputingNodeIconDisplayKey
    appStream = "AppStream"
    workSpacesFamily = "WorkSpaces Family"

    # AWSFrontEndWebMobileNodeIconDisplayKey
    amplify = "Amplify"
    deviceFarm = "Device Farm"
    locationService = "Location Service"

    # AWSGamesNodeIconDisplayKey
    gameKit = "GameKit"
    gameLift = "GameLift"
    gameSparks = "GameSparks"
    lumberyard = "Lumberyard"
    open3DEngine = "Open 3D Engine"

    # AWSInternetOfThingsNodeIconDisplayKey
    freeRTOS = "FreeRTOS"
    iot1Click = "IoT 1-Click"
    iotAnalytics = "IoT Analytics"
    iotButton = "IoT Button"
    iotCore = "IoT Core"
    iotDeviceDefender = "IoT Device Defender"
    iotDeviceManagement = "IoT Device Management"
    iotEduKit = "IoT EduKit"
    iotEvents = "IoT Events"
    iotExpressLink = "IoT Express Link"
    iotFleetWise = "IoT FleetWise"
    iotGreengrass = "IoT Greengrass"
    iotRoboRunner = "IoT RoboRunner"
    iotSiteWise = "IoT SiteWise"
    iotThingsGraph = "IoT Things Graph"
    iotTwinMaker = "IoT TwinMaker"

    # AWSMachineLearningNodeIconDisplayKey
    apacheMXNetOnAWS = "Apache MXNet on AWS"
    augmentedAIA2I = "Augmented AIA2I"
    codeGuru = "CodeGuru"
    codeWhisperer = "Code Whisperer"
    comprehend = "Comprehend"
    comprehendMedical = "Comprehend Medical"
    deepComposer = "DeepComposer"
    deepLearningAMIs = "Deep Learning AMIs"
    deepLearningContainers = "Deep Learning Containers"
    deepRacer = "DeepRacer"
    devOpsGuru = "DevOps Guru"
    elasticInference = "Elastic Inference"
    forecast = "Forecast"
    fraudDetector = "Fraud Detector"
    healthLake = "HealthLake"
    kendra = "Kendra"
    lex = "Lex"
    lookoutForEquipment = "Lookout for Equipment"
    lookoutForMetrics = "Lookout for Metrics"
    lookoutForVision = "Lookout for Vision"
    monitron = "Monitron"
    neuron = "Neuron"
    omics = "Omics"
    panorama = "Panorama"
    personalize = "Personalize"
    polly = "Polly"
    rekognition = "Rekognition"
    sageMaker = "SageMaker"
    sageMakerGroundTruth = "SageMaker Ground Truth"
    sageMakerStudioLab = "SageMaker Studio Lab"
    tensorFlowOnAWS = "TensorFlow on AWS"
    textract = "Textract"
    torchServe = "TorchServe"
    transcribeAWS = "Transcribe AWS"
    translate = "Translate"

    # AWSManagementGovernanceNodeIconDisplayKey
    appConfig = "AppConfig"
    autoScaling = "Auto Scaling"
    backintAgent = "Backint Agent"
    chatbot = "Chatbot"
    cloudFormation = "CloudFormation"
    cloudTrail = "CloudTrail"
    cloudWatch = "CloudWatch"
    config = "Config"
    controlTower = "Control Tower"
    distroForOpenTelemetry = "Distro for OpenTelemetry"
    faultInjectionSimulator = "Fault Injection Simulator"
    launchWizard = "Launch Wizard"
    licenseManager = "License Manager"
    managedGrafana = "Managed Grafana"
    managedServiceForPrometheus = "Managed Service for Prometheus"
    managementConsole = "Management Console"
    opsWorks = "OpsWorks"
    organizations = "Organizations"
    personalHealthDashboard = "Personal Health Dashboard"
    proton = "Proton"
    resilienceHub = "Resilience Hub"
    resourceExplorer = "Resource Explorer"
    serviceCatalog = "Service Catalog"
    serviceManagementConnector = "Service Management Connector"
    systemsManager = "Systems Manager"
    trustedAdvisor = "Trusted Advisor"
    wellArchitectedTool = "Well-Architected Tool"

    # AWSMediaServicesNodeIconDisplayKey
    elasticTranscoder = "Elastic Transcoder"
    elementalAppliancesAndSoftware = "Elemental Appliances and Software"
    elementalConductor = "Elemental Conductor"
    elementalDelta = "Elemental Delta"
    elementalLink = "Elemental Link"
    elementalLive = "Elemental Live"
    elementalMediaConnect = "Elemental MediaConnect"
    elementalMediaConvert = "Elemental MediaConvert"
    elementalMediaLive = "Elemental MediaLive"
    elementalMediaPackage = "Elemental MediaPackage"
    elementalMediaStore = "Elemental MediaStore"
    elementalMediaTailor = "Elemental MediaTailor"
    elementalServer = "Elemental Server"
    interactiveVideoService = "Interactive Video Service"
    nimbleStudio = "Nimble Studio"

    # AWSMigrationTransferNodeIconDisplayKey
    applicationDiscoveryService = "Application Discovery Service"
    applicationMigrationService = "Application Migration Service"
    dataSync = "DataSync"
    mainframeModernization = "Mainframe Modernization"
    migrationEvaluator = "Migration Evaluator"
    migrationHub = "Migration Hub"
    serverMigrationService = "Server Migration Service"
    transferFamily = "Transfer Family"

    # AWSNetworkingContentDeliveryNodeIconDisplayKey
    appMesh = "AppMesh"
    clientVPN = "Client VPN"
    cloudDirectory = "Cloud Directory"
    cloudFront = "CloudFront"
    cloudMap = "CloudMap"
    cloudWAN = "CloudWAN"
    directConnect = "Direct Connect"
    elasticLoadBalancing = "Elastic Load Balancing"
    globalAccelerator = "Global Accelerator"
    private5G = "Private 5G"
    privateLink = "Private Link"
    route53 = "Route 53"
    siteToSite = "Site-to-Site"
    transitGateway = "Transit Gateway"
    verifiedAccess = "Verified Access"
    vpc = "VPC"
    vpcLattice = "VPC Lattice"

    # AWSResourceNetworkingContentDeliveryNodeIconDisplayKey
    elbApplicationLoadBalancer = "ELB Application Load Balancer"
    elbClassicLoadBalancer = "ELB Classic Load Balancer"
    elbGatewayLoadBalancer = "ELB Gateway Load Balancer"
    elbNetworkLoadBalancer = "ELB Network Load Balancer"
    route53RouteTable = "Route 53 Route Table"
    vpcAlt = "VPC Alt"
    vpcCarrierGateway = "VPC Carrier Gateway"
    vpcCustomerGateway = "VPC Customer Gateway"
    vpcElasticNetworkAdapter = "VPC Elastic Network Adapter"
    vpcElasticNetworkInterface = "VPC Elastic Network Interface"
    vpcEndpoints = "VPC Endpoints"
    vpcFlowLogs = "VPC Flow Logs"
    vpcInternetGateway = "VPC Internet Gateway"
    vpcNATGateway = "VPC NAT Gateway"
    vpcNetworkAccessAnalyzer = "VPC Network Access Analyzer"
    vpcNetworkAccessControlList = "VPC Network Access Control List"
    vpcPeeringConnection = "VPC Peering Connection"
    vpcReachabilityAnalyzer = "VPC Reachability Analyzer"
    vpcRouter = "VPC Router"
    vpcTrafficMirroring = "VPC Traffic Mirroring"
    vpcVPNGateway = "VPC VPN Gateway"

    # AWSSecurityIdentityComplianceNodeIconDisplayKey
    auditManager = "Audit Manager"
    certificateManager = "Certificate Manager"
    cloudHSM = "CloudHSM"
    cognito = "Cognito"
    detective = "Detective"
    directoryService = "Directory Service"
    firewallManager = "Firewall Manager"
    guardDuty = "GuardDuty"
    iamIdentityCenter = "IAM Identity Center"
    identityAndAccessManagement = "Identity and Access Management"
    inspector = "Inspector"
    keyManagementService = "Key Management Service"
    macie = "Macie"
    networkFirewall = "Network Firewall"
    privateCertificateAuthority = "Private Certificate Authority"
    resourceAccessManager = "Resource Access Manager"
    secretsManager = "Secrets Manager"
    securityHub = "Security Hub"
    securityLake = "Security Lake"
    shield = "Shield"
    signer = "Signer"
    verifiedPermissions = "Verified Permissions"
    waf = "WAF"

    # AWSStorageNodeIconDisplayKey
    backup = "Backup"
    ebs = "EBS"
    efs = "EFS"
    elasticDisasterRecovery = "Elastic Disaster Recovery"
    fileCache = "File Cache"
    fsx = "FSx"
    fsxForLustre = "FSx for Lustre"
    fsxForNetAppONTAP = "FSx for NetApp ONTAP"
    fsxForOpenZFS = "FSx for OpenZFS"
    fsxForWFS = "FSx for WFS"
    s3 = "S3"
    s3Glacier = "S3 Glacier"
    snowball = "Snowball"
    snowballEdge = "Snowball Edge"
    snowcone = "Snowcone"
    snowmobile = "Snowmobile"
    storageGateway = "Storage Gateway"

    # AWSOthersNodeIconDisplayKey
    braket = "Braket"
    groundStation = "Ground Station"
    managedBlockchain = "Managed Blockchain"
    marketplace = "Marketplace"
    quantumLedgerDatabase = "Quantum Ledger Database"
    roboMaker = "RoboMaker"
    singleSignOn = "Single Sign-On"

    # Not in used
    # AWSResourceAnalyticsNodeIconDisplayKey
    EMRCluster = "EMRCluster"
    EMREngine = "EMREngine"
    EMRHDFSCluster = "EMRHDFSCluster"
    GlueDataQuality = "GlueDataQuality"
    LakeFormationDataLake = "LakeFormationDataLake"
    MSKConnect = "MSKConnect"
    RedshiftAuto = "RedshiftAuto"
    RedshiftDataSharingGovernance = "RedshiftDataSharingGovernance"
    RedshiftDenseComputeNode = "RedshiftDenseComputeNode"
    RedshiftDenseStorageNode = "RedshiftDenseStorageNode"
    RedshiftML = "RedshiftML"
    RedshiftQueryEditor = "RedshiftQueryEditor"

    # AWSResourceAppIntegrationNodeIconDisplayKey
    ApiGatewayEndpoint = "ApiGatewayEndpoint"
    EventBridgeCustomEventBus = "EventBridgeCustomEventBus"
    EventBridgeDefaultEventBus = "EventBridgeDefaultEventBus"
    EventBridgeEvent = "EventBridgeEvent"
    EventBridgePipes = "EventBridgePipes"
    EventBridgeRule = "EventBridgeRule"
    EventBridgeSaasPartnerEvent = "EventBridgeSaasPartnerEvent"
    EventBridgeScheduler = "EventBridgeScheduler"
    EventBridgeSchema = "EventBridgeSchema"
    EventBridgeSchemaRegistry = "EventBridgeSchemaRegistry"

    # AWSResourceDatabaseNodeIconDisplayKey
    AuroraPostgreSQL = "AuroraPostgreSQL"
    AuroraPostgreSQLAlt = "AuroraPostgreSQLAlt"
    AuroraSQLServer = "AuroraSQLServer"
    AuroraSQLServerAlt = "AuroraSQLServerAlt"

    # AWSResourceManagementGovernanceNodeIconDisplayKey
    CloudWatchAlarm = "CloudWatchAlarm"
    CloudWatchCrossAccountObservability = "CloudWatchCrossAccountObservability"
    CloudWatchDataProtection = "CloudWatchDataProtection"
    CloudWatchEventEventBased = "CloudWatchEventEventBased"
    CloudWatchEventTimeBased = "CloudWatchEventTimeBased"
    CloudWatchEvidently = "CloudWatchEvidently"
    CloudWatchLogs = "CloudWatchLogs"

    # AWSResourceSecurityIdentityComplianceNodeIconDisplayKey
    IAMAddOn = "IAMAddOn"
    IAMAccessAnalyzer = "IAMAccessAnalyzer"
    IAMEncryptedData = "IAMEncryptedData"
    IAMPermissions = "IAMPermissions"

    # AWSResourceStorageNodeIconDisplayKey
    ElasticBlockStoreMultipleVolumes = "ElasticBlockStoreMultipleVolumes"
    ElasticBlockStoreVolume = "ElasticBlockStoreVolume"
    ElasticFileSystemEFSStandard = "ElasticFileSystemEFSStandard"
    FileCacheOnPremisesNFSLinkedDatasets = "FileCacheOnPremisesNFSLinkedDatasets"
    SimpleStorageServiceBucket = "SimpleStorageServiceBucket"
    SimpleStorageServiceBucketWithObjects = "SimpleStorageServiceBucketWithObjects"
    SimpleStorageServiceS3Standard = "SimpleStorageServiceS3Standard"


class GenericNodeIconDisplayKey(Enum):
    # AWSResourceGeneralNodeIconDisplayKey
    firewall = "Firewall"
    forums = "Forums"
    genericApplication = "Generic Application"
    genericDatabase = "Generic Database"
    genericManagementConsole = "Generic Management Console"
    genericServer = "Generic Server"
    genericServers = "Generic Servers"
    genericShield = "Generic Shield"
    internet = "Internet"
    router = "Router"
    switch = "Switch"
    credentials = "Credentials"
    dataStream = "Data Stream"
    dataTable = "Data Table"
    document = "Document"
    documents = "Documents"
    email = "Email"
    folder = "Folder"
    folders = "Folders"
    gitRepository = "Git Repository"
    logs = "Logs"
    sdk = "SDK"
    sourceCode = "Source Code"
    sslPadlock = "SSL Padlock"
    user = "User"
    userAuthenticated = "User Authenticated"
    users = "Users"
    camera = "Camera"
    client = "Client"
    disk = "Disk"
    gear = "Gear"
    multimedia = "Multimedia"
    officeBuilding = "Office Building"
    tapeStorage = "Tape Storage"
    toolkit = "Toolkit"
    baseStation = "Base Station"
    genericActuator = "Generic Actuator"
    genericPLC = "Generic PLC"
    genericSensor = "Generic Sensor"
    historianDatabase = "Historian Database"
    iotGateway = "IoT Gateway"

    # Not in used
    Alert = "Alert"
    Chat = "Chat"
    ColdStorage = "ColdStorage"
    Credentials = "Credentials"
    DataStream = "DataStream"
    DataTable = "DataTable"
    Document = "Document"
    Documents = "Documents"
    Email = "Email"
    Folder = "Folder"
    Folders = "Folders"
    GitRepository = "GitRepository"
    Globe = "Globe"
    JsonScript = "JsonScript"
    Logs = "Logs"
    MagnifyingGlass = "MagnifyingGlass"
    Metrics = "Metrics"
    MobileClient = "MobileClient"
    ProgrammingLanguage = "ProgrammingLanguage"
    Question = "Question"
    Recover = "Recover"
    SAMLToken = "SAMLToken"
    SDK = "SDK"
    SourceCode = "SourceCode"
    SSLPadlock = "SSLPadlock"
    User = "User"
    UserAuthenticated = "UserAuthenticated"
    Users = "Users"


class AWSClusterNodeIconDisplayKey(Enum):
    autoScalingGroup = "autoScalingGroup"
    awsAccount = "awsAccount"
    awsCloud = "awsCloud"
    awsStepFunctionsWorkflow = "awsStepFunctionsWorkflow"
    awsSubnet = "awsSubnet"
    codePipelineCluster = "codePipelineCluster"
    dataPipelineCluster = "dataPipelineCluster"
    elasticBeanstalkContainer = "elasticBeanstalkContainer"
    privateSubnet = "privateSubnet"
    publicSubnet = "publicSubnet"
    region = "region"
    spotFleet = "spotFleet"
    kubernetesCluster = "kubernetesCluster"
    vpcCluster = "vpcCluster"


class GenericClusterNodeIconDisplayKey(Enum):
    cicd = "cicd"
    genericCloud = "genericCloud"
    genericCodePipeline = "genericCodePipeline"
    genericDataPipeline = "genericDataPipeline"
    genericServerCluster = "genericServerCluster"
    genericSubnet = "genericSubnet"
    genericVPC = "genericVPC"
    genericWirelessSubnet = "genericWirelessSubnet"
    onPremisesCompute = "onPremisesCompute"
    onPremisesEnvironment = "onPremisesEnvironment"
