from shared_libs.types.node import (
    AWSClusterNodeIconDisplayKey,
    AWSNodeIconDisplayKey,
    GenericClusterNodeIconDisplayKey,
    GenericNodeIconDisplayKey,
)

MXGRAPH_TO_AWS_ICON_MAPPING = {
    # AWSAnalyticsNodeIconKey
    "mxgraph.aws4.athena": AWSNodeIconDisplayKey.athena.name,
    "mxgraph.aws4.clean_rooms": AWSNodeIconDisplayKey.cleanRooms.name,
    "mxgraph.aws4.cloudsearch2": AWSNodeIconDisplayKey.cloudSearch.name,
    "mxgraph.aws4.data_exchange": AWSNodeIconDisplayKey.dataExchange.name,
    "mxgraph.aws4.data_pipeline": AWSNodeIconDisplayKey.dataPipeline.name,
    "mxgraph.aws4.datazone": AWSNodeIconDisplayKey.dataZone.name,
    "mxgraph.aws4.emr": AWSNodeIconDisplayKey.emr.name,
    "mxgraph.aws4.finspace": AWSNodeIconDisplayKey.finSpace.name,
    "mxgraph.aws4.glue": AWSNodeIconDisplayKey.glue.name,
    "mxgraph.aws4.glue_databrew": AWSNodeIconDisplayKey.glueDataBrew.name,
    "mxgraph.aws4.glue_elastic_views": AWSNodeIconDisplayKey.glueElasticViews.name,
    "mxgraph.aws4.kinesis": AWSNodeIconDisplayKey.kinesis.name,
    "mxgraph.aws4.kinesis_data_analytics": AWSNodeIconDisplayKey.kinesisDataAnalytics.name,
    "mxgraph.aws4.kinesis_data_streams": AWSNodeIconDisplayKey.kinesisDataStreams.name,
    "mxgraph.aws4.kinesis_data_firehose": AWSNodeIconDisplayKey.kinesisFirehose.name,
    "mxgraph.aws4.kinesis_video_streams": AWSNodeIconDisplayKey.kinesisVideoStreams.name,
    "mxgraph.aws4.lake_formation": AWSNodeIconDisplayKey.lakeFormation.name,
    "mxgraph.aws4.managed_streaming_for_kafka": AWSNodeIconDisplayKey.managedStreamingForApacheKafka.name,
    "mxgraph.aws4.elasticsearch_service": AWSNodeIconDisplayKey.openSearchService.name,
    "mxgraph.aws4.quicksight": AWSNodeIconDisplayKey.quickSight.name,
    "mxgraph.aws4.redshift": AWSNodeIconDisplayKey.redshift.name,
    # AWSAppIntegrationNodeIconKey
    "mxgraph.aws4.api_gateway": AWSNodeIconDisplayKey.apiGateway.name,
    "mxgraph.aws4.appflow": AWSNodeIconDisplayKey.appFlow.name,
    "mxgraph.aws4.appsync": AWSNodeIconDisplayKey.appSync.name,
    "mxgraph.aws4.mobile_application": AWSNodeIconDisplayKey.consoleMobileApplication.name,
    "mxgraph.aws4.eventbridge": AWSNodeIconDisplayKey.eventBridge.name,
    "mxgraph.aws4.express_workflow": AWSNodeIconDisplayKey.expressWorkflows.name,
    "mxgraph.aws4.managed_workflows_for_apache_airflow": AWSNodeIconDisplayKey.managedWorkflowsForApacheAirflow.name,
    "mxgraph.aws4.mq": AWSNodeIconDisplayKey.mq.name,
    "mxgraph.aws4.sns": AWSNodeIconDisplayKey.simpleNotificationService.name,
    "mxgraph.aws4.sqs": AWSNodeIconDisplayKey.simpleQueueService.name,
    "mxgraph.aws4.step_functions": AWSNodeIconDisplayKey.stepFunctions.name,
    # AWSBusinessApplicationsNodeIconKey
    "mxgraph.aws4.alexa_for_business": AWSNodeIconDisplayKey.alexaForBusiness.name,
    "mxgraph.aws4.chime": AWSNodeIconDisplayKey.chime.name,
    "mxgraph.aws4.chime_sdk": AWSNodeIconDisplayKey.chimeSDK.name,
    # "mxgraph.aws4.chime": AWSNodeIconDisplayKey.chimeVoiceConnector.name,
    "mxgraph.aws4.connect": AWSNodeIconDisplayKey.connect.name,
    "mxgraph.aws4.honeycode": AWSNodeIconDisplayKey.honeycode.name,
    "mxgraph.aws4.pinpoint": AWSNodeIconDisplayKey.pinpoint.name,
    # "mxgraph.aws4.pinpointapis": AWSNodeIconDisplayKey.pinpointAPIs.name,
    "mxgraph.aws4.simple_email_service": AWSNodeIconDisplayKey.simpleEmailService.name,
    "mxgraph.aws4.supply_chain": AWSNodeIconDisplayKey.supplyChain.name,
    "mxgraph.aws4.wickr": AWSNodeIconDisplayKey.wickr.name,
    "mxgraph.aws4.workdocs": AWSNodeIconDisplayKey.workDocs.name,
    # "mxgraph.aws4.workdocssdk": AWSNodeIconDisplayKey.workDocsSDK.name,
    "mxgraph.aws4.workmail": AWSNodeIconDisplayKey.workMail.name,
    # AWSCloudFinancialManagementNodeIconKey
    "mxgraph.aws4.application_cost_profiler": AWSNodeIconDisplayKey.applicationCostProfiler.name,
    "mxgraph.aws4.custom_billing_manager": AWSNodeIconDisplayKey.billingConductor.name,
    "mxgraph.aws4.budgets_2": AWSNodeIconDisplayKey.budgets.name,
    "mxgraph.aws4.cost_and_usage_report": AWSNodeIconDisplayKey.costAndUsageReport.name,
    "mxgraph.aws4.cost_explorer": AWSNodeIconDisplayKey.costExplorer.name,
    "mxgraph.aws4.reserved_instance_reporting": AWSNodeIconDisplayKey.reservedInstanceReporting.name,
    "mxgraph.aws4.savings_plans": AWSNodeIconDisplayKey.savingsPlans.name,
    # AWSComputeNodeIconKey
    "mxgraph.aws4.auto_scaling3": AWSNodeIconDisplayKey.applicationAutoScaling.name,
    "mxgraph.aws4.app_runner": AWSNodeIconDisplayKey.appRunner.name,
    "mxgraph.aws4.batch": AWSNodeIconDisplayKey.batch.name,
    "mxgraph.aws4.bottlerocket": AWSNodeIconDisplayKey.bottlerocket.name,
    "mxgraph.aws4.compute_optimizer": AWSNodeIconDisplayKey.computeOptimizer.name,
    "mxgraph.aws4.ec2": AWSNodeIconDisplayKey.ec2.name,
    "mxgraph.aws4.auto_scaling2": AWSNodeIconDisplayKey.ec2AutoScaling.name,
    "mxgraph.aws4.ec2_image_builder": AWSNodeIconDisplayKey.ec2ImageBuilder.name,
    "mxgraph.aws4.elastic_beanstalk": AWSNodeIconDisplayKey.elasticBeanstalk.name,
    "mxgraph.aws4.elastic_fabric_adapter": AWSNodeIconDisplayKey.elasticFabricAdapter.name,
    "mxgraph.aws4.fargate": AWSNodeIconDisplayKey.fargate.name,
    "mxgraph.aws4.lambda": AWSNodeIconDisplayKey.Lambda.value,  # Different from others due to python keyword
    "mxgraph.aws4.lightsail": AWSNodeIconDisplayKey.lightsail.name,
    "mxgraph.aws4.local_zones": AWSNodeIconDisplayKey.localZones.name,
    "mxgraph.aws4.nice_dcv": AWSNodeIconDisplayKey.niceDCV.name,
    "mxgraph.aws4.nice_enginframe": AWSNodeIconDisplayKey.niceEnginFrame.name,
    "mxgraph.aws4.nitro_enclaves": AWSNodeIconDisplayKey.nitroEnclaves.name,
    "mxgraph.aws4.outposts_family": AWSNodeIconDisplayKey.outpostsFamily.name,
    "mxgraph.aws4.outposts": AWSNodeIconDisplayKey.outpostsRack.name,
    "mxgraph.aws4.outposts_1u_and_2u_servers": AWSNodeIconDisplayKey.outpostsServers.name,
    "mxgraph.aws4.parallel_cluster": AWSNodeIconDisplayKey.parallelCluster.name,
    "mxgraph.aws4.serverless_application_repository": AWSNodeIconDisplayKey.serverlessApplicationRepository.name,
    "mxgraph.aws4.simspace_weaver": AWSNodeIconDisplayKey.simSpaceWeaver.name,
    "mxgraph.aws4.thinkbox_deadline": AWSNodeIconDisplayKey.thinkboxDeadline.name,
    "mxgraph.aws4.thinkbox_frost": AWSNodeIconDisplayKey.thinkboxFrost.name,
    "mxgraph.aws4.thinkbox_krakatoa": AWSNodeIconDisplayKey.thinkboxKrakatoa.name,
    "mxgraph.aws4.thinkbox_sequoia": AWSNodeIconDisplayKey.thinkboxSequoia.name,
    "mxgraph.aws4.thinkbox_stoke": AWSNodeIconDisplayKey.thinkboxStoke.name,
    "mxgraph.aws4.thinkbox_xmesh": AWSNodeIconDisplayKey.thinkboxXMesh.name,
    "mxgraph.aws4.vmware_cloud_on_aws": AWSNodeIconDisplayKey.vmwareCloudOnAWS.name,
    "mxgraph.aws4.wavelength": AWSNodeIconDisplayKey.wavelength.name,
    # AWSContainersNodeIconKey
    "mxgraph.aws4.ecs_anywhere": AWSNodeIconDisplayKey.ecsAnywhere.name,
    "mxgraph.aws4.eks_anywhere": AWSNodeIconDisplayKey.eksAnywhere.name,
    "mxgraph.aws4.eks_distro": AWSNodeIconDisplayKey.eksDistro.name,
    "mxgraph.aws4.ecr": AWSNodeIconDisplayKey.elasticContainerRegistry.name,
    "mxgraph.aws4.ecs": AWSNodeIconDisplayKey.elasticContainerService.name,
    "mxgraph.aws4.eks": AWSNodeIconDisplayKey.kubernetesPod.name,
    "mxgraph.aws4.red_hat_openshift": AWSNodeIconDisplayKey.redHatOpenShiftService.name,
    # AWSCustomerEnablementNodeIconKey
    "mxgraph.aws4.activate": AWSNodeIconDisplayKey.activate.name,
    "mxgraph.aws4.iq": AWSNodeIconDisplayKey.iq.name,
    "mxgraph.aws4.professional_services": AWSNodeIconDisplayKey.professionalServices.name,
    "mxgraph.aws4.repost": AWSNodeIconDisplayKey.rePost.name,
    "mxgraph.aws4.repost_private": AWSNodeIconDisplayKey.rePostPrivate.name,
    "mxgraph.aws4.support": AWSNodeIconDisplayKey.support.name,
    "mxgraph.aws4.training_certification": AWSNodeIconDisplayKey.trainingCertification.name,
    # AWSDatabaseNodeIconKey
    "mxgraph.aws4.aurora": AWSNodeIconDisplayKey.aurora.name,
    "mxgraph.aws4.database_migration_service": AWSNodeIconDisplayKey.databaseMigrationService.name,
    "mxgraph.aws4.documentdb_with_mongodb_compatibility": AWSNodeIconDisplayKey.documentDB.name,
    "mxgraph.aws4.dynamodb": AWSNodeIconDisplayKey.dynamoDB.name,
    "mxgraph.aws4.elasticache": AWSNodeIconDisplayKey.elastiCache.name,
    "mxgraph.aws4.keyspaces": AWSNodeIconDisplayKey.keyspaces.name,
    "mxgraph.aws4.memorydb_for_redis": AWSNodeIconDisplayKey.memoryDBForRedis.name,
    "mxgraph.aws4.neptune": AWSNodeIconDisplayKey.neptune.name,
    "mxgraph.aws4.rds": AWSNodeIconDisplayKey.rds.name,
    "mxgraph.aws4.rds_instance_alt": AWSNodeIconDisplayKey.rdsInstance.name,
    "mxgraph.aws4.rds_on_vmware": AWSNodeIconDisplayKey.rdsOnVMware.name,
    "mxgraph.aws4.timestream": AWSNodeIconDisplayKey.timestream.name,
    # AWSDeveloperToolsNodeIconKey
    "mxgraph.aws4.application_composer": AWSNodeIconDisplayKey.applicationComposer.name,
    "mxgraph.aws4.cloud9": AWSNodeIconDisplayKey.cloud9.name,
    "mxgraph.aws4.cloud_control_api": AWSNodeIconDisplayKey.cloudControlAPI.name,
    "mxgraph.aws4.cloud_development_kit": AWSNodeIconDisplayKey.cloudDevelopmentKit.name,
    "mxgraph.aws4.cloudshell": AWSNodeIconDisplayKey.cloudShell.name,
    "mxgraph.aws4.codeartifact": AWSNodeIconDisplayKey.codeArtifact.name,
    "mxgraph.aws4.codebuild": AWSNodeIconDisplayKey.codeBuild.name,
    "mxgraph.aws4.codecatalyst": AWSNodeIconDisplayKey.codeCatalyst.name,
    "mxgraph.aws4.codecommit": AWSNodeIconDisplayKey.codeCommit.name,
    "mxgraph.aws4.codedeploy": AWSNodeIconDisplayKey.codeDeploy.name,
    "mxgraph.aws4.codepipeline": AWSNodeIconDisplayKey.codePipeline.name,
    "mxgraph.aws4.command_line_interface": AWSNodeIconDisplayKey.commandLineInterface.name,
    "mxgraph.aws4.corretto": AWSNodeIconDisplayKey.corretto.name,
    "mxgraph.aws4.tools_and_sdks": AWSNodeIconDisplayKey.toolsAndSDKs.name,
    "mxgraph.aws4.xray": AWSNodeIconDisplayKey.xRay.name,
    # AWSEndUserComputingNodeIconKey
    "mxgraph.aws4.appstream_20": AWSNodeIconDisplayKey.appStream.name,
    "mxgraph.aws4.workspaces_family": AWSNodeIconDisplayKey.workSpacesFamily.name,
    # AWSFrontEndWebMobileNodeIconKey
    "mxgraph.aws4.amplify": AWSNodeIconDisplayKey.amplify.name,
    "mxgraph.aws4.device_farm": AWSNodeIconDisplayKey.deviceFarm.name,
    "mxgraph.aws4.location_service": AWSNodeIconDisplayKey.locationService.name,
    # AWSGamesNodeIconKey
    "mxgraph.aws4.gamekit": AWSNodeIconDisplayKey.gameKit.name,
    "mxgraph.aws4.gamelift_2": AWSNodeIconDisplayKey.gameLift.name,
    "mxgraph.aws4.gamesparks": AWSNodeIconDisplayKey.gameSparks.name,
    "mxgraph.aws4.lumberyard": AWSNodeIconDisplayKey.lumberyard.name,
    "mxgraph.aws4.open_3d_engine_2": AWSNodeIconDisplayKey.open3DEngine.name,
    # AWSInternetOfThingsNodeIconKey
    "mxgraph.aws4.freertos": AWSNodeIconDisplayKey.freeRTOS.name,
    "mxgraph.aws4.iot_1click": AWSNodeIconDisplayKey.iot1Click.name,
    "mxgraph.aws4.iot_analytics": AWSNodeIconDisplayKey.iotAnalytics.name,
    "mxgraph.aws4.iot_button": AWSNodeIconDisplayKey.iotButton.name,
    "mxgraph.aws4.iot_core": AWSNodeIconDisplayKey.iotCore.name,
    "mxgraph.aws4.iot_device_defender": AWSNodeIconDisplayKey.iotDeviceDefender.name,
    "mxgraph.aws4.iot_device_management": AWSNodeIconDisplayKey.iotDeviceManagement.name,
    "mxgraph.aws4.iot_edukit": AWSNodeIconDisplayKey.iotEduKit.name,
    "mxgraph.aws4.iot_events": AWSNodeIconDisplayKey.iotEvents.name,
    "mxgraph.aws4.iot_expresslink": AWSNodeIconDisplayKey.iotExpressLink.name,
    "mxgraph.aws4.iot_fleetwise": AWSNodeIconDisplayKey.iotFleetWise.name,
    "mxgraph.aws4.greengrass": AWSNodeIconDisplayKey.iotGreengrass.name,
    "mxgraph.aws4.iot_roborunner": AWSNodeIconDisplayKey.iotRoboRunner.name,
    "mxgraph.aws4.iot_sitewise": AWSNodeIconDisplayKey.iotSiteWise.name,
    "mxgraph.aws4.iot_things_graph": AWSNodeIconDisplayKey.iotThingsGraph.name,
    "mxgraph.aws4.iot_twinmaker": AWSNodeIconDisplayKey.iotTwinMaker.name,
    # AWSMachineLearningNodeIconKey
    "mxgraph.aws4.apache_mxnet_on_aws": AWSNodeIconDisplayKey.apacheMXNetOnAWS.name,
    "mxgraph.aws4.augmented_ai": AWSNodeIconDisplayKey.augmentedAIA2I.name,
    "mxgraph.aws4.codeguru_2": AWSNodeIconDisplayKey.codeGuru.name,
    "mxgraph.aws4.codewhisperer": AWSNodeIconDisplayKey.codeWhisperer.name,
    "mxgraph.aws4.comprehend": AWSNodeIconDisplayKey.comprehend.name,
    "mxgraph.aws4.comprehend_medical": AWSNodeIconDisplayKey.comprehendMedical.name,
    "mxgraph.aws4.deepcomposer": AWSNodeIconDisplayKey.deepComposer.name,
    "mxgraph.aws4.deep_learning_amis": AWSNodeIconDisplayKey.deepLearningAMIs.name,
    "mxgraph.aws4.deep_learning_containers": AWSNodeIconDisplayKey.deepLearningContainers.name,
    "mxgraph.aws4.deepracer": AWSNodeIconDisplayKey.deepRacer.name,
    "mxgraph.aws4.devops_guru": AWSNodeIconDisplayKey.devOpsGuru.name,
    "mxgraph.aws4.elastic_inference_2": AWSNodeIconDisplayKey.elasticInference.name,
    "mxgraph.aws4.forecast": AWSNodeIconDisplayKey.forecast.name,
    "mxgraph.aws4.fraud_detector": AWSNodeIconDisplayKey.fraudDetector.name,
    "mxgraph.aws4.healthlake": AWSNodeIconDisplayKey.healthLake.name,
    "mxgraph.aws4.kendra": AWSNodeIconDisplayKey.kendra.name,
    "mxgraph.aws4.lex": AWSNodeIconDisplayKey.lex.name,
    "mxgraph.aws4.lookout_for_equipment": AWSNodeIconDisplayKey.lookoutForEquipment.name,
    "mxgraph.aws4.lookout_for_metrics": AWSNodeIconDisplayKey.lookoutForMetrics.name,
    "mxgraph.aws4.lookout_for_vision": AWSNodeIconDisplayKey.lookoutForVision.name,
    "mxgraph.aws4.monitron": AWSNodeIconDisplayKey.monitron.name,
    "mxgraph.aws4.neuron_ml_sdk": AWSNodeIconDisplayKey.neuron.name,
    "mxgraph.aws4.omics": AWSNodeIconDisplayKey.omics.name,
    "mxgraph.aws4.panorama": AWSNodeIconDisplayKey.panorama.name,
    "mxgraph.aws4.personalize": AWSNodeIconDisplayKey.personalize.name,
    "mxgraph.aws4.polly": AWSNodeIconDisplayKey.polly.name,
    "mxgraph.aws4.rekognition_2": AWSNodeIconDisplayKey.rekognition.name,
    "mxgraph.aws4.sagemaker": AWSNodeIconDisplayKey.sageMaker.name,
    "mxgraph.aws4.sagemaker_ground_truth": AWSNodeIconDisplayKey.sageMakerGroundTruth.name,
    "mxgraph.aws4.sagemaker_studio_lab": AWSNodeIconDisplayKey.sageMakerStudioLab.name,
    "mxgraph.aws4.tensorflow_on_aws": AWSNodeIconDisplayKey.tensorFlowOnAWS.name,
    "mxgraph.aws4.textract": AWSNodeIconDisplayKey.textract.name,
    "mxgraph.aws4.torchserve": AWSNodeIconDisplayKey.torchServe.name,
    "mxgraph.aws4.transcribe": AWSNodeIconDisplayKey.transcribeAWS.name,
    "mxgraph.aws4.translate": AWSNodeIconDisplayKey.translate.name,
    # AWSManagementGovernanceNodeIconKey
    "mxgraph.aws4.app_config": AWSNodeIconDisplayKey.appConfig.name,
    "mxgraph.aws4.autoscaling": AWSNodeIconDisplayKey.autoScaling.name,
    "mxgraph.aws4.backint_agent": AWSNodeIconDisplayKey.backintAgent.name,
    "mxgraph.aws4.chatbot": AWSNodeIconDisplayKey.chatbot.name,
    "mxgraph.aws4.cloudformation": AWSNodeIconDisplayKey.cloudFormation.name,
    "mxgraph.aws4.cloudtrail": AWSNodeIconDisplayKey.cloudTrail.name,
    "mxgraph.aws4.cloudwatch_2": AWSNodeIconDisplayKey.cloudWatch.name,
    "mxgraph.aws4.config": AWSNodeIconDisplayKey.config.name,
    "mxgraph.aws4.control_tower": AWSNodeIconDisplayKey.controlTower.name,
    "mxgraph.aws4.distro_for_opentelemetry": AWSNodeIconDisplayKey.distroForOpenTelemetry.name,
    "mxgraph.aws4.fault_injection_simulator": AWSNodeIconDisplayKey.faultInjectionSimulator.name,
    "mxgraph.aws4.app_wizard": AWSNodeIconDisplayKey.launchWizard.name,
    "mxgraph.aws4.license_manager": AWSNodeIconDisplayKey.licenseManager.name,
    "mxgraph.aws4.managed_service_for_grafana": AWSNodeIconDisplayKey.managedGrafana.name,
    "mxgraph.aws4.managed_service_for_prometheus": AWSNodeIconDisplayKey.managedServiceForPrometheus.name,
    "mxgraph.aws4.management_console": AWSNodeIconDisplayKey.managementConsole.name,
    "mxgraph.aws4.opsworks": AWSNodeIconDisplayKey.opsWorks.name,
    "mxgraph.aws4.organizations": AWSNodeIconDisplayKey.organizations.name,
    "mxgraph.aws4.personal_health_dashboard": AWSNodeIconDisplayKey.personalHealthDashboard.name,
    "mxgraph.aws4.proton": AWSNodeIconDisplayKey.proton.name,
    "mxgraph.aws4.resilience_hub": AWSNodeIconDisplayKey.resilienceHub.name,
    "mxgraph.aws4.resource_explorer": AWSNodeIconDisplayKey.resourceExplorer.name,
    "mxgraph.aws4.service_catalog": AWSNodeIconDisplayKey.serviceCatalog.name,
    "mxgraph.aws4.service_management_connector": AWSNodeIconDisplayKey.serviceManagementConnector.name,
    "mxgraph.aws4.systems_manager": AWSNodeIconDisplayKey.systemsManager.name,
    "mxgraph.aws4.trusted_advisor": AWSNodeIconDisplayKey.trustedAdvisor.name,
    "mxgraph.aws4.well_architect_tool": AWSNodeIconDisplayKey.wellArchitectedTool.name,
    # AWSMediaServicesNodeIconKey
    "mxgraph.aws4.elastic_transcoder": AWSNodeIconDisplayKey.elasticTranscoder.name,
    "mxgraph.aws4.elemental": AWSNodeIconDisplayKey.elementalAppliancesAndSoftware.name,
    # "mxgraph.aws4.elementalconductor": AWSNodeIconDisplayKey.elementalConductor.name,
    # "mxgraph.aws4.elementaldelta": AWSNodeIconDisplayKey.elementalDelta.name,
    "mxgraph.aws4.elemental_link": AWSNodeIconDisplayKey.elementalLink.name,
    # "mxgraph.aws4.elementallive": AWSNodeIconDisplayKey.elementalLive.name,
    "mxgraph.aws4.elemental_mediaconnect": AWSNodeIconDisplayKey.elementalMediaConnect.name,
    "mxgraph.aws4.elemental_mediaconvert": AWSNodeIconDisplayKey.elementalMediaConvert.name,
    "mxgraph.aws4.elemental_medialive": AWSNodeIconDisplayKey.elementalMediaLive.name,
    "mxgraph.aws4.elemental_mediapackage": AWSNodeIconDisplayKey.elementalMediaPackage.name,
    "mxgraph.aws4.elemental_mediastore": AWSNodeIconDisplayKey.elementalMediaStore.name,
    "mxgraph.aws4.elemental_mediatailor": AWSNodeIconDisplayKey.elementalMediaTailor.name,
    # "mxgraph.aws4.elementalserver": "elementalServer",
    "mxgraph.aws4.interactive_video": AWSNodeIconDisplayKey.interactiveVideoService.name,
    "mxgraph.aws4.nimble_studio": AWSNodeIconDisplayKey.nimbleStudio.name,
    # AWSMigrationTransferNodeIconKey
    "mxgraph.aws4.application_discovery_service": AWSNodeIconDisplayKey.applicationDiscoveryService.name,
    "mxgraph.aws4.cloudendure_migration": AWSNodeIconDisplayKey.applicationMigrationService.name,
    "mxgraph.aws4.datasync": AWSNodeIconDisplayKey.dataSync.name,
    "mxgraph.aws4.mainframe_modernization": AWSNodeIconDisplayKey.mainframeModernization.name,
    "mxgraph.aws4.migration_evaluator": AWSNodeIconDisplayKey.migrationEvaluator.name,
    "mxgraph.aws4.migration_hub": AWSNodeIconDisplayKey.migrationHub.name,
    "mxgraph.aws4.server_migration_service": AWSNodeIconDisplayKey.serverMigrationService.name,
    "mxgraph.aws4.transfer_family": AWSNodeIconDisplayKey.transferFamily.name,
    # AWSNetworkingContentDeliveryNodeIconKey
    "mxgraph.aws4.app_mesh": AWSNodeIconDisplayKey.appMesh.name,
    "mxgraph.aws4.client_vpn": AWSNodeIconDisplayKey.clientVPN.name,
    "mxgraph.aws4.cloud_directory": AWSNodeIconDisplayKey.cloudDirectory.name,
    "mxgraph.aws4.cloudfront": AWSNodeIconDisplayKey.cloudFront.name,
    "mxgraph.aws4.cloud_map": AWSNodeIconDisplayKey.cloudMap.name,
    "mxgraph.aws4.cloud_wan": AWSNodeIconDisplayKey.cloudWAN.name,
    "mxgraph.aws4.direct_connect": AWSNodeIconDisplayKey.directConnect.name,
    "mxgraph.aws4.elastic_load_balancing": AWSNodeIconDisplayKey.elasticLoadBalancing.name,
    "mxgraph.aws4.global_accelerator": AWSNodeIconDisplayKey.globalAccelerator.name,
    "mxgraph.aws4.private_5g": AWSNodeIconDisplayKey.private5G.name,
    "mxgraph.aws4.vpc_privatelink": AWSNodeIconDisplayKey.privateLink.name,
    "mxgraph.aws4.route_53": AWSNodeIconDisplayKey.route53.name,
    "mxgraph.aws4.site_to_site_vpn": AWSNodeIconDisplayKey.siteToSite.name,
    "mxgraph.aws4.transit_gateway": AWSNodeIconDisplayKey.transitGateway.name,
    "mxgraph.aws4.verified_access": AWSNodeIconDisplayKey.verifiedAccess.name,
    "mxgraph.aws4.vpc": AWSNodeIconDisplayKey.vpc.name,
    "mxgraph.aws4.vpc_lattice": AWSNodeIconDisplayKey.vpcLattice.name,
    "mxgraph.aws4.application_load_balancer": AWSNodeIconDisplayKey.elbApplicationLoadBalancer.name,
    "mxgraph.aws4.classic_load_balancer": AWSNodeIconDisplayKey.elbClassicLoadBalancer.name,
    "mxgraph.aws4.gateway_load_balancer": AWSNodeIconDisplayKey.elbGatewayLoadBalancer.name,
    "mxgraph.aws4.network_load_balancer": AWSNodeIconDisplayKey.elbNetworkLoadBalancer.name,
    "mxgraph.aws4.route_table": AWSNodeIconDisplayKey.route53RouteTable.name,
    "mxgraph.aws4.vpc_virtual_private_cloud_vpc": AWSNodeIconDisplayKey.vpcAlt.name,
    "mxgraph.aws4.vpc_carrier_gateway": AWSNodeIconDisplayKey.vpcCarrierGateway.name,
    "mxgraph.aws4.customer_gateway": AWSNodeIconDisplayKey.vpcCustomerGateway.name,
    "mxgraph.aws4.elastic_network_adapter": AWSNodeIconDisplayKey.vpcElasticNetworkAdapter.name,
    "mxgraph.aws4.elastic_network_interface": AWSNodeIconDisplayKey.vpcElasticNetworkInterface.name,
    "mxgraph.aws4.endpoints": AWSNodeIconDisplayKey.vpcEndpoints.name,
    "mxgraph.aws4.flow_logs": AWSNodeIconDisplayKey.vpcFlowLogs.name,
    "mxgraph.aws4.internet_gateway": AWSNodeIconDisplayKey.vpcInternetGateway.name,
    "mxgraph.aws4.nat_gateway": AWSNodeIconDisplayKey.vpcNATGateway.name,
    "mxgraph.aws4.vpc_network_access_analyzer": AWSNodeIconDisplayKey.vpcNetworkAccessAnalyzer.name,
    "mxgraph.aws4.network_access_control_list": AWSNodeIconDisplayKey.vpcNetworkAccessControlList.name,
    "mxgraph.aws4.peering": AWSNodeIconDisplayKey.vpcPeeringConnection.name,
    "mxgraph.aws4.vpc_reachability_analyzer": AWSNodeIconDisplayKey.vpcReachabilityAnalyzer.name,
    "mxgraph.aws4.router": AWSNodeIconDisplayKey.vpcRouter.name,
    "mxgraph.aws4.vpc_traffic_mirroring": AWSNodeIconDisplayKey.vpcTrafficMirroring.name,
    "mxgraph.aws4.vpn_gateway": AWSNodeIconDisplayKey.vpcVPNGateway.name,
    # AWSSecurityIdentityComplianceNodeIconKey
    "mxgraph.aws4.audit_manager": AWSNodeIconDisplayKey.auditManager.name,
    "mxgraph.aws4.certificate_manager_3": AWSNodeIconDisplayKey.certificateManager.name,
    "mxgraph.aws4.cloudhsm": AWSNodeIconDisplayKey.cloudHSM.name,
    "mxgraph.aws4.cognito": AWSNodeIconDisplayKey.cognito.name,
    "mxgraph.aws4.detective": AWSNodeIconDisplayKey.detective.name,
    "mxgraph.aws4.directory_service": AWSNodeIconDisplayKey.directoryService.name,
    "mxgraph.aws4.firewall_manager": AWSNodeIconDisplayKey.firewallManager.name,
    "mxgraph.aws4.guardduty": AWSNodeIconDisplayKey.guardDuty.name,
    "mxgraph.aws4.single_sign_on": AWSNodeIconDisplayKey.iamIdentityCenter.name,
    "mxgraph.aws4.identity_and_access_management": AWSNodeIconDisplayKey.identityAndAccessManagement.name,
    "mxgraph.aws4.inspector": AWSNodeIconDisplayKey.inspector.name,
    "mxgraph.aws4.key_management_service": AWSNodeIconDisplayKey.keyManagementService.name,
    "mxgraph.aws4.macie": AWSNodeIconDisplayKey.macie.name,
    "mxgraph.aws4.network_firewall": AWSNodeIconDisplayKey.networkFirewall.name,
    "mxgraph.aws4.private_certificate_authority": AWSNodeIconDisplayKey.privateCertificateAuthority.name,
    "mxgraph.aws4.resource_access_manager": AWSNodeIconDisplayKey.resourceAccessManager.name,
    "mxgraph.aws4.secrets_manager": AWSNodeIconDisplayKey.secretsManager.name,
    "mxgraph.aws4.security_hub": AWSNodeIconDisplayKey.securityHub.name,
    "mxgraph.aws4.security_lake": AWSNodeIconDisplayKey.securityLake.name,
    "mxgraph.aws4.shield": AWSNodeIconDisplayKey.shield.name,
    "mxgraph.aws4.signer": AWSNodeIconDisplayKey.signer.name,
    "mxgraph.aws4.verified_permissions": AWSNodeIconDisplayKey.verifiedPermissions.name,
    "mxgraph.aws4.waf": AWSNodeIconDisplayKey.waf.name,
    # AWSStorageNodeIconKey
    "mxgraph.aws4.backup": AWSNodeIconDisplayKey.backup.name,
    "mxgraph.aws4.elastic_block_store": AWSNodeIconDisplayKey.ebs.name,
    "mxgraph.aws4.elastic_file_system": AWSNodeIconDisplayKey.efs.name,
    "mxgraph.aws4.cloudendure_disaster_recovery": AWSNodeIconDisplayKey.elasticDisasterRecovery.name,
    "mxgraph.aws4.file_cache": AWSNodeIconDisplayKey.fileCache.name,
    "mxgraph.aws4.fsx": AWSNodeIconDisplayKey.fsx.name,
    "mxgraph.aws4.fsx_for_lustre": AWSNodeIconDisplayKey.fsxForLustre.name,
    "mxgraph.aws4.fsx_for_netapp_ontap": AWSNodeIconDisplayKey.fsxForNetAppONTAP.name,
    "mxgraph.aws4.fsx_for_openzfs": AWSNodeIconDisplayKey.fsxForOpenZFS.name,
    "mxgraph.aws4.fsx_for_windows_file_server": AWSNodeIconDisplayKey.fsxForWFS.name,
    "mxgraph.aws4.s3": AWSNodeIconDisplayKey.s3.name,
    "mxgraph.aws4.glacier": AWSNodeIconDisplayKey.s3Glacier.name,
    "mxgraph.aws4.snowball": AWSNodeIconDisplayKey.snowball.name,
    "mxgraph.aws4.snowball_edge": AWSNodeIconDisplayKey.snowballEdge.name,
    "mxgraph.aws4.snowcone": AWSNodeIconDisplayKey.snowcone.name,
    "mxgraph.aws4.snowmobile": AWSNodeIconDisplayKey.snowmobile.name,
    "mxgraph.aws4.storage_gateway": AWSNodeIconDisplayKey.storageGateway.name,
    # AWSOthersNodeIconKey
    "mxgraph.aws4.braket": AWSNodeIconDisplayKey.braket.name,
    "mxgraph.aws4.ground_station": AWSNodeIconDisplayKey.groundStation.name,
    "mxgraph.aws4.managed_blockchain": AWSNodeIconDisplayKey.managedBlockchain.name,
    "mxgraph.aws4.marketplace": AWSNodeIconDisplayKey.marketplace.name,
    "mxgraph.aws4.quantum_ledger_database": AWSNodeIconDisplayKey.quantumLedgerDatabase.name,
    "mxgraph.aws4.robomaker": AWSNodeIconDisplayKey.roboMaker.name,
    # "mxgraph.aws4.singlesignon": AWSNodeIconDisplayKey.singleSignOn.name,
}

MXGRAPH_TO_GENERIC_ICON_MAPPING = {
    "mxgraph.aws4.generic_firewall": GenericNodeIconDisplayKey.firewall.name,
    # "mxgraph.aws4.generic_forums": GenericNodeIconDisplayKey.forums.name,
    "mxgraph.aws4.generic_application": GenericNodeIconDisplayKey.genericApplication.name,
    "mxgraph.aws4.generic_database": GenericNodeIconDisplayKey.genericDatabase.name,
    "mxgraph.aws4.management_console2": GenericNodeIconDisplayKey.genericManagementConsole.name,
    "mxgraph.aws4.traditional_server": GenericNodeIconDisplayKey.genericServer.name,
    "mxgraph.aws4.servers": GenericNodeIconDisplayKey.genericServers.name,
    "mxgraph.aws4.shield2": GenericNodeIconDisplayKey.genericShield.name,
    "mxgraph.aws4.internet": GenericNodeIconDisplayKey.internet.name,
    "mxgraph.aws4.internet_alt1": GenericNodeIconDisplayKey.internet.name,
    "mxgraph.aws4.internet_alt2": GenericNodeIconDisplayKey.internet.name,
    "mxgraph.aws4.internet_alt22": GenericNodeIconDisplayKey.internet.name,
    # "mxgraph.aws4.generic_router": GenericNodeIconDisplayKey.router.name,
    # "mxgraph.aws4.generic_switch": GenericNodeIconDisplayKey.switch.name,
    # "mxgraph.aws4.generic_credentials": GenericNodeIconDisplayKey.credentials.name,
    # "mxgraph.aws4.generic_dataStream": GenericNodeIconDisplayKey.dataStream.name,
    # "mxgraph.aws4.generic_dataTable": GenericNodeIconDisplayKey.dataTable.name,
    # "mxgraph.aws4.generic_document": GenericNodeIconDisplayKey.document.name,
    # "mxgraph.aws4.generic_documents": GenericNodeIconDisplayKey.documents.name,
    # "mxgraph.aws4.generic_email": GenericNodeIconDisplayKey.email.name,
    # "mxgraph.aws4.generic_folder": GenericNodeIconDisplayKey.folder.name,
    # "mxgraph.aws4.generic_folders": GenericNodeIconDisplayKey.folders.name,
    # "mxgraph.aws4.generic_gitRepository": GenericNodeIconDisplayKey.gitRepository.name,
    # "mxgraph.aws4.generic_logs": GenericNodeIconDisplayKey.logs.name,
    # "mxgraph.aws4.generic_sdk": GenericNodeIconDisplayKey.sdk.name,
    # "mxgraph.aws4.generic_sourceCode": GenericNodeIconDisplayKey.sourceCode.name,
    # "mxgraph.aws4.generic_sslPadlock": GenericNodeIconDisplayKey.sslPadlock.name,
    # "mxgraph.aws4.generic_user": GenericNodeIconDisplayKey.user.name,
    # "mxgraph.aws4.generic_userAuthenticated": GenericNodeIconDisplayKey.userAuthenticated.name,
    # "mxgraph.aws4.generic_users": GenericNodeIconDisplayKey.users.name,
    "mxgraph.aws4.camera2": GenericNodeIconDisplayKey.camera.name,
    "mxgraph.aws4.client": GenericNodeIconDisplayKey.client.name,
    "mxgraph.aws4.disk": GenericNodeIconDisplayKey.disk.name,
    "mxgraph.aws4.gear": GenericNodeIconDisplayKey.gear.name,
    "mxgraph.aws4.multimedia": GenericNodeIconDisplayKey.multimedia.name,
    "mxgraph.aws4.office_building": GenericNodeIconDisplayKey.officeBuilding.name,
    "mxgraph.aws4.tape_storage": GenericNodeIconDisplayKey.tapeStorage.name,
    "mxgraph.aws4.external_toolkit": GenericNodeIconDisplayKey.toolkit.name,
    # "mxgraph.aws4.generic_baseStation": GenericNodeIconDisplayKey.baseStation.name,
    # "mxgraph.aws4.generic_genericActuator": GenericNodeIconDisplayKey.genericActuator.name,
    # "mxgraph.aws4.generic_genericPLC": GenericNodeIconDisplayKey.genericPLC.name,
    # "mxgraph.aws4.generic_genericSensor": GenericNodeIconDisplayKey.genericSensor.name,
    # "mxgraph.aws4.generic_historianDatabase": GenericNodeIconDisplayKey.historianDatabase.name,
    # "mxgraph.aws4.generic_iotGateway": GenericNodeIconDisplayKey.iotGateway.name,
}

MXGRAPH_TO_ICON_MAPPING = {
    **MXGRAPH_TO_AWS_ICON_MAPPING,
    **MXGRAPH_TO_GENERIC_ICON_MAPPING,
}

MXGRAPH_TO_AWS_CLUSTER_ICON_MAPPING = {
    "mxgraph.aws4.group_auto_scaling_group": AWSClusterNodeIconDisplayKey.autoScalingGroup.name,
    "mxgraph.aws4.group_account": AWSClusterNodeIconDisplayKey.awsAccount.name,
    "mxgraph.aws4.group_aws_cloud_alt": AWSClusterNodeIconDisplayKey.awsCloud.name,
    "mxgraph.aws4.group_aws_step_functions_workflow": AWSClusterNodeIconDisplayKey.awsStepFunctionsWorkflow.name,
    # "mxgraph.aws4.awssubnet": AWSClusterNodeIconDisplayKey.awsSubnet.name,
    # "mxgraph.aws4.codepipelinecluster": AWSClusterNodeIconDisplayKey.codePipelineCluster.name,
    # "mxgraph.aws4.datapipelinecluster": AWSClusterNodeIconDisplayKey.dataPipelineCluster.name,
    "mxgraph.aws4.group_elastic_beanstalk": AWSClusterNodeIconDisplayKey.elasticBeanstalkContainer.name,
    "mxgraph.aws4.group_security_group": AWSClusterNodeIconDisplayKey.privateSubnet.name,
    # "mxgraph.aws4.publicsubnet": AWSClusterNodeIconDisplayKey.publicSubnet.name,
    "mxgraph.aws4.group_region": AWSClusterNodeIconDisplayKey.region.name,
    "mxgraph.aws4.group_spot_fleet": AWSClusterNodeIconDisplayKey.spotFleet.name,
    # "mxgraph.aws4.kubernetescluster": AWSClusterNodeIconDisplayKey.kubernetesCluster.name,
    # "mxgraph.aws4.vpccluster": AWSClusterNodeIconDisplayKey.vpcCluster.name,
}

MXGRAPH_TO_GENERIC_CLSUTER_ICON_MAPPING = {
    # "mxgraph.aws4.group_cicd": GenericClusterNodeIconDisplayKey.cicd.name,
    "mxgraph.aws4.group_aws_cloud": GenericClusterNodeIconDisplayKey.genericCloud.name,
    # "mxgraph.aws4.group_genericCodePipeline": GenericClusterNodeIconDisplayKey.genericCodePipeline.name,
    # "mxgraph.aws4.group_genericDataPipeline": GenericClusterNodeIconDisplayKey.genericDataPipeline.name,
    "mxgraph.aws4.group_on_premise": GenericClusterNodeIconDisplayKey.genericServerCluster.name,
    # "mxgraph.aws4.group_genericSubnet": GenericClusterNodeIconDisplayKey.genericSubnet.name,
    "mxgraph.aws4.group_vpc2": GenericClusterNodeIconDisplayKey.genericVPC.name,
    # "mxgraph.aws4.group_genericWirelessSubnet": GenericClusterNodeIconDisplayKey.genericWirelessSubnet.name,
    "mxgraph.aws4.group_corporate_data_center": GenericClusterNodeIconDisplayKey.onPremisesCompute.name,
    # "mxgraph.aws4.group_onPremisesEnvironment": GenericClusterNodeIconDisplayKey.onPremisesEnvironment.name,
}

MXGRAPH_TO_CLUSTER_ICON_MAPPING = {
    **MXGRAPH_TO_AWS_CLUSTER_ICON_MAPPING,
    **MXGRAPH_TO_GENERIC_CLSUTER_ICON_MAPPING,
}

CLUSTER_NODE_BORDER_COLOR = {
    # AWS
    AWSClusterNodeIconDisplayKey.autoScalingGroup.name: "#d8661333",
    AWSClusterNodeIconDisplayKey.awsAccount.name: "#cd226433",
    AWSClusterNodeIconDisplayKey.awsCloud.name: "#232f3e33",
    AWSClusterNodeIconDisplayKey.awsStepFunctionsWorkflow.name: "#cd226433",
    AWSClusterNodeIconDisplayKey.awsSubnet.name: "#232f3e33",
    AWSClusterNodeIconDisplayKey.codePipelineCluster.name: "#2e27ad33",
    AWSClusterNodeIconDisplayKey.dataPipelineCluster.name: "#4d27a833",
    AWSClusterNodeIconDisplayKey.elasticBeanstalkContainer.name: "#d8661333",
    AWSClusterNodeIconDisplayKey.privateSubnet.name: "#00a4a633",
    AWSClusterNodeIconDisplayKey.publicSubnet.name: "#7aa11633",
    AWSClusterNodeIconDisplayKey.region.name: "#00a4a633",
    AWSClusterNodeIconDisplayKey.spotFleet.name: "#d8661333",
    AWSClusterNodeIconDisplayKey.kubernetesCluster.name: "#32659133",
    AWSClusterNodeIconDisplayKey.vpcCluster.name: "#24881433",
    # Generic
    GenericClusterNodeIconDisplayKey.cicd.name: "#5a6c8633",
    GenericClusterNodeIconDisplayKey.genericCloud.name: "#4b4d5033",
    GenericClusterNodeIconDisplayKey.genericCodePipeline.name: "#5a6c8633",
    GenericClusterNodeIconDisplayKey.genericDataPipeline.name: "#5a6c8633",
    GenericClusterNodeIconDisplayKey.genericServerCluster.name: "#5a6c8633",
    GenericClusterNodeIconDisplayKey.genericSubnet.name: "#5a6c8633",
    GenericClusterNodeIconDisplayKey.genericVPC.name: "#5a6c8633",
    GenericClusterNodeIconDisplayKey.genericWirelessSubnet.name: "#5a6c8633",
    GenericClusterNodeIconDisplayKey.onPremisesCompute.name: "#5a6c8633",
    GenericClusterNodeIconDisplayKey.onPremisesEnvironment.name: "#01010233",
}

CLUSTER_NODE_BACKGROUND_COLOR = {
    # AWS
    AWSClusterNodeIconDisplayKey.autoScalingGroup.name: "#d8661310",
    AWSClusterNodeIconDisplayKey.awsAccount.name: "#cd226410",
    AWSClusterNodeIconDisplayKey.awsCloud.name: "#232f3e10",
    AWSClusterNodeIconDisplayKey.awsStepFunctionsWorkflow.name: "#cd226410",
    AWSClusterNodeIconDisplayKey.awsSubnet.name: "#232f3e10",
    AWSClusterNodeIconDisplayKey.codePipelineCluster.name: "#2e27ad10",
    AWSClusterNodeIconDisplayKey.dataPipelineCluster.name: "#4d27a810",
    AWSClusterNodeIconDisplayKey.elasticBeanstalkContainer.name: "#d8661310",
    AWSClusterNodeIconDisplayKey.privateSubnet.name: "#00a4a610",
    AWSClusterNodeIconDisplayKey.publicSubnet.name: "#7aa11610",
    AWSClusterNodeIconDisplayKey.region.name: "#00a4a610",
    AWSClusterNodeIconDisplayKey.spotFleet.name: "#d8661310",
    AWSClusterNodeIconDisplayKey.kubernetesCluster.name: "#32659110",
    AWSClusterNodeIconDisplayKey.vpcCluster.name: "#24881410",
    # Generic
    GenericClusterNodeIconDisplayKey.cicd.name: "#5a6c8633",
    GenericClusterNodeIconDisplayKey.genericCloud.name: "#232f3e33",
    GenericClusterNodeIconDisplayKey.genericCodePipeline.name: "#5a6c8633",
    GenericClusterNodeIconDisplayKey.genericDataPipeline.name: "#5a6c8633",
    GenericClusterNodeIconDisplayKey.genericServerCluster.name: "#5a6c8633",
    GenericClusterNodeIconDisplayKey.genericSubnet.name: "#5a6c8633",
    GenericClusterNodeIconDisplayKey.genericVPC.name: "#5a6c8633",
    GenericClusterNodeIconDisplayKey.genericWirelessSubnet.name: "#5a6c8633",
    GenericClusterNodeIconDisplayKey.onPremisesCompute.name: "#5a6c8633",
    GenericClusterNodeIconDisplayKey.onPremisesEnvironment.name: "#5a6c8633",
}

CLUSTER_NODE_BORDER_STYLE = {
    AWSClusterNodeIconDisplayKey.autoScalingGroup.name: "dashed",
    AWSClusterNodeIconDisplayKey.region.name: "dashed",
}

AWS_LABEL_MAPPING = {
    # AWSAnalyticsNodeIconKey
    AWSNodeIconDisplayKey.athena.name: AWSNodeIconDisplayKey.athena.value,
    AWSNodeIconDisplayKey.cleanRooms.name: AWSNodeIconDisplayKey.cleanRooms.value,
    AWSNodeIconDisplayKey.cloudSearch.name: AWSNodeIconDisplayKey.cloudSearch.value,
    AWSNodeIconDisplayKey.dataExchange.name: AWSNodeIconDisplayKey.dataExchange.value,
    AWSNodeIconDisplayKey.dataPipeline.name: AWSNodeIconDisplayKey.dataPipeline.value,
    AWSNodeIconDisplayKey.dataZone.name: AWSNodeIconDisplayKey.dataZone.value,
    AWSNodeIconDisplayKey.emr.name: AWSNodeIconDisplayKey.emr.value,
    AWSNodeIconDisplayKey.finSpace.name: AWSNodeIconDisplayKey.finSpace.value,
    AWSNodeIconDisplayKey.glue.name: AWSNodeIconDisplayKey.glue.value,
    AWSNodeIconDisplayKey.glueDataBrew.name: AWSNodeIconDisplayKey.glueDataBrew.value,
    AWSNodeIconDisplayKey.glueElasticViews.name: AWSNodeIconDisplayKey.glueElasticViews.value,
    AWSNodeIconDisplayKey.kinesis.name: AWSNodeIconDisplayKey.kinesis.value,
    AWSNodeIconDisplayKey.kinesisDataAnalytics.name: AWSNodeIconDisplayKey.kinesisDataAnalytics.value,
    AWSNodeIconDisplayKey.kinesisDataStreams.name: AWSNodeIconDisplayKey.kinesisDataStreams.value,
    AWSNodeIconDisplayKey.kinesisFirehose.name: AWSNodeIconDisplayKey.kinesisFirehose.value,
    AWSNodeIconDisplayKey.kinesisVideoStreams.name: AWSNodeIconDisplayKey.kinesisVideoStreams.value,
    AWSNodeIconDisplayKey.lakeFormation.name: AWSNodeIconDisplayKey.lakeFormation.value,
    AWSNodeIconDisplayKey.managedStreamingForApacheKafka.name: AWSNodeIconDisplayKey.managedStreamingForApacheKafka.value,
    AWSNodeIconDisplayKey.openSearchService.name: AWSNodeIconDisplayKey.openSearchService.value,
    AWSNodeIconDisplayKey.quickSight.name: AWSNodeIconDisplayKey.quickSight.value,
    AWSNodeIconDisplayKey.redshift.name: AWSNodeIconDisplayKey.redshift.value,
    # AWSAppIntegrationNodeIconKey
    AWSNodeIconDisplayKey.apiGateway.name: AWSNodeIconDisplayKey.apiGateway.value,
    AWSNodeIconDisplayKey.appFlow.name: AWSNodeIconDisplayKey.appFlow.value,
    AWSNodeIconDisplayKey.appSync.name: AWSNodeIconDisplayKey.appSync.value,
    AWSNodeIconDisplayKey.consoleMobileApplication.name: AWSNodeIconDisplayKey.consoleMobileApplication.value,
    AWSNodeIconDisplayKey.eventBridge.name: AWSNodeIconDisplayKey.eventBridge.value,
    AWSNodeIconDisplayKey.expressWorkflows.name: AWSNodeIconDisplayKey.expressWorkflows.value,
    AWSNodeIconDisplayKey.managedWorkflowsForApacheAirflow.name: AWSNodeIconDisplayKey.managedWorkflowsForApacheAirflow.value,
    AWSNodeIconDisplayKey.mq.name: AWSNodeIconDisplayKey.mq.value,
    AWSNodeIconDisplayKey.simpleNotificationService.name: AWSNodeIconDisplayKey.simpleNotificationService.value,
    AWSNodeIconDisplayKey.simpleQueueService.name: AWSNodeIconDisplayKey.simpleQueueService.value,
    AWSNodeIconDisplayKey.stepFunctions.name: AWSNodeIconDisplayKey.stepFunctions.value,
    # AWSBusinessApplicationsNodeIconKey
    AWSNodeIconDisplayKey.alexaForBusiness.name: AWSNodeIconDisplayKey.alexaForBusiness.value,
    AWSNodeIconDisplayKey.chime.name: AWSNodeIconDisplayKey.chime.value,
    AWSNodeIconDisplayKey.chimeSDK.name: AWSNodeIconDisplayKey.chimeSDK.value,
    AWSNodeIconDisplayKey.chimeVoiceConnector.name: AWSNodeIconDisplayKey.chimeVoiceConnector.value,
    AWSNodeIconDisplayKey.connect.name: AWSNodeIconDisplayKey.connect.value,
    AWSNodeIconDisplayKey.honeycode.name: AWSNodeIconDisplayKey.honeycode.value,
    AWSNodeIconDisplayKey.pinpoint.name: AWSNodeIconDisplayKey.pinpoint.value,
    AWSNodeIconDisplayKey.pinpointAPIs.name: AWSNodeIconDisplayKey.pinpointAPIs.value,
    AWSNodeIconDisplayKey.simpleEmailService.name: AWSNodeIconDisplayKey.simpleEmailService.value,
    AWSNodeIconDisplayKey.supplyChain.name: AWSNodeIconDisplayKey.supplyChain.value,
    AWSNodeIconDisplayKey.wickr.name: AWSNodeIconDisplayKey.wickr.value,
    AWSNodeIconDisplayKey.workDocs.name: AWSNodeIconDisplayKey.workDocs.value,
    AWSNodeIconDisplayKey.workDocsSDK.name: AWSNodeIconDisplayKey.workDocsSDK.value,
    AWSNodeIconDisplayKey.workMail.name: AWSNodeIconDisplayKey.workMail.value,
    # AWSCloudFinancialManagementNodeIconKey
    AWSNodeIconDisplayKey.applicationCostProfiler.name: AWSNodeIconDisplayKey.applicationCostProfiler.value,
    AWSNodeIconDisplayKey.billingConductor.name: AWSNodeIconDisplayKey.billingConductor.value,
    AWSNodeIconDisplayKey.budgets.name: AWSNodeIconDisplayKey.budgets.value,
    AWSNodeIconDisplayKey.costAndUsageReport.name: AWSNodeIconDisplayKey.costAndUsageReport.value,
    AWSNodeIconDisplayKey.costExplorer.name: AWSNodeIconDisplayKey.costExplorer.value,
    AWSNodeIconDisplayKey.reservedInstanceReporting.name: AWSNodeIconDisplayKey.reservedInstanceReporting.value,
    AWSNodeIconDisplayKey.savingsPlans.name: AWSNodeIconDisplayKey.savingsPlans.value,
    # AWSComputeNodeIconKey
    AWSNodeIconDisplayKey.appRunner.name: AWSNodeIconDisplayKey.appRunner.value,
    AWSNodeIconDisplayKey.applicationAutoScaling.name: AWSNodeIconDisplayKey.applicationAutoScaling.value,
    AWSNodeIconDisplayKey.batch.name: AWSNodeIconDisplayKey.batch.value,
    AWSNodeIconDisplayKey.bottlerocket.name: AWSNodeIconDisplayKey.bottlerocket.value,
    AWSNodeIconDisplayKey.computeOptimizer.name: AWSNodeIconDisplayKey.computeOptimizer.value,
    AWSNodeIconDisplayKey.ec2.name: AWSNodeIconDisplayKey.ec2.value,
    AWSNodeIconDisplayKey.ec2AutoScaling.name: AWSNodeIconDisplayKey.ec2AutoScaling.value,
    AWSNodeIconDisplayKey.ec2ImageBuilder.name: AWSNodeIconDisplayKey.ec2ImageBuilder.value,
    AWSNodeIconDisplayKey.elasticBeanstalk.name: AWSNodeIconDisplayKey.elasticBeanstalk.value,
    AWSNodeIconDisplayKey.elasticFabricAdapter.name: AWSNodeIconDisplayKey.elasticFabricAdapter.value,
    AWSNodeIconDisplayKey.fargate.name: AWSNodeIconDisplayKey.fargate.value,
    AWSNodeIconDisplayKey.Lambda.value: AWSNodeIconDisplayKey.Lambda.name,
    AWSNodeIconDisplayKey.lightsail.name: AWSNodeIconDisplayKey.lightsail.value,
    AWSNodeIconDisplayKey.localZones.name: AWSNodeIconDisplayKey.localZones.value,
    AWSNodeIconDisplayKey.niceDCV.name: AWSNodeIconDisplayKey.niceDCV.value,
    AWSNodeIconDisplayKey.niceEnginFrame.name: AWSNodeIconDisplayKey.niceEnginFrame.value,
    AWSNodeIconDisplayKey.nitroEnclaves.name: AWSNodeIconDisplayKey.nitroEnclaves.value,
    AWSNodeIconDisplayKey.outpostsFamily.name: AWSNodeIconDisplayKey.outpostsFamily.value,
    AWSNodeIconDisplayKey.outpostsRack.name: AWSNodeIconDisplayKey.outpostsRack.value,
    AWSNodeIconDisplayKey.outpostsServers.name: AWSNodeIconDisplayKey.outpostsServers.value,
    AWSNodeIconDisplayKey.parallelCluster.name: AWSNodeIconDisplayKey.parallelCluster.value,
    AWSNodeIconDisplayKey.serverlessApplicationRepository.name: AWSNodeIconDisplayKey.serverlessApplicationRepository.value,
    AWSNodeIconDisplayKey.simSpaceWeaver.name: AWSNodeIconDisplayKey.simSpaceWeaver.value,
    AWSNodeIconDisplayKey.thinkboxDeadline.name: AWSNodeIconDisplayKey.thinkboxDeadline.value,
    AWSNodeIconDisplayKey.thinkboxFrost.name: AWSNodeIconDisplayKey.thinkboxFrost.value,
    AWSNodeIconDisplayKey.thinkboxKrakatoa.name: AWSNodeIconDisplayKey.thinkboxKrakatoa.value,
    AWSNodeIconDisplayKey.thinkboxSequoia.name: AWSNodeIconDisplayKey.thinkboxSequoia.value,
    AWSNodeIconDisplayKey.thinkboxStoke.name: AWSNodeIconDisplayKey.thinkboxStoke.value,
    AWSNodeIconDisplayKey.thinkboxXMesh.name: AWSNodeIconDisplayKey.thinkboxXMesh.value,
    AWSNodeIconDisplayKey.vmwareCloudOnAWS.name: AWSNodeIconDisplayKey.vmwareCloudOnAWS.value,
    AWSNodeIconDisplayKey.wavelength.name: AWSNodeIconDisplayKey.wavelength.value,
    # AWSContainersNodeIconKey
    AWSNodeIconDisplayKey.ecsAnywhere.name: AWSNodeIconDisplayKey.ecsAnywhere.value,
    AWSNodeIconDisplayKey.eksAnywhere.name: AWSNodeIconDisplayKey.eksAnywhere.value,
    AWSNodeIconDisplayKey.eksDistro.name: AWSNodeIconDisplayKey.eksDistro.value,
    AWSNodeIconDisplayKey.elasticContainerRegistry.name: AWSNodeIconDisplayKey.elasticContainerRegistry.value,
    AWSNodeIconDisplayKey.elasticContainerService.name: AWSNodeIconDisplayKey.elasticContainerService.value,
    AWSNodeIconDisplayKey.kubernetesPod.name: AWSNodeIconDisplayKey.kubernetesPod.value,
    AWSNodeIconDisplayKey.redHatOpenShiftService.name: AWSNodeIconDisplayKey.redHatOpenShiftService.value,
    # AWSCustomerEnablementNodeIconKey
    AWSNodeIconDisplayKey.activate.name: AWSNodeIconDisplayKey.activate.value,
    AWSNodeIconDisplayKey.iq.name: AWSNodeIconDisplayKey.iq.value,
    AWSNodeIconDisplayKey.professionalServices.name: AWSNodeIconDisplayKey.professionalServices.value,
    AWSNodeIconDisplayKey.rePost.name: AWSNodeIconDisplayKey.rePost.value,
    AWSNodeIconDisplayKey.rePostPrivate.name: AWSNodeIconDisplayKey.rePostPrivate.value,
    AWSNodeIconDisplayKey.support.name: AWSNodeIconDisplayKey.support.value,
    AWSNodeIconDisplayKey.trainingCertification.name: AWSNodeIconDisplayKey.trainingCertification.value,
    # AWSDatabaseNodeIconKey
    AWSNodeIconDisplayKey.aurora.name: AWSNodeIconDisplayKey.aurora.value,
    AWSNodeIconDisplayKey.databaseMigrationService.name: AWSNodeIconDisplayKey.databaseMigrationService.value,
    AWSNodeIconDisplayKey.documentDB.name: AWSNodeIconDisplayKey.documentDB.value,
    AWSNodeIconDisplayKey.dynamoDB.name: AWSNodeIconDisplayKey.dynamoDB.value,
    AWSNodeIconDisplayKey.elastiCache.name: AWSNodeIconDisplayKey.elastiCache.value,
    AWSNodeIconDisplayKey.keyspaces.name: AWSNodeIconDisplayKey.keyspaces.value,
    AWSNodeIconDisplayKey.memoryDBForRedis.name: AWSNodeIconDisplayKey.memoryDBForRedis.value,
    AWSNodeIconDisplayKey.neptune.name: AWSNodeIconDisplayKey.neptune.value,
    AWSNodeIconDisplayKey.rds.name: AWSNodeIconDisplayKey.rds.value,
    AWSNodeIconDisplayKey.rdsInstance.name: AWSNodeIconDisplayKey.rdsInstance.value,
    AWSNodeIconDisplayKey.rdsOnVMware.name: AWSNodeIconDisplayKey.rdsOnVMware.value,
    AWSNodeIconDisplayKey.timestream.name: AWSNodeIconDisplayKey.timestream.value,
    # AWSDeveloperToolsNodeIconKey
    AWSNodeIconDisplayKey.applicationComposer.name: AWSNodeIconDisplayKey.applicationComposer.value,
    AWSNodeIconDisplayKey.cloud9.name: AWSNodeIconDisplayKey.cloud9.value,
    AWSNodeIconDisplayKey.cloudControlAPI.name: AWSNodeIconDisplayKey.cloudControlAPI.value,
    AWSNodeIconDisplayKey.cloudDevelopmentKit.name: AWSNodeIconDisplayKey.cloudDevelopmentKit.value,
    AWSNodeIconDisplayKey.cloudShell.name: AWSNodeIconDisplayKey.cloudShell.value,
    AWSNodeIconDisplayKey.codeArtifact.name: AWSNodeIconDisplayKey.codeArtifact.value,
    AWSNodeIconDisplayKey.codeBuild.name: AWSNodeIconDisplayKey.codeBuild.value,
    AWSNodeIconDisplayKey.codeCatalyst.name: AWSNodeIconDisplayKey.codeCatalyst.value,
    AWSNodeIconDisplayKey.codeCommit.name: AWSNodeIconDisplayKey.codeCommit.value,
    AWSNodeIconDisplayKey.codeDeploy.name: AWSNodeIconDisplayKey.codeDeploy.value,
    AWSNodeIconDisplayKey.codePipeline.name: AWSNodeIconDisplayKey.codePipeline.value,
    AWSNodeIconDisplayKey.commandLineInterface.name: AWSNodeIconDisplayKey.commandLineInterface.value,
    AWSNodeIconDisplayKey.corretto.name: AWSNodeIconDisplayKey.corretto.value,
    AWSNodeIconDisplayKey.toolsAndSDKs.name: AWSNodeIconDisplayKey.toolsAndSDKs.value,
    AWSNodeIconDisplayKey.xRay.name: AWSNodeIconDisplayKey.xRay.value,
    # AWSEndUserComputingNodeIconKey
    AWSNodeIconDisplayKey.appStream.name: AWSNodeIconDisplayKey.appStream.value,
    AWSNodeIconDisplayKey.workSpacesFamily.name: AWSNodeIconDisplayKey.workSpacesFamily.value,
    # AWSFrontEndWebMobileNodeIconKey
    AWSNodeIconDisplayKey.amplify.name: AWSNodeIconDisplayKey.amplify.value,
    AWSNodeIconDisplayKey.deviceFarm.name: AWSNodeIconDisplayKey.deviceFarm.value,
    AWSNodeIconDisplayKey.locationService.name: AWSNodeIconDisplayKey.locationService.value,
    # AWSGamesNodeIconKey
    AWSNodeIconDisplayKey.gameKit.name: AWSNodeIconDisplayKey.gameKit.value,
    AWSNodeIconDisplayKey.gameLift.name: AWSNodeIconDisplayKey.gameLift.value,
    AWSNodeIconDisplayKey.gameSparks.name: AWSNodeIconDisplayKey.gameSparks.value,
    AWSNodeIconDisplayKey.lumberyard.name: AWSNodeIconDisplayKey.lumberyard.value,
    AWSNodeIconDisplayKey.open3DEngine.name: AWSNodeIconDisplayKey.open3DEngine.value,
    # AWSInternetOfThingsNodeIconKey
    AWSNodeIconDisplayKey.freeRTOS.name: AWSNodeIconDisplayKey.freeRTOS.value,
    AWSNodeIconDisplayKey.iot1Click.name: AWSNodeIconDisplayKey.iot1Click.value,
    AWSNodeIconDisplayKey.iotAnalytics.name: AWSNodeIconDisplayKey.iotAnalytics.value,
    AWSNodeIconDisplayKey.iotButton.name: AWSNodeIconDisplayKey.iotButton.value,
    AWSNodeIconDisplayKey.iotCore.name: AWSNodeIconDisplayKey.iotCore.value,
    AWSNodeIconDisplayKey.iotDeviceDefender.name: AWSNodeIconDisplayKey.iotDeviceDefender.value,
    AWSNodeIconDisplayKey.iotDeviceManagement.name: AWSNodeIconDisplayKey.iotDeviceManagement.value,
    AWSNodeIconDisplayKey.iotEduKit.name: AWSNodeIconDisplayKey.iotEduKit.value,
    AWSNodeIconDisplayKey.iotEvents.name: AWSNodeIconDisplayKey.iotEvents.value,
    AWSNodeIconDisplayKey.iotExpressLink.name: AWSNodeIconDisplayKey.iotExpressLink.value,
    AWSNodeIconDisplayKey.iotFleetWise.name: AWSNodeIconDisplayKey.iotFleetWise.value,
    AWSNodeIconDisplayKey.iotGreengrass.name: AWSNodeIconDisplayKey.iotGreengrass.value,
    AWSNodeIconDisplayKey.iotRoboRunner.name: AWSNodeIconDisplayKey.iotRoboRunner.value,
    AWSNodeIconDisplayKey.iotSiteWise.name: AWSNodeIconDisplayKey.iotSiteWise.value,
    AWSNodeIconDisplayKey.iotThingsGraph.name: AWSNodeIconDisplayKey.iotThingsGraph.value,
    AWSNodeIconDisplayKey.iotTwinMaker.name: AWSNodeIconDisplayKey.iotTwinMaker.value,
    # AWSMachineLearningNodeIconKey
    AWSNodeIconDisplayKey.apacheMXNetOnAWS.name: AWSNodeIconDisplayKey.apacheMXNetOnAWS.value,
    AWSNodeIconDisplayKey.augmentedAIA2I.name: AWSNodeIconDisplayKey.augmentedAIA2I.value,
    AWSNodeIconDisplayKey.codeGuru.name: AWSNodeIconDisplayKey.codeGuru.value,
    AWSNodeIconDisplayKey.codeWhisperer.name: AWSNodeIconDisplayKey.codeWhisperer.value,
    AWSNodeIconDisplayKey.comprehend.name: AWSNodeIconDisplayKey.comprehend.value,
    AWSNodeIconDisplayKey.comprehendMedical.name: AWSNodeIconDisplayKey.comprehendMedical.value,
    AWSNodeIconDisplayKey.deepComposer.name: AWSNodeIconDisplayKey.deepComposer.value,
    AWSNodeIconDisplayKey.deepLearningAMIs.name: AWSNodeIconDisplayKey.deepLearningAMIs.value,
    AWSNodeIconDisplayKey.deepLearningContainers.name: AWSNodeIconDisplayKey.deepLearningContainers.value,
    AWSNodeIconDisplayKey.deepRacer.name: AWSNodeIconDisplayKey.deepRacer.value,
    AWSNodeIconDisplayKey.devOpsGuru.name: AWSNodeIconDisplayKey.devOpsGuru.value,
    AWSNodeIconDisplayKey.elasticInference.name: AWSNodeIconDisplayKey.elasticInference.value,
    AWSNodeIconDisplayKey.forecast.name: AWSNodeIconDisplayKey.forecast.value,
    AWSNodeIconDisplayKey.fraudDetector.name: AWSNodeIconDisplayKey.fraudDetector.value,
    AWSNodeIconDisplayKey.healthLake.name: AWSNodeIconDisplayKey.healthLake.value,
    AWSNodeIconDisplayKey.kendra.name: AWSNodeIconDisplayKey.kendra.value,
    AWSNodeIconDisplayKey.lex.name: AWSNodeIconDisplayKey.lex.value,
    AWSNodeIconDisplayKey.lookoutForEquipment.name: AWSNodeIconDisplayKey.lookoutForEquipment.value,
    AWSNodeIconDisplayKey.lookoutForMetrics.name: AWSNodeIconDisplayKey.lookoutForMetrics.value,
    AWSNodeIconDisplayKey.lookoutForVision.name: AWSNodeIconDisplayKey.lookoutForVision.value,
    AWSNodeIconDisplayKey.monitron.name: AWSNodeIconDisplayKey.monitron.value,
    AWSNodeIconDisplayKey.neuron.name: AWSNodeIconDisplayKey.neuron.value,
    AWSNodeIconDisplayKey.omics.name: AWSNodeIconDisplayKey.omics.value,
    AWSNodeIconDisplayKey.panorama.name: AWSNodeIconDisplayKey.panorama.value,
    AWSNodeIconDisplayKey.personalize.name: AWSNodeIconDisplayKey.personalize.value,
    AWSNodeIconDisplayKey.polly.name: AWSNodeIconDisplayKey.polly.value,
    AWSNodeIconDisplayKey.rekognition.name: AWSNodeIconDisplayKey.rekognition.value,
    AWSNodeIconDisplayKey.sageMaker.name: AWSNodeIconDisplayKey.sageMaker.value,
    AWSNodeIconDisplayKey.sageMakerGroundTruth.name: AWSNodeIconDisplayKey.sageMakerGroundTruth.value,
    AWSNodeIconDisplayKey.sageMakerStudioLab.name: AWSNodeIconDisplayKey.sageMakerStudioLab.value,
    AWSNodeIconDisplayKey.tensorFlowOnAWS.name: AWSNodeIconDisplayKey.tensorFlowOnAWS.value,
    AWSNodeIconDisplayKey.textract.name: AWSNodeIconDisplayKey.textract.value,
    AWSNodeIconDisplayKey.torchServe.name: AWSNodeIconDisplayKey.torchServe.value,
    AWSNodeIconDisplayKey.transcribeAWS.name: AWSNodeIconDisplayKey.transcribeAWS.value,
    AWSNodeIconDisplayKey.translate.name: AWSNodeIconDisplayKey.translate.value,
    # AWSManagementGovernanceNodeIconKey
    AWSNodeIconDisplayKey.appConfig.name: AWSNodeIconDisplayKey.appConfig.value,
    AWSNodeIconDisplayKey.autoScaling.name: AWSNodeIconDisplayKey.autoScaling.value,
    AWSNodeIconDisplayKey.backintAgent.name: AWSNodeIconDisplayKey.backintAgent.value,
    AWSNodeIconDisplayKey.chatbot.name: AWSNodeIconDisplayKey.chatbot.value,
    AWSNodeIconDisplayKey.cloudFormation.name: AWSNodeIconDisplayKey.cloudFormation.value,
    AWSNodeIconDisplayKey.cloudTrail.name: AWSNodeIconDisplayKey.cloudTrail.value,
    AWSNodeIconDisplayKey.cloudWatch.name: AWSNodeIconDisplayKey.cloudWatch.value,
    AWSNodeIconDisplayKey.config.name: AWSNodeIconDisplayKey.config.value,
    AWSNodeIconDisplayKey.controlTower.name: AWSNodeIconDisplayKey.controlTower.value,
    AWSNodeIconDisplayKey.distroForOpenTelemetry.name: AWSNodeIconDisplayKey.distroForOpenTelemetry.value,
    AWSNodeIconDisplayKey.faultInjectionSimulator.name: AWSNodeIconDisplayKey.faultInjectionSimulator.value,
    AWSNodeIconDisplayKey.launchWizard.name: AWSNodeIconDisplayKey.launchWizard.value,
    AWSNodeIconDisplayKey.licenseManager.name: AWSNodeIconDisplayKey.licenseManager.value,
    AWSNodeIconDisplayKey.managedGrafana.name: AWSNodeIconDisplayKey.managedGrafana.value,
    AWSNodeIconDisplayKey.managedServiceForPrometheus.name: AWSNodeIconDisplayKey.managedServiceForPrometheus.value,
    AWSNodeIconDisplayKey.managementConsole.name: AWSNodeIconDisplayKey.managementConsole.value,
    AWSNodeIconDisplayKey.opsWorks.name: AWSNodeIconDisplayKey.opsWorks.value,
    AWSNodeIconDisplayKey.organizations.name: AWSNodeIconDisplayKey.organizations.value,
    AWSNodeIconDisplayKey.personalHealthDashboard.name: AWSNodeIconDisplayKey.personalHealthDashboard.value,
    AWSNodeIconDisplayKey.proton.name: AWSNodeIconDisplayKey.proton.value,
    AWSNodeIconDisplayKey.resilienceHub.name: AWSNodeIconDisplayKey.resilienceHub.value,
    AWSNodeIconDisplayKey.resourceExplorer.name: AWSNodeIconDisplayKey.resourceExplorer.value,
    AWSNodeIconDisplayKey.serviceCatalog.name: AWSNodeIconDisplayKey.serviceCatalog.value,
    AWSNodeIconDisplayKey.serviceManagementConnector.name: AWSNodeIconDisplayKey.serviceManagementConnector.value,
    AWSNodeIconDisplayKey.systemsManager.name: AWSNodeIconDisplayKey.systemsManager.value,
    AWSNodeIconDisplayKey.trustedAdvisor.name: AWSNodeIconDisplayKey.trustedAdvisor.value,
    AWSNodeIconDisplayKey.wellArchitectedTool.name: AWSNodeIconDisplayKey.wellArchitectedTool.value,
    # AWSMediaServicesNodeIconKey
    AWSNodeIconDisplayKey.elasticTranscoder.name: AWSNodeIconDisplayKey.elasticTranscoder.value,
    AWSNodeIconDisplayKey.elementalAppliancesAndSoftware.name: AWSNodeIconDisplayKey.elementalAppliancesAndSoftware.value,
    AWSNodeIconDisplayKey.elementalConductor.name: AWSNodeIconDisplayKey.elementalConductor.value,
    AWSNodeIconDisplayKey.elementalDelta.name: AWSNodeIconDisplayKey.elementalDelta.value,
    AWSNodeIconDisplayKey.elementalLink.name: AWSNodeIconDisplayKey.elementalLink.value,
    AWSNodeIconDisplayKey.elementalLive.name: AWSNodeIconDisplayKey.elementalLive.value,
    AWSNodeIconDisplayKey.elementalMediaConnect.name: AWSNodeIconDisplayKey.elementalMediaConnect.value,
    AWSNodeIconDisplayKey.elementalMediaConvert.name: AWSNodeIconDisplayKey.elementalMediaConvert.value,
    AWSNodeIconDisplayKey.elementalMediaLive.name: AWSNodeIconDisplayKey.elementalMediaLive.value,
    AWSNodeIconDisplayKey.elementalMediaPackage.name: AWSNodeIconDisplayKey.elementalMediaPackage.value,
    AWSNodeIconDisplayKey.elementalMediaStore.name: AWSNodeIconDisplayKey.elementalMediaStore.value,
    AWSNodeIconDisplayKey.elementalMediaTailor.name: AWSNodeIconDisplayKey.elementalMediaTailor.value,
    AWSNodeIconDisplayKey.elementalServer.name: AWSNodeIconDisplayKey.elementalServer.value,
    AWSNodeIconDisplayKey.interactiveVideoService.name: AWSNodeIconDisplayKey.interactiveVideoService.value,
    AWSNodeIconDisplayKey.nimbleStudio.name: AWSNodeIconDisplayKey.nimbleStudio.value,
    # AWSMigrationTransferNodeIconKey
    AWSNodeIconDisplayKey.applicationDiscoveryService.name: AWSNodeIconDisplayKey.applicationDiscoveryService.value,
    AWSNodeIconDisplayKey.applicationMigrationService.name: AWSNodeIconDisplayKey.applicationMigrationService.value,
    AWSNodeIconDisplayKey.dataSync.name: AWSNodeIconDisplayKey.dataSync.value,
    AWSNodeIconDisplayKey.mainframeModernization.name: AWSNodeIconDisplayKey.mainframeModernization.value,
    AWSNodeIconDisplayKey.migrationEvaluator.name: AWSNodeIconDisplayKey.migrationEvaluator.value,
    AWSNodeIconDisplayKey.migrationHub.name: AWSNodeIconDisplayKey.migrationHub.value,
    AWSNodeIconDisplayKey.serverMigrationService.name: AWSNodeIconDisplayKey.serverMigrationService.value,
    AWSNodeIconDisplayKey.transferFamily.name: AWSNodeIconDisplayKey.transferFamily.value,
    # AWSNetworkingContentDeliveryNodeIconKey
    AWSNodeIconDisplayKey.appMesh.name: AWSNodeIconDisplayKey.appMesh.value,
    AWSNodeIconDisplayKey.clientVPN.name: AWSNodeIconDisplayKey.clientVPN.value,
    AWSNodeIconDisplayKey.cloudDirectory.name: AWSNodeIconDisplayKey.cloudDirectory.value,
    AWSNodeIconDisplayKey.cloudFront.name: AWSNodeIconDisplayKey.cloudFront.value,
    AWSNodeIconDisplayKey.cloudMap.name: AWSNodeIconDisplayKey.cloudMap.value,
    AWSNodeIconDisplayKey.cloudWAN.name: AWSNodeIconDisplayKey.cloudWAN.value,
    AWSNodeIconDisplayKey.directConnect.name: AWSNodeIconDisplayKey.directConnect.value,
    AWSNodeIconDisplayKey.elasticLoadBalancing.name: AWSNodeIconDisplayKey.elasticLoadBalancing.value,
    AWSNodeIconDisplayKey.globalAccelerator.name: AWSNodeIconDisplayKey.globalAccelerator.value,
    AWSNodeIconDisplayKey.private5G.name: AWSNodeIconDisplayKey.private5G.value,
    AWSNodeIconDisplayKey.privateLink.name: AWSNodeIconDisplayKey.privateLink.value,
    AWSNodeIconDisplayKey.route53.name: AWSNodeIconDisplayKey.route53.value,
    AWSNodeIconDisplayKey.siteToSite.name: AWSNodeIconDisplayKey.siteToSite.value,
    AWSNodeIconDisplayKey.transitGateway.name: AWSNodeIconDisplayKey.transitGateway.value,
    AWSNodeIconDisplayKey.verifiedAccess.name: AWSNodeIconDisplayKey.verifiedAccess.value,
    AWSNodeIconDisplayKey.vpc.name: AWSNodeIconDisplayKey.vpc.value,
    AWSNodeIconDisplayKey.vpcLattice.name: AWSNodeIconDisplayKey.vpcLattice.value,
    # AWSResourceNetworkingContentDeliveryNodeIconKey
    AWSNodeIconDisplayKey.elbApplicationLoadBalancer.name: AWSNodeIconDisplayKey.elbApplicationLoadBalancer.value,
    AWSNodeIconDisplayKey.elbClassicLoadBalancer.name: AWSNodeIconDisplayKey.elbClassicLoadBalancer.value,
    AWSNodeIconDisplayKey.elbGatewayLoadBalancer.name: AWSNodeIconDisplayKey.elbGatewayLoadBalancer.value,
    AWSNodeIconDisplayKey.elbNetworkLoadBalancer.name: AWSNodeIconDisplayKey.elbNetworkLoadBalancer.value,
    AWSNodeIconDisplayKey.route53RouteTable.name: AWSNodeIconDisplayKey.route53RouteTable.value,
    AWSNodeIconDisplayKey.vpcAlt.name: AWSNodeIconDisplayKey.vpcAlt.value,
    AWSNodeIconDisplayKey.vpcCarrierGateway.name: AWSNodeIconDisplayKey.vpcCarrierGateway.value,
    AWSNodeIconDisplayKey.vpcCustomerGateway.name: AWSNodeIconDisplayKey.vpcCustomerGateway.value,
    AWSNodeIconDisplayKey.vpcElasticNetworkAdapter.name: AWSNodeIconDisplayKey.vpcElasticNetworkAdapter.value,
    AWSNodeIconDisplayKey.vpcElasticNetworkInterface.name: AWSNodeIconDisplayKey.vpcElasticNetworkInterface.value,
    AWSNodeIconDisplayKey.vpcEndpoints.name: AWSNodeIconDisplayKey.vpcEndpoints.value,
    AWSNodeIconDisplayKey.vpcFlowLogs.name: AWSNodeIconDisplayKey.vpcFlowLogs.value,
    AWSNodeIconDisplayKey.vpcInternetGateway.name: AWSNodeIconDisplayKey.vpcInternetGateway.value,
    AWSNodeIconDisplayKey.vpcNATGateway.name: AWSNodeIconDisplayKey.vpcNATGateway.value,
    AWSNodeIconDisplayKey.vpcNetworkAccessAnalyzer.name: AWSNodeIconDisplayKey.vpcNetworkAccessAnalyzer.value,
    AWSNodeIconDisplayKey.vpcNetworkAccessControlList.name: AWSNodeIconDisplayKey.vpcNetworkAccessControlList.value,
    AWSNodeIconDisplayKey.vpcPeeringConnection.name: AWSNodeIconDisplayKey.vpcPeeringConnection.value,
    AWSNodeIconDisplayKey.vpcReachabilityAnalyzer.name: AWSNodeIconDisplayKey.vpcReachabilityAnalyzer.value,
    AWSNodeIconDisplayKey.vpcRouter.name: AWSNodeIconDisplayKey.vpcRouter.value,
    AWSNodeIconDisplayKey.vpcTrafficMirroring.name: AWSNodeIconDisplayKey.vpcTrafficMirroring.value,
    AWSNodeIconDisplayKey.vpcVPNGateway.name: AWSNodeIconDisplayKey.vpcVPNGateway.value,
    # AWSSecurityIdentityComplianceNodeIconKey
    AWSNodeIconDisplayKey.auditManager.name: AWSNodeIconDisplayKey.auditManager.value,
    AWSNodeIconDisplayKey.certificateManager.name: AWSNodeIconDisplayKey.certificateManager.value,
    AWSNodeIconDisplayKey.cloudHSM.name: AWSNodeIconDisplayKey.cloudHSM.value,
    AWSNodeIconDisplayKey.cognito.name: AWSNodeIconDisplayKey.cognito.value,
    AWSNodeIconDisplayKey.detective.name: AWSNodeIconDisplayKey.detective.value,
    AWSNodeIconDisplayKey.directoryService.name: AWSNodeIconDisplayKey.directoryService.value,
    AWSNodeIconDisplayKey.firewallManager.name: AWSNodeIconDisplayKey.firewallManager.value,
    AWSNodeIconDisplayKey.guardDuty.name: AWSNodeIconDisplayKey.guardDuty.value,
    AWSNodeIconDisplayKey.iamIdentityCenter.name: AWSNodeIconDisplayKey.iamIdentityCenter.value,
    AWSNodeIconDisplayKey.identityAndAccessManagement.name: AWSNodeIconDisplayKey.identityAndAccessManagement.value,
    AWSNodeIconDisplayKey.inspector.name: AWSNodeIconDisplayKey.inspector.value,
    AWSNodeIconDisplayKey.keyManagementService.name: AWSNodeIconDisplayKey.keyManagementService.value,
    AWSNodeIconDisplayKey.macie.name: AWSNodeIconDisplayKey.macie.value,
    AWSNodeIconDisplayKey.networkFirewall.name: AWSNodeIconDisplayKey.networkFirewall.value,
    AWSNodeIconDisplayKey.privateCertificateAuthority.name: AWSNodeIconDisplayKey.privateCertificateAuthority.value,
    AWSNodeIconDisplayKey.resourceAccessManager.name: AWSNodeIconDisplayKey.resourceAccessManager.value,
    AWSNodeIconDisplayKey.secretsManager.name: AWSNodeIconDisplayKey.secretsManager.value,
    AWSNodeIconDisplayKey.securityHub.name: AWSNodeIconDisplayKey.securityHub.value,
    AWSNodeIconDisplayKey.securityLake.name: AWSNodeIconDisplayKey.securityLake.value,
    AWSNodeIconDisplayKey.shield.name: AWSNodeIconDisplayKey.shield.value,
    AWSNodeIconDisplayKey.signer.name: AWSNodeIconDisplayKey.signer.value,
    AWSNodeIconDisplayKey.verifiedPermissions.name: AWSNodeIconDisplayKey.verifiedPermissions.value,
    AWSNodeIconDisplayKey.waf.name: AWSNodeIconDisplayKey.waf.value,
    # AWSStorageNodeIconKey
    AWSNodeIconDisplayKey.backup.name: AWSNodeIconDisplayKey.backup.value,
    AWSNodeIconDisplayKey.ebs.name: AWSNodeIconDisplayKey.ebs.value,
    AWSNodeIconDisplayKey.efs.name: AWSNodeIconDisplayKey.efs.value,
    AWSNodeIconDisplayKey.elasticDisasterRecovery.name: AWSNodeIconDisplayKey.elasticDisasterRecovery.value,
    AWSNodeIconDisplayKey.fileCache.name: AWSNodeIconDisplayKey.fileCache.value,
    AWSNodeIconDisplayKey.fsx.name: AWSNodeIconDisplayKey.fsx.value,
    AWSNodeIconDisplayKey.fsxForLustre.name: AWSNodeIconDisplayKey.fsxForLustre.value,
    AWSNodeIconDisplayKey.fsxForNetAppONTAP.name: AWSNodeIconDisplayKey.fsxForNetAppONTAP.value,
    AWSNodeIconDisplayKey.fsxForOpenZFS.name: AWSNodeIconDisplayKey.fsxForOpenZFS.value,
    AWSNodeIconDisplayKey.fsxForWFS.name: AWSNodeIconDisplayKey.fsxForWFS.value,
    AWSNodeIconDisplayKey.s3.name: AWSNodeIconDisplayKey.s3.value,
    AWSNodeIconDisplayKey.s3Glacier.name: AWSNodeIconDisplayKey.s3Glacier.value,
    AWSNodeIconDisplayKey.snowball.name: AWSNodeIconDisplayKey.snowball.value,
    AWSNodeIconDisplayKey.snowballEdge.name: AWSNodeIconDisplayKey.snowballEdge.value,
    AWSNodeIconDisplayKey.snowcone.name: AWSNodeIconDisplayKey.snowcone.value,
    AWSNodeIconDisplayKey.snowmobile.name: AWSNodeIconDisplayKey.snowmobile.value,
    AWSNodeIconDisplayKey.storageGateway.name: AWSNodeIconDisplayKey.storageGateway.value,
    # AWSOthersNodeIconKey
    AWSNodeIconDisplayKey.braket.name: AWSNodeIconDisplayKey.braket.value,
    AWSNodeIconDisplayKey.groundStation.name: AWSNodeIconDisplayKey.groundStation.value,
    AWSNodeIconDisplayKey.managedBlockchain.name: AWSNodeIconDisplayKey.managedBlockchain.value,
    AWSNodeIconDisplayKey.marketplace.name: AWSNodeIconDisplayKey.marketplace.value,
    AWSNodeIconDisplayKey.quantumLedgerDatabase.name: AWSNodeIconDisplayKey.quantumLedgerDatabase.value,
    AWSNodeIconDisplayKey.roboMaker.name: AWSNodeIconDisplayKey.roboMaker.value,
    AWSNodeIconDisplayKey.singleSignOn.name: AWSNodeIconDisplayKey.singleSignOn.value,
}

GENERIC_LABEL_MAPPING = {
    GenericNodeIconDisplayKey.firewall.name: GenericNodeIconDisplayKey.firewall.value,
    GenericNodeIconDisplayKey.forums.name: GenericNodeIconDisplayKey.forums.value,
    GenericNodeIconDisplayKey.genericApplication.name: GenericNodeIconDisplayKey.genericApplication.value,
    GenericNodeIconDisplayKey.genericDatabase.name: GenericNodeIconDisplayKey.genericDatabase.value,
    GenericNodeIconDisplayKey.genericManagementConsole.name: GenericNodeIconDisplayKey.genericManagementConsole.value,
    GenericNodeIconDisplayKey.genericServer.name: GenericNodeIconDisplayKey.genericServer.value,
    GenericNodeIconDisplayKey.genericServers.name: GenericNodeIconDisplayKey.genericServers.value,
    GenericNodeIconDisplayKey.genericShield.name: GenericNodeIconDisplayKey.genericShield.value,
    GenericNodeIconDisplayKey.internet.name: GenericNodeIconDisplayKey.internet.value,
    GenericNodeIconDisplayKey.router.name: GenericNodeIconDisplayKey.router.value,
    GenericNodeIconDisplayKey.switch.name: GenericNodeIconDisplayKey.switch.value,
    GenericNodeIconDisplayKey.credentials.name: GenericNodeIconDisplayKey.credentials.value,
    GenericNodeIconDisplayKey.dataStream.name: GenericNodeIconDisplayKey.dataStream.value,
    GenericNodeIconDisplayKey.dataTable.name: GenericNodeIconDisplayKey.dataTable.value,
    GenericNodeIconDisplayKey.document.name: GenericNodeIconDisplayKey.document.value,
    GenericNodeIconDisplayKey.documents.name: GenericNodeIconDisplayKey.documents.value,
    GenericNodeIconDisplayKey.email.name: GenericNodeIconDisplayKey.email.value,
    GenericNodeIconDisplayKey.folder.name: GenericNodeIconDisplayKey.folder.value,
    GenericNodeIconDisplayKey.folders.name: GenericNodeIconDisplayKey.folders.value,
    GenericNodeIconDisplayKey.gitRepository.name: GenericNodeIconDisplayKey.gitRepository.value,
    GenericNodeIconDisplayKey.logs.name: GenericNodeIconDisplayKey.logs.value,
    GenericNodeIconDisplayKey.sdk.name: GenericNodeIconDisplayKey.sdk.value,
    GenericNodeIconDisplayKey.sourceCode.name: GenericNodeIconDisplayKey.sourceCode.value,
    GenericNodeIconDisplayKey.sslPadlock.name: GenericNodeIconDisplayKey.sslPadlock.value,
    GenericNodeIconDisplayKey.user.name: GenericNodeIconDisplayKey.user.value,
    GenericNodeIconDisplayKey.userAuthenticated.name: GenericNodeIconDisplayKey.userAuthenticated.value,
    GenericNodeIconDisplayKey.users.name: GenericNodeIconDisplayKey.users.value,
    GenericNodeIconDisplayKey.camera.name: GenericNodeIconDisplayKey.camera.value,
    GenericNodeIconDisplayKey.client.name: GenericNodeIconDisplayKey.client.value,
    GenericNodeIconDisplayKey.disk.name: GenericNodeIconDisplayKey.disk.value,
    GenericNodeIconDisplayKey.gear.name: GenericNodeIconDisplayKey.gear.value,
    GenericNodeIconDisplayKey.multimedia.name: GenericNodeIconDisplayKey.multimedia.value,
    GenericNodeIconDisplayKey.officeBuilding.name: GenericNodeIconDisplayKey.officeBuilding.value,
    GenericNodeIconDisplayKey.tapeStorage.name: GenericNodeIconDisplayKey.tapeStorage.value,
    GenericNodeIconDisplayKey.toolkit.name: GenericNodeIconDisplayKey.toolkit.value,
    GenericNodeIconDisplayKey.baseStation.name: GenericNodeIconDisplayKey.baseStation.value,
    GenericNodeIconDisplayKey.genericActuator.name: GenericNodeIconDisplayKey.genericActuator.value,
    GenericNodeIconDisplayKey.genericPLC.name: GenericNodeIconDisplayKey.genericPLC.value,
    GenericNodeIconDisplayKey.genericSensor.name: GenericNodeIconDisplayKey.genericSensor.value,
    GenericNodeIconDisplayKey.historianDatabase.name: GenericNodeIconDisplayKey.historianDatabase.value,
    GenericNodeIconDisplayKey.iotGateway.name: GenericNodeIconDisplayKey.iotGateway.value,
}

MXGRAPH_TO_LABEL_MAPPING = {
    **AWS_LABEL_MAPPING,
    **GENERIC_LABEL_MAPPING,
}